### ISSUE TITLE
"Symbol not found" error when using OpenGL/Renderscript with functions with update definitions

### ISSUE THREAD

**Issue by bleibig** [halide/Halide#1004]
When using targets that use the image_load/image_store intrinsics in the Halide IR (currently Renderscript and OpenGL), compilation fails when using a function with update definitions that isn't the final function in the pipeline. E.g. the following code:

``` c++
#include "Halide.h"

using namespace Halide;

int main() {
    Var x("x"), y("y"), c("c");
    Func f("f"), g("g");

    f(x, y, c) = undef<int>();
    f(x, y, 0) = x + y;
    f(x, y, 1) = x - y;
    f(x, y, 2) = x * y;

    g(x, y, c) = f(x, y, c);

    g.bound(c, 0, 3);
    g.glsl(x, y, c);

    Target t(get_host_target());
    t.set_feature(Target::OpenGL);

    g.realize(100, 100, 3, t);
    return 0;
}
```

Running causes the following error:

```
Internal error at /Users/brian/src/Halide/src/CodeGen_LLVM.cpp:886
Symbol not found: f.buffer
```

You can change the `glsl` call to `g.shader(x, y, c, DeviceAPI::Renderscript);` and the `OpenGL` target to `Renderscript`, and you get the same error.

**Comment by zvookin** [comment]
Fundamental issue is this is a reduction, by virtue of the update stages, inside of a GLSL shader. This actually almost works in this case because the compiler is doing well with bounds inference and is generating a small stack allocation for the result of f at each shader position, but the GLSL backend requires that this temporary be a texture and thus it does not turn into a small array on the stack in the shader code. There is no way the current approach is compilable. So the fix here is to generate an error earlier on in the compilation.

The varying attributes code is also generating a ton of vertex properties for this, which is disconcerting as it is a fairly simple case.

Scheduling f compute_root() fixes the compilation failure and would likely be required for any reduction that is more complex.

**Comment by steven-johnson** [comment]
RenderScript support is long-gone; closing this issue.
