### ISSUE TITLE
Deadlock on Windows in unique_name() on DLL loading.

### ISSUE THREAD

**Issue by wampler** [halide/Halide#1064]
The lock_guard in unique_name() in Util.cpp seems to cause a deadlock on Windows (at least Windows 7) when Halide.dll is loaded. The issue is in the constructor of the placeholder Vars (i.e. _, _0, _1, etc.), which ends up calling unique_name() during static initialization. As per the discussion at http://stackoverflow.com/questions/14711263/c11-stdmutex-in-visual-studio-2012-deadlock-when-locked-from-dllmain locking from within DllMain() can lead to deadlock (and on my system, it is).

I don't have an easy solution other than removing the lock from within unique_name() and living with the lack of thread safety, but hopefully someone else has a better idea.

**Comment by zvookin** [comment]
This is kind of a mess in that there are two implementations of unique_name, one of which uses a 256 entry table and atomic increment and the other a general hash table to handle arbitrary length strings. They can overlap in names as demonstrated by the following code:

```
#include "Halide.h"
#include <iostream>
#include <sstream>

using namespace Halide;

int main(int argc, char **argv) {
    for (int i = 0; i < 40; i++) {
        std::string char_name = Internal::unique_name('_');
        std::ostringstream oss;
        oss << '_' << i;
        std::string str_name = Internal::unique_name(oss.str());

        std::cout << "Char name: " << char_name << " str name: " << str_name << std::endl;
    }
}
```

The attempt by Var to protect its names from being returned by unique_name doesn't work for the char version. I have an on how to fix this, relying on the character prefix version not using locks.

**Comment by zvookin** [comment]
Does 9114aa6b580c4f092df40b1137bc948218f7b6d5 fix this?

**Comment by dsharletg** [comment]
I think maybe we can fix this more reliably: unique_name(char) doesn't need any locks, and unique_name(std::string s) can just check if s has length 1 (rather than use is_implicit), if so, call unique_name(char). None of that requires locking; a lock is only required if s has length > 1. 

So, as long as we don't call unique_name with a string of length > 1 from a static constructor, we should be safe...

**Comment by dsharletg** [comment]
Actually, this just looks totally broken: unique_name returns a new name that isn't even being used. I'm going to make a branch with these changes.

**Comment by zvookin** [comment]
So I wrote a more sophisticated version along those lines. The implicits
are not actually single character, they are explicitly "_0", "_1", etc. If
we actually carve those out from the single character version, then the
CodeGen_C test breaks because the names it generates change and the test
does a simple textual compare of expected results. (I just added code to
offset the _ entry in the atomic table by 100. Now I could update the
CodeGen_C test, but the fact that its names are already colliding with the
implicits indicates it isn't a problem and I kind of feel like the char
version of make_unique isn't intended to be mutually exclusive with
everything, etc. I.e. we very likely have more than one uniqueness domain
here...)

The change I originally made also worked to get the two versions of
unique_name to be mutually unique, etc. It did so by inserting $ characters
into anything that might match the pattern of the single character
allocator. But I decided not to commit that because really there is not
enough information to say what uniqueness is really required. (The case
that they collide was given in the issue I thing. Basically
make_unique("a0") == make_unique('a') the first time each is called.) Also,
inserting $'s where there were none before is dangerous as $ signs are not
legal as identifiers in various languages we gen code for. E.g. The single
char version of make_unique is guaranteed to be $ free unless one passes $
as the char.

It seems silly that the Var constructor allocates the unique name, but it
sort of makes sense as the way to make sure it doesn't collide.

Also there are cases like Lambda.h doing:
        Func f("lambda" + Internal::unique_name('_'));
which failed when I put a $ in the thing returned from unique_name. This is
not needed for correctness as the Func constructor turns around and calls
unique_name on the passed in name again. It does however make the names use
_ instead of $ between the name and the number.

Anyway, after learning all this the hard way, I decided to step back and
make the smallest fix I could to (hoefully) unbreak Windows. I threw in a
couple TODOs, as yeah, we need to do something better with all this.

-Z-
