### ISSUE TITLE
Specialization with Var or RVar in condition should produce nicer error message

### ISSUE THREAD

**Issue by gkanwar** [halide/Halide#1077]
Error example:
```
using namespace Halide;
using namespace std;

int main(int argc, char** argv) {
  Var x("x"),y("y");

  Func f("f");
  f(x,y) = select(x > 0, x*y, -x*y);

  RDom r(0, 10, 0, 10);
  Func g("g");
  g() = Expr(0.0);
  g() += f(r.x,r.y);

  // Attempt to specialize incorrectly                                                     
  g.update(0).specialize(r.x > 0);

  Image<float> out(g.realize(10,10));
}
```

Gives output:
```
Internal error at /home/halidenightly/build_bot/slave/linux-64-gcc49-trunk/halide/src/CodeGen_LLVM.cpp:896
Symbol not found: r4.x$r
```

**Comment by abadams** [comment]
This is a missing error message. The condition in the specialize can't
depend on any Vars or RVars - the generated if statement goes outside all
the loops.

You probably want to split your positive and negative cases into separate
update definitions, instead of a single update definition with a select.
You can also exploit "likely" to do loop partitioning, if you have a select
that you want to simplify away in the common case.

**Comment by gkanwar** [comment]
Ah yep, you're right. Updated the issue description.
