### ISSUE TITLE
GPU tutorial not working on Mac Pro

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#1147]
Using commit a7f3fcec7bc (I also tried HEAD~100 with the same results):

```
$ g++ lesson_12*.cpp -g -std=c++11 -I ../include -I ../tools -L ../bin -lHalide `libpng-config --cflags --ldflags` -o lesson_12
```

```
$ DYLD_LIBRARY_PATH=../bin ./lesson_12
Testing performance on CPU:
1.8867 milliseconds
Testing performance on GPU:
0.3758 milliseconds
Mismatch between output (255) and reference output (9) at 370, 98, 0
```

This is on a MacPro6,1 OS X 10.11.4, LLVM 3.8. I've attached the output with `HL_DEBUG_CODEGEN=1`:  [lesson12.txt](https://github.com/halide/Halide/files/230762/lesson12.txt)

**Comment by abadams** [comment]
Damn, the macpro buildbot also has this error but it wasn't causing the
build to count as failed. Will investigate.

**Comment by abadams** [comment]
Ok, the issue is that the OpenCL drivers on mac pros are broken and ancient, and Apple doesn't care. Shared memory claims to work but doesn't. I switched the tutorial to use the metal backend instead when on OSX. That seems to work and has good performance. Please let me know if it works for you too.

I'll ping @zvookin so he knows the metal backend is now in use in the tutorials.

**Comment by shoaibkamil** [comment]
I can confirm this works on my home machine (iMac17,1), which also had the same issue with OpenCL.  Thanks!  Unfortunate that those drivers are so broken.
