### ISSUE TITLE
buffer_t's don't track type information; would be useful for OpenGL backend

### ISSUE THREAD

**Issue by nickchornay** [halide/Halide#118]
OpenGL requires knowledge of the input data format when dealing with textures. The buffer_t that gets passed to the runtime functions lacks type information.

**Comment by steven-johnson** [comment]
Bumping this issue for discussion again; trying to write code that can perform operations on arbitrary buffer_t's is currently infeasible due to the lack of type information. We really need to add the equivalent of a Halide::Type. (In code I'm working on I'm able to track this by passing along extra metadata, but this is awkward and suboptimal.)

**Comment by abadams** [comment]
Yes, we need type and dimensionality (I've encountered a few bugs due to a
buffer of the wrong dimensionality being passed in).

Once all the outstanding PRs refactoring core codegen are merged in (mostly
gpu api naming), we should make a breaking change to buffer_t.

**Comment by zvookin** [comment]
I'm going to close this now that halide_buffer_t has landed.
