### ISSUE TITLE
Undefined symbol in Python wrapper

### ISSUE THREAD

**Issue by stefanv** [halide/Halide#1297]
After a successful compile of the Python wrapper, upon import I see:

```
ImportError: /home/stefan/src/Halide/python_bindings/build/halide.so: undefined symbol: _ZNK6Halide8Internal8ExprNodeINS0_8FloatImmEE6acceptEPNS0_9IRVisitorE
```

I followed these build instructions:
- Download halide binary from `https://github.com/halide/Halide/releases`, place in `~/src/halide-binary`
- Clone `https://github.com/halide/Halide.git`
- `cd python_bindings && mkdir build && cd build`
- `cmake -DHALIDE_LIBRARIES=${HOME}/src/halide-binary/lib  -DHALIDE_INCLUDE_DIR=${HOME}/src/halide-binary/include ..`
- `make`

Platform: `Linux shinobi 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by abadams** [comment]
The better-tested way to build the python bindings is to use the Makefile.
In the root halide source folder try something like:

make -j8  && make -C python_bindings test -j8

**Comment by lengoanhcat** [comment]
Recently, I tried to compile python_binding interface of Halide as well. Adam's advise is great; however, there is a minor problem ( at least known in Ubuntu ) with linking step to create shared library. The problem is ordering of ../lib/libHalide.a and other additional shared dynamic library. As the current Makefile places ../lib/libHalide.a after other shared libraries, created halide.so does not include necessary symbols like crc32, setupterm, etc. The solution is changing the following line in python_binding\Makefile:

$(CXX) $(PY_OBJS) $(NUMPY_OBJS) $(LDFLAGS) ../lib/libHalide.a -shared -o $@

... to ...

$(CXX) $(PY_OBJS) $(NUMPY_OBJS) ../lib/libHalide.a $(LDFLAGS) -shared -o $@

Then, halide.so should be compiled, tested and imported nicely. Hope this help.

**Comment by KlamerS** [comment]
In addition, I have added (on Ubuntu 14.04) $(shell llvm-config --system-libs) to the LDFLAGS line to link halide.so to the libraries needed by halide.
