### ISSUE TITLE
TIFF IO examples?

### ISSUE THREAD

**Issue by hirokai** [halide/Halide#130]
I've been trying Halide for a while for the analysis of microscopy images, and I was fascinated by its design principle as well as ease of use. (I have some background in Haskell, and the concept of defining algorithms in an abstract and purely-functional way sounds promising to me.)

One thing I found missing in the examples in the repo was TIFF loading/saving. TIFF is the most common format for biological imaging, and I quickly wrote an example of a TIFF load function using libtiff.

https://gist.github.com/hirokai/6154129

Are you interested in merging something like this into your example, e.g, to `apps/support/image_io.h`?

**Comment by dsharletg** [comment]
We now have TIFF support, sorry for the late response.

**Comment by mihai-mc** [comment]
@dsharletg there is no loading support for tiff files - https://github.com/halide/Halide/blob/288526cf7500f496c36eb0e74500e4fd4547b6fb/tools/halide_image_io.h#L1683

**Comment by steven-johnson** [comment]
> @dsharletg there is no loading support for tiff files:

That's correct. TIFF has many variants and options and handling them all requires libtiff or something similar -- since there have been closet-to-zero requests for tiff loading (aside from this, AFAIK) we've never thought it worth adding another external library dependency. (I suspect we'd consider a PR that added it, assuming the dependencies involved were small and manageable.)
