### ISSUE TITLE
Makefile Error line 781

### ISSUE THREAD

**Issue by RileyLee** [halide/Halide#1300]
Hey guys,

I'm trying to make Halide_release2016-04-27 with llvm3.7. Error popped up at line 781, when it's trying to compile test_internal.cpp

here are the errors:
bin/libHalide.so: undefined reference to `Halide::Internal::CodeGen_GPU_Host<Halide::Internal::CodeGen_PowerPC>::CodeGen_GPU_Host(Halide::Target)'
bin/libHalide.so: undefined reference to`Halide::Internal::CodeGen_GPU_HostHalide::Internal::CodeGen_ARM::CodeGen_GPU_Host(Halide::Target)'
bin/libHalide.so: undefined reference to `Halide::Internal::CodeGen_GPU_Host<Halide::Internal::CodeGen_MIPS>::CodeGen_GPU_Host(Halide::Target)'
bin/libHalide.so: undefined reference to`llvm::IRBuilderBase::CreateGlobalString(llvm::StringRef, llvm::Twine const&)'
bin/libHalide.so: undefined reference to `llvm::CallInst::init(llvm::Value_, llvm::ArrayRef<llvm::Value_>, llvm::Twine const&)'
collect2: error: ld returned 1 exit status
Makefile:781: recipe for target 'bin/test_internal' failed
make: **\* [bin/test_internal] Error 1

Does anyone know how I could fix this?

thanks

**Comment by zvookin** [comment]
The undefined references to MIPS and POWERPC might be fixed by setting
WITH_MIPS and WITH_POWERPC to the empty string either on the make command
line or in the Makefile. Also be sure to do a make clean on everything to
make sure the compiles are consistent.

How are you getting llvm? The last error above ("undefined reference to
`llvm::CallInst::init...") looks like what happens when llvm's headers and
objects are inconsistent somehow and the API has changed. (If it is a
straight up versioning issue against the API, then the code doesn't compile
at all. In this case, the code has compiled but is not linking.)

-Z-
