### ISSUE TITLE
Bounds are not tight using a combination of rfactor() and split()

### ISSUE THREAD

**Issue by jingpu** [halide/Halide#1516]
I find the bounds inference doesn't give a tight bound when using a combination of `rfactor()` and `split()` primitives.

```
RDom r(0, 20, 0, 30);
f(x, y) = x - y;
g(x, y) = 1;
g(r.x, r.y) += f(r.x, r.y);

g.update(0).split(r.x, rxo, rxi, 2);
f.compute_at(g, rxo);
g.update(0).rfactor({{rxo, u}});
```

Without the last `rfactor()` call, the allocation bound of `f` is 2x30, while with `rfactor()` added the allocation bound of `f` becomes 20x30 (the same as `f.compute_root()` schedule gives).
I suspect it is related to the implementation of `Stage::purify()`, but haven't actually located the issue.

**Comment by psuriana** [comment]
The bugs seems to be in allocation bounds inference. It defines the bound "correctly" as: `let f.y.max_realized = max(g_intm.s1.r4$y.max, f.s0.y.max)`, but, it is using the wrong `g_intm.s1.r4$y.max`. `g_intm.s1.r4$y.max` is redefined into `let g_intm.s1.r4$y.max = g_intm.s1.r4$y` inside the consume `f` node, and it should have used that value instead of using the original `g_intm.s1.r4$y.max`,  which is 29. I'll look into this.

**Comment by dsharletg** [comment]
It looks like this was fixed by the above PR.
