### ISSUE TITLE
Some tests require assert() for correctness

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#1565]
Specifically, test/error/wrong_type and test/error/float16_t_implicit_downcast assume that the assert() macros in HalideBuffer.h will be tested and fail, which may not be the case for all build environments. 

It's easy enough to ensure that NDEBUG is not defined for these, but the bigger question is whether HalideBuffer.h should use internal_assert or user_assert instead? (IMHO it should, and we should avoid plain-old assert())

**Comment by abadams** [comment]
HalideBuffer.h can't depend on Halide.h - it's a runtime header, so
internal_assert and user_assert aren't available. We could call
halide_error perhaps, but it would also be nice if that header worked
without a halide runtime linked in. It doesn't currently work to do that
due to the call to halide_device_free. I've been thinking about hiding that
call behind a template method or something so that you only need to link to
a halide runtime if you actually call that method somewhere.

I'm wary about forcing the asserts to exist in HalideBuffer itself, because
that header is a conventional header that a performance-sensitive final
binary can include, and I wanted to respect people's decision regarding
asserts in release builds.

So I guess it's probably best to undef NDEBUG in the tests that rely on
those asserts?

**Comment by steven-johnson** [comment]
Didn't think about the runtime-vs-not issue, so yeah on that. I can live with the status quo as long as we realize that the tests depend on this behavior for correctness.

(Side note: yes, it would be awesome to find a way to eliminate the need for halide_device_free)

**Comment by zvookin** [comment]
Per discussion yesterday on Generator test support, we'll likely be adding
some minimal check mechanism anyway. Can we just move to using that instead
of assert? (And said mechanism will have to be runtime only to support AOT
testing. We should consider making the check support usable without
Generator as well.)

-Z-
