### ISSUE TITLE
Broken bounds inference on master

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#1618]
Hi everyone,

It seems that bounds inference got broken by a commit in May.

I noticed that in a Sobel filter application, intermediate buffers were being greatly overdimensioned and overproduced. I have stripped the application down to an (almost?) minimal example, and identified the commit that introduced the issue.

The example is a simple vertical summing filter which is processed one horizontal line at a time. A particular stage is almost twice as large as it should be (see the comments in the source file).

A combination of a split and an unroll seems to trigger the issue.

From a git bisect, it seems the commit that first introduced the issue was in May:
2d3aab13d34754f957ab741764c8617ff09b6b20

The commit in question removed something called "split tree rebalancing", apparently because it was causing bugs. Since it seemed to have something to do with the order of applying split statements, I experimented a bit with the order of scheduling statements, but haven't found any ordering that behaves differently (none of the stages in the example have multiple splits anyway).

Example for reproduction attached. Tested on Ubuntu 16.04, LLVM 3.8.

Thanks for the help!

[Halide_BoundsError_Check.zip](https://github.com/halide/Halide/files/580533/Halide_BoundsError_Check.zip)

**Comment by SanderVocke** [comment]
Confirmed that undoing the commit in question (by re-adding the split tree rebalancing section in ScheduleFunctions.cpp) on the tip of master, fixes the issue (or at least the occurrences I observed).

But the commit mentions the rebalancing is removed because it causes other bugs in combination with TailStrategies, so I guess simply adding it back would be trading one issue for another.

**Comment by SanderVocke** [comment]
I hadn't realized that an unroll by a certain factor is a split as well. So now I understand why this has something to do with split ordering, and indeed my example does the inner split first (where the commit mentions people should generally do the outer split first).

So it seems that this may be an expected (maybe even desired?) result. But where the commit mentions split ordering causes different outcomes in a "sometimes useful way", it seems that in some cases it causes very undesirable results (such as the very inefficient result of the above example). And people may not realize that the reason their buffers are oversized is because of how they ordered their split commands - the link there is definitely not obvious.

If there is no correct way to do this split tree rebalancing, can we not just force programmers to do the outer split first, or at least warn them about the possible consequences if they don't?

**Comment by abadams** [comment]
I think there's a default we can change that will help things. First, some
explanation of current behavior:

If you do the outer split first, then you increase the size required. E.g.
the following schedule:

f.split(x, xo, xi, 1024).split(xi, xio, xii, 32)

seems similar to

f.split(x, xo, xi, 32).split(xo, xoo, xoi, 32);

Except that the former requires f to be at least 1024-wide, and the latter
only required it to be 32-wide. This is because both of these become:

f.split(x, xo, xi, 1024, TailStrategy::ShiftInwards).split(xi, xio, xii,
32, TailStrategy::ShiftInwards);
f.split(x, xo, xi, 32, TailStrategy::ShiftInwards).split(xo, xoo, xoi, 32,
TailStrategy::ShiftInwards);

ShiftInwards means that the last split N elements get pushed inwards so
that we don't compute off the edge of the region required. In the first
case, we still need to compute at least 1024 elements, and ShiftInwards
does nothing for the second split, because 1024 is an integer multiple of
32. It's equivalent to the schedule:

f.split(x, xo, xi, 1024, TailStrategy::ShiftInwards).split(xi, xio, xii,
32, TailStrategy::RoundUp);

 In the second case because we shift groups of 32 inwards, we're ok storing
to any output that is >= 32 elements, though we'll still compute at least
1024 values. (There will be lots of redundant compute). This nested
ShiftInwards is the thing making nasty complex expressions that make
allocation bounds inference very conservative.

Now, here's the default we can change. I believe the second schedule is
actually never better than this:

f.split(x, xo, xi, 32, TailStrategy::ShiftInwards).split(xo, xoo, xoi, 32,
TailStrategy::RoundUp);

If the first split already does a ShiftInwards, then you buy nothing by
making a split on the outer variable created also ShiftInwards. The *do*
mean different things. Let's change the constants so I can write down the
values computed in order. Say both splits are of size 3, and we're supposed
to be computing 10 elements. We can only compute multiples of 9 elements
due to the two splits, so we'll actually be computing 18 elements, with 8
of them redundant:

The current behavior:

.split(x, xo, xi, 3).split(xo, xoo, xoi, 3)
implies
.split(x, xo, xi, 3, ShiftInwards).split(xo, xoo, xoi, 3, ShiftInwards)


If we need to compute these values:
0 1 2 3 4 5 6 7 8 9

After the first split they get put in groups of three. Notice the last
group was pushed inwards, and we're redundantly recomputing 7 and 8.
[0 1 2] [3 4 5] [6 7 8] [7 8 9]

After the second split, we've collected these groups of 3 into groups of 3.
There are four groups, call them A, B, C, D:

A:[0 1 2] B:[3 4 5] C:[6 7 8] D:[7 8 9]

On the first iteration of this outer variable we'll compute ABC, and on the
second iteration we'll compute BCD. So the values computed are:

[[0 1 2] [3 4 5] [6 7 8]] [[3 4 5] [6 7 8] [7 8 9]]

The equivalent loop structure is:
for xoo in [0, 1]:
  for xoi in [0, 1, 2]:
    for xi in [0, 1, 2]:
      xo = min(xoo*3 + xoi, 3)
      x = min(xo*3 + xi, 9)
      compute value @ x

Now suppose we use this schedule instead:

.split(x, xo, xi, 3, ShiftInwards).split(xo, xoo, xoi, 3, RoundUp)

The first split produces the same groups
[0 1 2] [3 4 5] [6 7 8] [7 8 9]

The second split rounds up, and forces there to be 6 groups of three
instead of 4 groups of there, so we have groups ABCDEF now. But because
there's an inner ShiftInwards, groups DEF all just compute [7,8,9]:

[[0 1 2] [3 4 5] [6 7 8]] [[7 8 9] [7 8 9] [7 8 9]]

The equivalent loop is:

for xoo in [0, 1]:
  for xoi in [0, 1, 2]:
    for xi in [0, 1, 2]:
      xo = xoo*3 + xoi
      x = min(xo*3 + xi, 9)
      compute value @ x

Only the definition of xo changed. The inner ShiftInwards is sufficient to
prevent overcompute.

I think perhaps the default TailStrategy for splitting an outer variable
created by a ShiftInwards split should be RoundUp. This will produce
simpler IR, and it does indeed fix the original code.

The broader problem here is that allocation bounds inference is very
conservative, because it needs to analyze partially-lowered code. I don't
know how to fix that.

**Comment by SanderVocke** [comment]
Thanks for the in-depth response!

So it sounds like this is not so much a bug or an issue, but more like a possible point of improvement (either through having different default split settings, or a somehow more intelligent bounds inference pass).

Would you like to keep this issue open in that case, or is it better to close it?

**Comment by abadams** [comment]
Let's keep it open. I'll try implementing the different default. The
workaround is to do the splits in the other order, or to use an explicit
TailStrategy.

**Comment by abadams** [comment]
Fixed by #1639
