### ISSUE TITLE
Reductions should have more parallelism

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#1874]
A reduction like `minimum()` or `maximum()` is essentially executed serially. Neither `vectorize()` nor `gpu_tile()` perform as expected.

See [Tree Scan](https://www.cs.cmu.edu/~scandal/nesl/alg-sequence.html#treescan)

**Comment by abadams** [comment]
You can parallelize reductions - that's what rfactor is for.

The real problem here is that the built-in reduction helpers can't do any internal scheduling.

**Comment by kgnk** [comment]
Oh, that's what that's for. There needs to be a tutorial or example for `rfactor()`. The comment documentation is okay, I guess, but it would be nice to have executable code.

Getting access to the `Func` created by the reduction helpers is a separate issue that I solve by cut & paste the reduction helper source and go from there.

**Comment by kgnk** [comment]
Oh, there's already a PR #1853 for that.

**Comment by kgnk** [comment]
I've got it working in 2d on a GPU with a rather complex combination of tile, rfactor, split and vectorize. I would still like to see tile and vectorize do rfactor internally as it took me a whole day to get it right.

**Comment by zvookin** [comment]
Please feel free to elaborate on your ideas for making this easier. I expect what you are envisioning is a higher-level primitive than tile or vectorize rather than a modification to those operators specifically, but perhaps I am missing something.

We did think about this quite a bit and nothing really made sense until rfactor. The complexity of using rfactor is at least partially due to choices to be made in how the parallelization is done. Our preferred approach for automating such choices is the auto scheduler. Extending the auto scheduler to use rfactor is planned, though likely will happen after it is initially merged.

There is also the RecFilter approach, which layers a more domain specific DSL on top of Halide. This generally gives better ease of use, though it is only applicable to certain areas of use and if it were employed a lot, it would make using Halide a confusing mix of many different mechanisms across a bunch of domains. It is somewhat instructive in that for one's own pipelines, one can often package up complex scheduling into helper routines.

**Comment by kgnk** [comment]
I guess you're right. I was making a lot of assumptions about what might be a desirable breakdown.

**Comment by MDBrothers** [comment]
I myself am trying to accelerate a rolling minimum reduction. Would there be any chance that you would share the schedule you came up with?
