### ISSUE TITLE
a.min.type() != b.min.type()

### ISSUE THREAD

**Issue by kgnk** [halide/Halide#2178]
In Bounds.cpp, `Bounds::visit_compare()` will use whatever random unbounded interval comes from `a_expr`. It should return `bounds_of_type(Bool())` if `a_expr` or `b_expr` are unbounded.

**Comment by kgnk** [comment]
Oh, BTW, `Bounds::compute_function_value_bounds()` has a loop `for (size_t k = 0; k < f.args().size(); k++)` that should use `f_args.size()`.

Also BTW, for iterating containers where I need the index, I always use the form `for (size_t i =0, last = container.size(); i != last; ++i)` because I remember something about the language says the function call to `size()` can't be removed, only inlined. Meanwhile the size doesn't change for the scope of the loop. Is that language rule bent for `-O3`?

**Comment by zvookin** [comment]
The language definition text basically says the compiler cannot change the
semantics of the loop. (If the compiler can prove the size doesn't change,
it can not reread the size field, but it is really hard to prove that in
multithreaded code. Keeping the size in an explicit local does indeed
change the semantics with respect to that. It is almost always correct in
Halide since we typically don't walk containers and mutate them in one
loop, but it is also a really small efficiency win and the code is kind of
ugly. I'd rather just use "foo.size()" directly.)

-Z-

**Comment by kgnk** [comment]
It's a kind of iterator style. It allows for automatic loop unrolling and vectorization, which, I'll admit, is of little use while looping over function arguments.
