### ISSUE TITLE
Ignoring output edges

### ISSUE THREAD

**Issue by tremmelg** [halide/Halide#2202]
I would like to express a stencil where the edges of the output image are not written to so as to avoid doing boundary handling for the inputs. Is this possible and if so, how would I do it?

**Comment by SanderVocke** [comment]
If I understand what you mean, you can have a look at the tutorial: [Realizing over shifted domains](http://halide-lang.org/tutorials/tutorial_lesson_06_realizing_over_shifted_domains.html).

For example, if your input is 200x200, but you want the output to produce only from (1,1) to (198,198):

```
//198x198 is the size of the area being produced (NOT the absolute coordinates)
Buffer<int> output(198, 198);
//At this point, "output" represents the pixel space (0,0) to (197,197)

//Now, shift the starting point:
output.set_min(1, 1);
//At this point, "output" represents the pixel space (1,1) to (198,198)

function.realize(output);
```

**Comment by tremmelg** [comment]
I think that's not quite what I was looking for. I'd still like the output to be 200x200 but just produce pixels from (1,1) to (199,199).

**Comment by SanderVocke** [comment]
Then it sounds more like a file I/O problem than an algo expression problem: you are only producing 198x198 pixels, but you want to write a padded image to disk. 

Maybe there is a trick with Halide Buffers that allows you to produce into only a subset of them, or that would allow you to get some kind of handle to a subset of a Buffer. If so, maybe someone else can shed some light on it.

You could instead use a boundary condition on the input (see [boundary conditions](http://halide-lang.org/docs/_boundary_conditions_8h.html)).

**Comment by zvookin** [comment]
It is a little hard to tell exactly which problem you are running into here. It could be something really simple, such as difficulty with the API to set the mins of a buffer or setting up the output extent incorrectly. I doubt this is the case as there are other problems that one would run into with interestingly scheduled filters, but in case it is, both halide_buffer_t and Halide::Runtime::Buffer allow adjusting the pointer and changing the mins and extents to do this. (E.g. see the Halide::Runtime::Buffer::crop method.) This works less well on GPUs, though you can do it if you access the device handle directly and the GPU API in question gives you a way to efficiently subset one of its memory allocations.

For vectorized filters, there is an issue that arbitrary bounds and extents imply some mechanism to deal with the edges. This may or may not be a problem depending on how things are scheduled. We provide a lot of tools for controlling this, but figuring out exactly how to set things up depends a bit on what you want. If the schedule has asserted starting coordinate alignment (e.g. input.dim(0).min % 8 == 0) then passing in non-aligned mins may result in an assertion failure.

Finally, sometimes what one wants is to specify that the edge pixels in the output can be overwritten with indeterminate data, which makes the output vectorization line up nicely but allows inserting arbitrary input data in the immediately preceding stage instead of computing the entire apron all the way back to the start. I believe Halide's separate tracking of allocated and computed bounds will do this automatically for internally allocated buffers, at least in some cases, but we do not give a way to specify a separate allocation bounds for inputs and outputs. The idea of doing so has been discussed recently, but it isn't really planned.

**Comment by tremmelg** [comment]
Thanks for the replies! The ` Halide::Runtime::Buffer::crop ` method does exactly what I was looking for.
