### ISSUE TITLE
linking problem

### ISSUE THREAD

**Issue by olegarch** [halide/Halide#2271]
I am using  halide_opencl_set_device_type("gpu") but it gives me error at link time:

undefined reference to `halide_opencl_set_device_type'

I can use env var but would prefer to do it from code.

**Comment by zvookin** [comment]
Are you linking against with a filter compiled with opencl in the target or a runtime built with that feature enabled?

**Comment by steven-johnson** [comment]
Halide has two interesting libraries to link against:

- The Compiler, aka `libHalide`, which is used to compile Halide-language code (e.g. in the form of a Generator or otherwise).
- The Runtime (no special name), which is normally included in compiled code by default. (If you add the "no_runtime" feature to HL_TARGET then you'll have to take pains to generate and link it yourself.)

The issue here is that `halide_opencl_set_device_type` is part of the *runtime* -- it doesn't exist in the compiler. You're only linking against the compiler (`libHalide`), so this is behavior as expected.

(This is a common mistake for people to make; I've opened https://github.com/halide/Halide/issues/2272 for discussion.)

**Comment by olegarch** [comment]
Thanks for explanation.

Does it mean that in order to enforce device type "gpu" for OpenCL I always need to have env variable set.
Can I enforce it from the code?

**Comment by zvookin** [comment]
Are you compiling ahead of time or JIT? I can see this being unavailable
for JIT. If you link with an ahead of time filter that was compiled with
opencl in the target, this function should be available, but that may not
help for JIT.

We should make sure all environment variable behavior is available via an
API for use in JIT situations.

Part of the reason this isn't totally robust is apps often replace the
function to get the GPU context to have total control.

-Z-

**Comment by olegarch** [comment]
I am experimenting with JIT right now. thanks for help.
