### ISSUE TITLE
Where to find hexagon_tools 8.0 version?

### ISSUE THREAD

**Issue by shipingli** [halide/Halide#2416]
I downloaded Hexagon SDK 3.2, 3.1, and 3.0, but still did not see   HEXAGON_Tools version 8.0, I only see 7.2.12.
Where should I get the 8,0?
I am using Linux.
Thanks

**Comment by ronlieb** [comment]
You should be able to get the 8.0 Hexagon tools from CreatePoint

https://createpoint.qti.qualcomm.com/tools/#suite/129/10941

 

If you wish, contact me at my qualcomm address, ronl @ qualcomm.com

Just to let me know if your development model is using upstream vs a Qualcomm produced Halide.

I might be able to help with a few other issues you will run into.

 

Thanks,

Ron

---

Qualcomm Innovation Center, Inc. is a member of Code Aurora Forum, hosted by The Linux Foundation

**Comment by shipingli** [comment]
Found it, it moved to a different location from 3.1.

ronlieb, I will contact you.

Thanks

**Comment by andrewjong** [comment]
They have moved it. Any idea where to find it now?
@ronlieb

**Comment by ronlieb** [comment]
[AMD Official Use Only - Internal Distribution Only]

Ask Pranav Bhandarkar or Dan Palermo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by andrewjong** [comment]
Ah, what are their emails?

**Comment by dsharletg** [comment]
@dpalermo @pranavb-ca

**Comment by dpalermo** [comment]
https://developer.qualcomm.com/
https://developer.qualcomm.com/software/hexagon-dsp-sdk
https://developer.qualcomm.com/software/hexagon-dsp-sdk/tools

You should download Hexagon SDK 3.5.1
which contains tools/HEXAGON_Tools/8.3.07

**Comment by andrewjong** [comment]
@dpalermo thanks! I previously downloaded Hexagon SDK 3.0 and that installed HEXAGON_Tools 7.1.12. It appears that got stuck in my system, because when I try to install through 3.5.1, it does not install the updated HEXAGON_Tools 8. Do you know how I can fully clear my system of 7.1.12 please? I already did rm -rf the original 7.1.12 folder.

**Comment by dpalermo** [comment]
Interesting, I have never seen that behavior.

You said you completely removed the 7.1.12 folder.  Are you installing SDK 3.5.1 into the same directory as 3.0?  I would instead suggest completely removing the SDK 3.0 directory.  

Typically, I install the SDK into a new directory (e.g. /local/scratch/dpalermo/SDK/Hexagon_SDK/3.5.1) so I can keep a few versions around (e.g. the latest release or two and the one currently under development)....and just remove the older ones when I know I am done with them.  This might also avoid any issues with the installer thinking some components have already been installed before.  If you aren't already installing into a new directory name, give that a try.

Otherwise, if you are still running into problems, make sure you aren't just running out of space on the partition where you are installing...although the installer is supposed to check that before installing.

**Comment by andrewjong** [comment]
Hum this is strange... The 3.5.1 installer is not installing HEXAGON_Tools for me. I do completely remove the SDK directory, I have plenty of partition space, and I tried installing to another location. Sigh... not sure what to do.

This is perhaps related. Something to do with Make files pointing to the old location, even though the old location has been removed? However there was no resolution to the thread.
https://developer.qualcomm.com/forum/qdn-forums/software/hexagon-dsp-sdk/toolsinstallation/33874
