### ISSUE TITLE
error when compile tutorial 10

### ISSUE THREAD

**Issue by alynn340** [halide/Halide#2638]
Dear all,

I download the halide-arm32-linux-32-trunk release package, and android ndk r16b.
When I try to compile tutorial 10 with prebuit libHalide.so, compiler return the error msg below.
But my Android.mk already have 
LOCAL_CFLAGS   := -fPIC -mfpu=vfp -DNDK -mfloat-abi=softfp -mhard-float -D_NDK_MATH_NO_SOFTFP=1

Error msg:
D:/Tool/Android/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../.
./arm-linux-androideabi/bin\ld: error: D:/Tool/Android/android-ndk-r16b/projects/halide_example2/obj/local/armeabi-v7a/objs/halide_generate/lesson_10_
aot_compilation_generate.o uses VFP register arguments, output does not
D:/Tool/Android/android-ndk-r16b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../.
./arm-linux-androideabi/bin\ld: error: D:/Tool/Android/android-ndk-r16b/projects/halide_example2/obj/local/armeabi-v7a/libHalide.so uses VFP register
arguments, output does not

Any one can help me?
thanks!

**Comment by zvookin** [comment]
What does "-mfloat-abi=softfp -mhard-float" mean? I think the issue is you are compiling with hard-float ABI and Halide forces Android targets to use soft-float. We can certainly give control over this in the `Target` somehow, but first we should make sure this is actually how you want to be compiling. If you want to change Halide, and are building from source, look at `CodeGen_ARM::use_soft_float_abi`. You can try just having it return false and see if that gets your code compiling.

**Comment by abadams** [comment]
I think it means that the ABI passes floats on the stack and ignores fp registers, but that real floating point hardware *is* available. That aside, this looks like this is an issue with running the *compiler* on arm android, not an issue with generated code.

libHalide.so is the compiler. Unless you want to be doing compilation on device, I suggest using one of the x86 releases of the compiler and cross-compiling code to arm android. If you want to compile LLVM+Halide for device so that you can JIT there, that's more complicated, but is possible. You'll likely have to compile things yourself though to get the correct float ABI settings.

**Comment by alynn340** [comment]
If I change the setting to " -msoft-float -mfloat-abi=softfp" , 
" lesson_10_aot_compilation_generate.o uses VFP register arguments, output does not" error disappear.
But still show error "libHalide.so uses VFP register arguments, output does not".

Should I compile libHalide again with setting soft_float_abi?

**Comment by alynn340** [comment]
thanks your reply, I would use linux g++ to compile the code
