### ISSUE TITLE
python binding can't be built

### ISSUE THREAD

**Issue by kanryu** [halide/Halide#2643]
Halide/python_bindings can not be built with VisualStudio 2017, please fix.

**Comment by steven-johnson** [comment]
The old CMake build files for the python_bindings were broken, and a fair amount of work was needed to get the python bindings robust again, which is why we temporarily removed the CMake build for it entirely.

At the moment, the core effort focused on getting the python bindings fully healthy and supported is working on the core code. 

If someone would like to resurrect the CMake build file for the Python Bindings and make it work really well, that would be super-awesome and we'd welcome a PR (right now I have my hands full with other tasks and it's almost certainly going to be several weeks before I can even think about CMake support).

Be aware, though, that such a PR really needs to include:
-- verification that it's been tested on (at least) Linux-x86, OSX, and Windows-MSVC systems, and runs all the same targets and tests as the Makefile
-- specific instructions on how Windows systems need to be configured with respect to which version(s) and installation(s) of Python are supported, as well as the versions and install instructions for Boost.Python (which is required by the bindings).

**Comment by kanryu** [comment]
Specifically, the Visual Studio Solution is generated from CMake. But I can't build it.

problems:
1. Normally, the VisualStudio compiler (cl.exe) can not use the 'not' operator. Explicitly include 'iso646.h' or '/ Za' option required.
2. A compile error occurs with content of 'struct timeval' being wrong

Please correct the source code so that it can be built with VisualStudio.

**Comment by steven-johnson** [comment]
The CMakeLists.txt file in python_bindings/ was deleted a week or so ago.

**Comment by alexreinking** [comment]
Preliminary support is being added back in #4644

**Comment by alexreinking** [comment]
Python bindings are now built on Windows via CMake.

**Comment by kanryu** [comment]
Thanks! :)
