### ISSUE TITLE
About bitmap byte orders in Halide language

### ISSUE THREAD

**Issue by kanryu** [halide/Halide#2681]
When loading an image using load_and_convert_image (), I noticed that it is not an ordinary arrangement of binary of bitmap of pixels, about RGBA, RGBA, RGBA ...

Actually it is arranged about Buffer<uint8_t> as follows:

  BBBBBBBB...
  BBBBBBBB...
  ...
  GGGGGGGG...
  GGGGGGGG...
  ...
  RRRRRRRR...
  RRRRRRRR...
  ...
  AAAAAAAA...
  AAAAAAAA...
  ...

This arrangement is too different from general image processing, so unnecessary processing is required for encoding and decoding.

Please let me know how to handle general bitmaps in the order of RGBA, RGBA ....
(Of course it can be ARGB, ARGB ... or BGRA, BGRA .. but it does not matter the order of colors)

**Comment by zvookin** [comment]
This is not a byte order issue. Byte order can play into the ordering of components in a 32-bit value, though it is conflated with other things in a way that it is somewhat independent of the CPU (or GPU) architecture's byte-order. (In general Halide pretty much only supports little-endian byte order since we haven't run into a case where someone needs big-endian support.)

Terminology wise, there are planar, semi-planar, and interleaved layouts.

Planar:

rrrr
rrrr
....

gggg
gggg
....

bbbb
bbbb
.......

Semi-planar:

rrrr
gggg
bbbb
rrrr
gggg
bbbb

....

Interleaved

rgbrgbrgbrgb...

Halide typically doesn't distinguish which component is which however and it is difficult tot ell whether this issue is about the component ordering vs. the overall layout.

Note that pretty much every possible representation is used somewhere in image processing and words like "ordinary arrangement" simply indicate a lack of broad experience. There really is very little total agreement across platforms and environments on exactly how to layout pixels. Halide is designed to handle the full generality of layouts as well as an arbitrary number of components in data.

`load_and_convert_image` is present to support testing and example app development. It is not intended to be a general image I/O function for use in real applications. As such it only supports a limited number of file formats and data layouts. It happens to use planar layout. To work in other orders, one would generally use a different image I/O library. The Halide language itself can process data in most data formats via a combination of scheduling and bounds constraints.

**Comment by kanryu** [comment]
Note that pretty much every possible representation is used somewhere in image processing and words like "ordinary arrangement" simply indicate a lack of broad experience.

You wrote like this, but it has already been confirmed that executing the library by defining functions and generators ordered by buffer (c, x, y) will cause alignment errors.

In other words, the current Halide language only supports spaces (or matrices) in which each pixel is sorted separately. If you say that you support other arrangements as you say please indicate the source code.

**Comment by abadams** [comment]
There are two tutorials dedicated to this topic:
http://halide-lang.org/tutorials/tutorial_lesson_16_rgb_generate.html

**Comment by zvookin** [comment]
There doesn't seem to be any productive work to be done here. Closing the issue.

**Comment by kanryu** [comment]
@zvookin Sorry, I want to ask more questions, so reopen this topic.

@abadams Thanks for showing me the sample!

I rewrite my function, and run. but it crashed.

https://gist.github.com/kanryu/060641d811061bf852161d2d23c236c4

The side that calls this function (C ++) writes such code.

    QString filename(QString::fromLocal8Bit(argv[1]));
    QImage img = QImage(filename);
    QImage img2(img.size(),img.format());
    std::vector<int> sizes(3);
    sizes[0] = img.depth()/8;
    sizes[1] = img.width();
    sizes[2] = img.height();
    Buffer<uint8_t> buff1(img.bits(), sizes);
    Buffer<uint8_t> buff2(img2.bits(), sizes);

    int result = luminor_rgba(buff1, -100.0f, 1.0f, 1.0f, buff2);

    img2.save("test.png");

Each image must be RGBA pixel format bitmap.
And that result is:

    Error: Input buffer input is accessed at -12, which is before the min (0) in dimension 0

**Comment by abadams** [comment]
The Halide code indexes things as x, y, c, but the C++ indexes things as c, x, y. I think you want to use Buffer<uint8_t>::make_interleaved instead of the default constructor

**Comment by kanryu** [comment]
@abadams Thanks! I made it :)

I checked the source code of Halide and it seems that such an operation is done internally. (of course you know)
It is like this to change the number of dimensions. I understand.

    /** Wrap an existing interleaved image. */
    static Buffer<T, D> make_interleaved(T *data, int width, int height, int channels) {
        Buffer<T, D> im(data, channels, width, height);
        im.transpose(0, 1);
        im.transpose(1, 2);
        return im;
    }

**Comment by kanryu** [comment]
Now I rewrite the library using Buffer :: make_interlieave (). It works very well.

However, there is no suitable API to test the generated function with halide_image_io.h, and the test program can not be described.

Will not you add an image loader assuming make_interleaved()?

**Comment by zvookin** [comment]
Can't you just construct a `QImage` on the result data and call `QImage::save`?

**Comment by kanryu** [comment]
Yes. My ultimate goal is to adopt it for Qt applications.(It has already been achieved)

However, since the library is separately published separately, it is desirable to work with pure C ++ whenever possible. There is a convenient program called halide_image_io.h so I want to solve it with this.

**Comment by zvookin** [comment]
If you want to submit a patch to `halide_image_io.h` and it is well written and of reasonable complexity, we'll consider it, but I doubt anyone else is going to work on this. `halide_image_io.h` is intended to be a simple support library for testing and proof of concept apps, not an full image I/O library.

You can also reformat the data as part of the writing process, which for a test is likely quite reasonable.
