### ISSUE TITLE
pmullw

### ISSUE THREAD

**Issue by matthiaskramm** [halide/Halide#2841]
It's my understanding that several of the MMX packed integer instructions can operate on 8-byte aligned memory addresses. I'm looking at the code

```
Var x;
ImageParam i1(Int(16), 1);
ImageParam i2(Int(16), 1);
i1.set_host_alignment(16);
i2.set_host_alignment(16);
Func f("f");
f(x) = i1(x) * i2(x);
f.align_bounds(x, 16);
f.vectorize(x, 16);
```

which generates the x86_64 assembly

```
movdqu (%r15),%xmm1
movdqu (%r11),%xmm3
pmullw %xmm1,%xmm3
movdqu %xmm3,(%rax)
```

However, I would have expected

```
movdqu (%r15),%xmm1
pmullw (%r11),%xmm1
movdqu %xmm1,(%rax)
```

Is this an alignment issue, or something to do with code generation or LLVM?

I verified that the generated C code contains assertions of the form

```
  if (( _i1__0_buffer->host & 15) != 0)   {  
    return halide_error_unaligned_host_ptr(_ucon, "i1$0", 16);
  }  
```

**Comment by abadams** [comment]
You haven't told Halide quite enough information, because Images can start at coordinates other than zero. So the min coordinate (which might be -3, for example) is known to be aligned, and the iteration runs from 0 to some multiple of 16.

If we instead tell Halide that the min coordinate is aligned, and the iteration domain (which is tied to the output shape) starts at that min coordinate, then everything works out:
```
    Var x;
    ImageParam i1(Int(16), 1);
    ImageParam i2(Int(16), 1);
    i1.set_host_alignment(16);
    i2.set_host_alignment(16);
    Func f("f");
    f(x) = i1(x) * i2(x);
    f.vectorize(x, 16);
    f.output_buffer().dim(0).set_min(i1.dim(0).min());
```

produces:
```
	movdqu	-16(%rbx), %xmm0
	movdqu	(%rbx), %xmm1
	pmullw	(%rdx), %xmm1
	pmullw	-16(%rdx), %xmm0
	movdqu	%xmm0, -16(%rcx)
	movdqu	%xmm1, (%rcx)
	addq	$32, %rcx
	addq	$32, %rbx
	addq	$32, %rdx
	decq	%rsi
	jne	LBB0_2
```

**Comment by matthiaskramm** [comment]
Thanks, that makes it work for me! It wouldn't have occurred to me to fiddle with the output shape to change the opcodes of the computation.
