### ISSUE TITLE
Trying to create OpenCL kernel for a generator

### ISSUE THREAD

**Issue by romix** [halide/Halide#2866]
I'm new to Halide. Sorry if my question is obvious or was answered before. I tried to quickly find something about it, but couldn't.

So, I'm trying to use the `conv_layer_generator.cpp` as an example (could be any other generator as well) and to generate and run the OpenCL kernel using it. But I do not quite understand how to achieve this. I guess I have to provide a proper target or something like that. But where and how do I do it? In `process.cpp` or may be when I generate the conv_layer by means of the generator?

I'd like to be able:
- to run the generated code on a GPU
- and to see the OpenCL kernel source code being produced. In ideal case, it would be nice if this OpenCL kernel could be written into a file. But it would be OK if it is produced e.g. by means of certain debug options.  Is it even possible?

**Comment by abadams** [comment]
Halide doesn't produce standalone OpenCL kernels - there's also a bunch of
compute that needs to happen on the CPU like marshaling arguments and
checking sizes of things. So Halide compiles CPU-callable functions that
internally launch an OpenCL kernel.

One way to see this kernel is to set the environment variable
HL_DEBUG_CODEGEN=1. It'll print it out during compilation.

For Halide to use the GPU at all the schedule needs to say so, using
something like Func::gpu_tile. Conv layer doesn't have a GPU schedule
(well, it does, but it's commented out because of a weird issue we were
unable to figure out). Try something like local_laplacian instead. That
Makefile uses the environment variable HL_TARGET to set the target, which
is what we conventionally do. For OpenCL you can use something like
HL_TARGET=host-opencl. This gets passed through to the target= flag to the
generator binary.

**Comment by romix** [comment]
Thanks! I was able to produce the OpenCL kernels and using the `HL_DEBUG_CODEGEN=1` I was able to print them.

**Comment by yvn96** [comment]
Hi @romix , how were you able to generate Opencl kernels in C, I guess HL_DEBUG_CODEGEN=1 only gives the pseudo code behind the kernels
