### ISSUE TITLE
Using halide to implement a matrix multiplication for 2D row-major arrays allocated in C

### ISSUE THREAD

**Issue by romix** [halide/Halide#2868]
I'm trying to implement a matrix multiplication for 2D row-major arrays allocated in C, which are allocated by an external library.  The arrays are very big and changing them to column-major representation is not an option.

I'm running into certain issues.

As far as I understand, I need to create Halide::Runtime::Buffer objects from those arrays by using a constructor like:
```c++
Halide::Runtime::Buffer<float, 2> A(a, a_rows, a_cols);
```

But it seems like this is not quite correct, because Halide uses row-major internal representation, but indexes it like (col, row)? Is it correct? Or does it the column-major representation?

Also the simple definition of a naive matmul in Halide seems to work incorrectly, because of these indexing issues.

Having the indexing working different than in C makes it very easy to introduce bugs when you write your code. It is too easy to swap the index order by mistake.

Questions:
- Is there any way to make indexing work like in C (same order of indices, i.e. row, col) by calling some methods on the Buffer objects?
- How would such a simple thing like matrix multiplication look like in Halide if it needs to work correctly on these externally C-allocated row-major 2D arrays?

**Comment by abadams** [comment]
You are correct. By default Halide uses a row-major internal representation, but indexes it as col, row. So you have two options:

1) Write your matrix multiply as:

C(j, i) += A(k, i) * B(j, k);

You rightly point out that this is error-prone.

2) Tell Halide to store things so that the first coordinate is the innermost one in memory. I hesitate to say column major, because really it's going to represent a row-major matrix, but with more conventional indexing.

To allocate the input/output buffers like this:
```
Halide::Runtime::Buffer<float> A(my_data, rows, cols);
A.transpose(0, 1);
```
The transpose call doesn't move any data around, it just changes the order of the dimension metadata so that the indexing is flipped to row, col.

In the Halide source you need to tell Halide to generate code where the second dimension can be assumed to have stride 1, and the first dimension has unknown stride:
```
for (auto buf : {A, B, C.output_buffer()}) {
 buf.dim(0).set_stride(Expr());
 buf.dim(1).set_stride(1);
}
```
Then you can write things as:
```
C(i, j) += A(i, k) * B(k, j);
```

**Comment by romix** [comment]
Thanks for the reply!

> In the Halide source you need to tell Halide to generate code where the second dimension can be assumed to have stride 1, and the first dimension has unknown stride:

> for (auto buf : {A, B, C.output_buffer()}) {
 buf.dim(0).set_stride(Expr());
 buf.dim(1).set_stride(1);
}
>Then you can write things as:

>C(i, j) += A(i, k) * B(k, j);

Is it possible to avoid changing anything in the Halide code so that any existing Halide codes/kernels can be re-used? May be it is possible to set something outside of the Halide code to achieve the same effect?

**Comment by abadams** [comment]
The assumption that the stride of the first argument is 1 is baked into the
compiled code by default, so if that's not going to be true at runtime then
you need to change the Halide source to let it know. However, it is
possible to write Halide code that adapts to various layouts intelligently
(see http://halide-lang.org/tutorials/tutorial_lesson_16_rgb_generate.html)

**Comment by abadams** [comment]
That indexing is common practice for matrices in C, but the reverse of common practice for shading languages (e.g. opengl). This is a case where linear-algebra and imaging have conflicting conventions.

You can write such a helper function pretty easily, and people do. The implementation would be something like:

void C_style(OutputImageParam p) {
  p.dim(0).set_stride(p.dim(1).extent());
  p.dim(1).set_stride(1);
}

**Comment by ronghongbo** [comment]
Good point. Thanks!

**Comment by ronghongbo** [comment]
Hello Adams,

For lesson_01, after 
```    gradient(x, y) = e;```
I added 
```    gradient.output_buffer().set_stride(0, Halide::Expr() ).set_stride(1, 1);```

It executes and says success. Now how to see if the above set_stride(1, 1) has indeed some effect on code generation? 

With HL_DEBUG_CODEGEN=4, I see the generated code is the same as  the original, and there is still gradient.stride.1 used (instead of being replaced with 1). For example: 
```
Generating llvm bitcode for function __gradient...
Codegen: for<None> (gradient.s0.y, gradient.min.1, gradient.extent.1) {
  for<None> (gradient.s0.x, gradient.min.0, gradient.extent.0) {
    store gradient[(((gradient.s0.x*gradient.stride.0) + (gradient.s0.y*gradient.stride.1)) - ((gradient.min.0*gradient.stride.0) + (gradient.min.1*gradient.stride.1)))] = (gradient.s0.x + gradient.s0.y)
  } // for gradient.s0.x end
} // for gradient.s0.y end
.....
%buf_stride4 = getelementptr inbounds %struct.buffer_t, %struct.buffer_t* %gradient.buffer, i32 0, i32 3, i32 1
  %gradient.stride.1 = load i32, i32* %buf_stride4
``` 
Thanks!
Hongbo

**Comment by abadams** [comment]
That's not legal Halide syntax. Are you using an old version? If I write:

`    gradient.output_buffer().dim(0).set_stride(Halide::Expr() ).dim(1).set_stride(1);`

I see this IR:

```
  produce gradient {
    let t1 = ((gradient.min.0*gradient.stride.0) + gradient.min.1)
    for (gradient.s0.y, gradient.min.1, gradient.extent.1) {
      let t2 = (gradient.s0.y - t1)
      for (gradient.s0.x, gradient.min.0, gradient.extent.0) {
        gradient[((gradient.s0.x*gradient.stride.0) + t2)] = (gradient.s0.x + gradient.s0.y)
      }
    }
  }
```

I think you might be seeing an old bug.

**Comment by ronghongbo** [comment]
Thanks for the reply, Andrew! Indeed I am using an old version of Halide. I will upgrade and try.

Hongbo
