### ISSUE TITLE
Why is this not supported f(x) = f(x-1) + f(x-2) where x is Var? 

### ISSUE THREAD

**Issue by nitish2112** [halide/Halide#3035]
Hi,

Halide tutorial says that: "Each Var used in an update definition must appear unadorned in the same position as in the pure definition in all references to the function on the left and right-hand sides." I am having a hard time understanding why the following is valid:

```
Func f;
f(x,y) = x+y;
f(y+1, y) = f(0, y) * 17;
```
but this is not valid
```
Func f;
f(x,y) = x+y;
f(x,y+1) = f(0,y) * 17
```

Looking into the fibonacci example it seems like the following is valid:

```
    Func fib,;
    Var x;
    RDom r(2, 18);
    fib(x) = 1;
    fib(r) = fib(r-2) + fib(r-1);
```
but this is not:
```
    Func fib, g;
    Var x;
    fib(x) = 1;
    fib(x) = fib(x-2) + fib(x-1);
```
Can someone explain why Halide imposes this constraint?

Thanks!

**Comment by abadams** [comment]
A Halide Func definition has to mean the same thing no matter in what order the different values of the Var are considered. The version of fib that uses 'x' wouldn't work if x was traversed in decreasing order, or if multiple values of 'x' are computed in parallel. RVars have an implicit ordering to them, so they don't have this constraint, but you can't schedule them as flexibly.

The rule we came up with that you quoted is sufficient to avoid getting yourself into situations that cause race conditions or out-of-order execution of dependent things.

```f(y+1, y) = f(0, y) * 17```

is legal because for each value of y, the statement only mutates row 'y' of f. There's no cross-talk across the rows. This means it's safe to traverse the loop over y in parallel or in any order without changing the meaning of the algorithm.

**Comment by nitish2112** [comment]
Thanks! that helps
