### ISSUE TITLE
vectorized loads can overread buffers

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3036]
TL;DR: vectorized loads can overread an input buffer; not sure of the details yet, capturing an example for starters:

Given a simple pipeline like:

```
    const int vec_size = 4;
    const int width = vec_size * 2 - 1;

    Var x, xi;

    Buffer<float> input_buf(width);
    input_buf.fill(0.f);

    ImageParam input(Float(32), 1, "input");
    input.set(input_buf);

    Func tmp("tmp");
    tmp(x) = input(x);

    Func output("output");
    output(x) = tmp(x);

    tmp.compute_at(output, xi);
    output.compute_root()
        .split(x, x, xi, vec_size, TailStrategy::GuardWithIf)
        .vectorize(xi);

    // Set explicit extents just to make .stmt more readable
    // (not necessary for repro)
    input.dim(0).set_min(0).set_extent(width).set_stride(1);
    output.output_buffer().dim(0).set_min(0).set_extent(width).set_stride(1);

    auto b = output.realize(width);
```

This generates .stmt like:

```
  produce output {
    allocate tmp[float32 * 4]
    produce tmp {
      tmp[ramp(0, 1, 4)] = input[ramp(0, 1, 4)]
    }
    output[ramp(0, 1, 4)] = tmp[ramp(0, 1, 4)]
    free tmp
    allocate tmp[float32 * 4]
    produce tmp {
      tmp[ramp(0, 1, 4)] = input[ramp(4, 1, 4)]
    }
    predicate ((x4(4) < ramp(7, -1, 4)))
      output[ramp(4, 1, 4)] = (tmp[ramp(0, 1, 4)] if (x4(4) < ramp(7, -1, 4)))
    free tmp
  }
```

Note that the input buffer is known at compiletime to be 1.75 vectors wide, but rather than the one-dense-and-one-masked-load you'd expect, we get two-dense-and-one-masked.

**Comment by steven-johnson** [comment]
Note that the split() and compute_at(xi) seem to be necessary for this to happen.

**Comment by steven-johnson** [comment]
You can 'fix' this issue by explicitly adding the vec_size and GuardWithIf to the vectorize(xi) line: `output.vectorize(xi, vec_size, TailStrategy::GuardWithIf)` (the vec_size is redundant, the point here is to get the GuardWithIf onto the vectorize() itself)

That said, shouldn't a vectorize() of a split() 'inherit' the proper TailStrategy?

**Comment by abadams** [comment]
'xi' is a different loop in the two cases, so the IR is quite different.

That aside, the GuardWithIf only covers the computation of the associated function, not necessarily things compute_at its loops (i.e. the 'if' goes on the inside). We could change that behavior, but I believe the bug here is that there wasn't a bounds assertion failure on the input buffer. The IR clearly shows it reading up to and including index 7, but add_image_checks just uses the region *required* of tmp as its bounds, even though the region *computed* of tmp is larger. Thus it will ensure the input is large enough for tmp to be *correct*, but not necessarily large enough to cover every load from it. So this bug is another case of reading out of bounds in a benign way (the values can't affect the output), which is why we haven't had it bite us before a sanitizer. Valgrind wouldn't complain about this one either.

It does need fixing though - the out of bounds read could cross a page boundary or something in a pathological case.

The thing is, I don't understand how it could possibly work to have image bounds assertions done before computation bounds inference when things are still in terms of the regions required rather than the regions actually computed. I guess I'll try moving it after?

**Comment by abadams** [comment]
#3037

**Comment by abadams** [comment]
The PR makes it a bounds error instead, which is better. Best would be if the compute_at snuck inside the if statement too, but that would be a separate improvement.
