### ISSUE TITLE
apps/local_laplacian and memory allocation error

### ISSUE THREAD

**Issue by silly-git** [halide/Halide#3112]
Hello, I'm learning your awesome library and I'm running into a memory allocation error with the local_laplacian example app:
```
[Grimey:builds/Halide/bin] joe% ./local_laplacian_process ~/Desktop/mads.png 40 1 1 10 output.png
Error: Total allocation for buffer f4 is 2168156800, which exceeds the maximum size of 2147483647
Abort
[Grimey:builds/Halide/bin] joe% file ~/Desktop/mads.png
/Users/joe/Desktop/mads.png: PNG image data, 7952 x 5304, 16-bit/color RGB, non-interlaced
[Grimey:builds/Halide/bin] joe%
```

When processing a 42MP (7952x5304) image and `levels` at 40 or above. Is this expected? If so, is there a way to use this with higher levels (or larger images)? I found that breaking the image into tiles, processing those and putting them back together showed lines where the tile edges were - I can overlap the tiles and blend which looks fine, but I'd like to know if I've got something backwards.

Thanks!

**Comment by abadams** [comment]
This algorithm has an all-to-all dependence in it, so it's hard to tile. With huge images and large level counts it's going to need a lot of memory. I would try to keep the level count small and mess with the other parameters to get the effect you want instead.

In general you can tile Halide algorithms by tiling the output space. You feed the pipeline the entire input image, but for the output you make a Buffer with a non-zero min and a small extent and realize into that. It will only compute the necessary data to produce the correct output for that tile. For local laplacian however, it's probably still going to allocate too much memory due to the all-to-all dependence.

**Comment by silly-git** [comment]
Thanks the quick response, I'll give that a go.
