### ISSUE TITLE
Halide and Ryzen

### ISSUE THREAD

**Issue by 9cvele3** [halide/Halide#3135]
I implemented 3x3 and 5x5 separable convolutions in Halide (by computing in tiles, similar to Halide examples) and I got very good results on i5 4590. 
3x3: 1.28 ms
5x5: 1.3 ms

However, when I tested it on AMD Ryzen Threadripper 1920x (12 physical cores, 24 logical cores), it was actually slower than my old i5. 
3x3: 3.79ms
5x5: 4.73ms

When I watched cores utilization in TaskManager, on i5 all cores were used 100%. On Threadripper, overall utilization was about 70%, some cores were over 90%, but some cores were on just 50%.

In both cases I used Windows 10 and MSVC and `Halide::get_host_target()`.

Should I do something special do get better performance on Ryzen? 

Is this maybe a LLVM problem, since [LLVM Ryzen support is relatively new](https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Zen-Scheduler-WIP)? If so, will building Halide from source with newest LLVM be of any help?

**Comment by zvookin** [comment]
A few things to check:

1) How many threads is Halide using? Unfortunately I don't see a way to print this out easily, but it should be visible in the TaskManager. You can control the number of threads with the HL_NUM_THREADS environment variable or a call to halide_set_num_threads. Two good values to try are the number of physical cores and the number of logical cores.

2) Print out the result from `Halide::get_host_target()` using the Target::to_string method. Is it using AVX2? If not, try turning it on explicitly. If so, try manually disabling AVX2 to see if SSE is faster. (Sometimes cores downclock when using AVX2 for power reasons.) This assumes you are scaling your vectorization using something like `natural_vector_size<T>()`. If not,try making sure the vectorization size matches the instruction set.

3) We currently don't offer a way to set LLVM flags to target specific architecture variants using LLVM's flags. (There are a ton of them and anything at this level of detail likely needs to surface the LLVM flags directly rather than adding a small number of Halide Target features.)

Higher level, I don't think anyone working on Halide is using AMD CPUs right now so it isn't an area we have much experience with. We're definitely interested in making it work well, but efforts may need to come from others to figure out what needs to be done.

**Comment by 9cvele3** [comment]
Neither 1. or 2. helped. 

However, I was able to test convolution on another AMD Ryzen processor (AMD Ryzen 7 2800x - 8 core processor), and here the results were good (0.97ms for 3x3 convolution, 1.2ms for 5x5).

So Halide has problems with only some Ryzen processors (Threadripper). This is probably related to specific architecture of Threadripper.
