### ISSUE TITLE
Redundant Reads while vectorization in Halide for GPU

### ISSUE THREAD

**Issue by ImageHandler** [halide/Halide#3139]
Hi, 
I am using halide for gpu, for implementing 3x3 averaging filter.
If I vectorize in  X dimention (horizontal) then mulitple redundant loads happen which increase the overall latency.
e.g : to get the output for (1,1), we would require the pixels at 
(0,0), (1,0), (2, 0)
(0,1), (1,1), (2, 1)
(0,2), (1,2), (2, 2)

and similarly for calculating output of (2,1), we would require
(1,0), (2,0), (3, 0)
(1,1), (2,1), (3, 1)
(1,2), (2,2), (3, 2)

If we vectorize in the x dim with a factor of 2 then points (0,0) and (1,0) will be loaded into a vector
and the second vector will be of (1,0) and (2,0) and so on, but (1,0) is already in the loaded vector. 
So what's the need of loading it again from the buffer when we can directly use it from the previous vector.

**Comment by abadams** [comment]
For some backends we do that transformation automatically (hvx), but for
most we don't because it's not necessarily a performance win and you can
get at it using the schedule anyway like so:

f(x, y) = g(x-1, y) + g(x, y) + g(x + 1, y);
f.vectorize(x, 4);

The code above does three separate independent vector loads to g, loading a
total of 12 elements.

f(x, y) = g(x-1, y) + g(x, y) + g(x + 1, y);
f.vectorize(x, 4);
g.in(f).compute_at(f, x).vectorize(x);

The code above does a single 6-element vector load of g into local memory,
and then f loads its vectors out of that.

In general you use Func::in to control staging of data.

- Andrew

**Comment by yvn96** [comment]
Thanks that's good information, now I actually want to work on alternate pixels rather than working on whole image. Like in the first row i.e y=0, I will calculate(the averaging filter) for every even x (y=0),  and for y=1, I will calculate for every odd x, and the same procedure follows for all y's (depending upon if the y is even or odd). Can halide be beneficial in this case? 
Note that, I am working on halide for GPU only, and we are well aware of the lack of jumping tendency of GPUs like we can't use if else or switch statements in GPU, it will have a bad impact on the performance.

Further a different topic, I wrote a code for halide, when I am scheduling it with CPU as target, then it is working fine but as soon as I make GPU as target (basically use gpu_tile() function) it doesn't give me the correct output. Can you quote the reasons for why it would have been happening.

**Comment by abadams** [comment]
You can use Halide for that sort of thing. If you have some averaging filter "blur" that you only want to compute at every other pixel you could do something like:

blur(x, y) = in(x-1, y) + in(x+1, y) + in(x, y-1) + in(x, y+1);
out(x, y) = blur(2*x + y%2, y);

If you leave blur with the default schedule (inline) it will only get computed at the points where it will be used.

The most common reason for incorrect output is if copies to and from GPU memory aren't happening. Try calling .copy_to_host() on the output buffer.

**Comment by yvn96** [comment]
Thanks for the help, 
1. I had already called .copy_to_host() for the final function. Consider I have multiple functions a,b,c,d
b and c consume a and,  d consumes a, b and c
running them on cpu is fine but as soon I try to compute them on GPU it doesn't give me a correct output. 
2. If I am not using .gpu_tile() on a function where is that function computed?
e.g : consider the algorithm something like this :  
a(x, y) = something
b(x, y) = a(x, y) + something
c(x,y) = a(x, y) + something
d(x, y) = a(x,y) + b(x,y) + c(x,y) + something
Schedule : 
a.compute_root()
.gpu_tile(x,y,xo,yo,xi,yi,128,8);

b.compute_root();

c.compute_root();

d.compute_root()
.gpu_tile(x,y,xo,yo,xi,yi,128,8);
It gives me a correct output but if I add b.gpu_tile() or c.gpu_tile(), it becomes wrong.

**Comment by yvn96** [comment]
Say we have a generator and 3 functions in it A, B, C
A has input a (a buffer), and output of A is the input of B and output of B is input of C
I want to compute A, B and C seperately in different kernels. Once I use gpu_tile in the schedule of the above function with compute_root() 3 different output buffers are generated from the functions. But ideally this work could be done using a single shared buffer (which could become the input of the function and at the same time output of that function also). Is there a way to do so?

**Comment by abadams** [comment]
Halide doesn't really have the analysis to prove that something is safe to run in-place, so it doesn't. For a particular pipeline you could replace the memory allocator with something custom and have it just always return the same buffer.

Or if you make A, B, and C all additional outputs to the pipeline, then you have full control over how their memory is allocated, because for outputs we expect the user to allocate them.

**Comment by yvn96** [comment]
Is there any specific option to debug in halide for gpu. print() and print_when() gives a build error.

Internal error at HalideSourceCode/Halide/src/CodeGen_OpenCL_Dev.cpp:212
Condition failed: !function_takes_user_context(op->name)
