### ISSUE TITLE
Expr operator&(Expr x, Expr y) produces unexpected result

### ISSUE THREAD

**Issue by rzwm** [halide/Halide#3164]
Run below code you will get an access out of boundary error:"Error: Input buffer input is accessed at 12, which is beyond the max (11) in dimension 1".
```
#include "Halide.h"
using namespace Halide;

int main()
{
	const int width = 16;
	const int height = 8;

	Buffer<uint8_t> input(width, height * 3 / 2);
	input.set_name("input");
	Buffer<uint8_t> output(width, height);
	output.set_name("output");

	Var x{ "x" }, y{ "y" }, i{ "i" };

	Func Y_height{ "Y_height" };
	Y_height(i) = input.height() * 2 / 3; // equal to height
	Y_height.compute_root(); // pre-compute

	Func x_coordinate{ "x_coordinate" };
	Func y_coordinate{ "y_coordinate" };

	x_coordinate(x, y) = x;

	// using this is correct!!!!!!!!!!!!!!!!!
	//y_coordinate(x, y) = height * 5 / 4 + select(((height / 2) & 1) == 0, y / 4, (y + 2) / 4);

	// using this causes access out of boundary!!!!!!!!!!!!!!!!!!!!!!
	y_coordinate(x, y) = Y_height(0) * 5 / 4 + select(((Y_height(0) / 2) & 1) == 0, y / 4, (y + 2) / 4);

	Func copy{ "copy" };
	copy(x, y) = input(x_coordinate(x, y), y_coordinate(x, y));

	copy.realize(width, height);

	return 0;
}
```
It is caused by
```
y_coordinate(x, y) = Y_height(0) * 5 / 4 + select(((Y_height(0) / 2) & 1) == 0, y / 4, (y + 2) / 4);
```
,but use this there will be no error:
```
y_coordinate(x, y) = height * 5 / 4 + select(((height / 2) & 1) == 0, y / 4, (y + 2) / 4);
```
. I have make `Y_height(0)`  strictly equal to `height`, the only different is a call of `Expr operator&(Expr x, Expr y) ` in `((Y_height(0) / 2) & 1) == 0`. So I think there has a bug!

**Comment by shoaibkamil** [comment]
Just quickly glancing at your code, it looks like the difference between the two implementations is that the version using `height` directly has a `select` condition that can be statically computed, while the version using `Y_height(0)` has a condition that can't be proven statically.  In other words, 
```
y_coordinate(x, y) = height * 5 / 4 + select(((height / 2) & 1) == 0, y / 4, (y + 2) / 4);
```
can be statically simplified into:
```
y_coordinate(x, y) = 8 * 5 / 4 + select(((8 / 2) & 1) == 0, y / 4, (y + 2) / 4);
```
which can then be simplified into
```
y_coordinate(x, y) = 10 + y/4;
```

In contrast, the version using `Y_height(0)` cannot be statically simplified, and so the generated code will compute both branches of the `select` statement before evaluating the condition `(Y_height(0) / 2) & 1) == 0`.  Since one branch computes out of bounds, you will get that error.

**Comment by abadams** [comment]
In general bounds inference is conservative - sometimes it will think it needs more than it actually does. What's happening in this case is that the constant results in condition in the select simplifying away to true, while the load from another Func does not.

**Comment by abadams** [comment]
Oops, +1 to what Shoaib said.

**Comment by rzwm** [comment]
Thanks. Now I know the reason. Bounds inference keeps the safe, but makes code not be so convenient as C++.
