### ISSUE TITLE
Generating vpadd on ARM NEON

### ISSUE THREAD

**Issue by mohamedadaly** [halide/Halide#3207]
Is there a way to schedule a `Func` to generate a "horizontal" (pairwise) addition on arm neon e.g. `vpadd`, `vpadal`, etc.? I looked into CodeGen_ARM and the unit tests, and couldn't find any for these instructions.

**Comment by mohamedadaly** [comment]
Any thoughts?

**Comment by abadams** [comment]
A lot of the time the sort of code that would generate this uses vld2
instead to deinterleave on load, rather than doing a horizontal op after
loading. So it would have to be doing a horizontal reduction of something
scheduled per-vector. Here's an example for vpaddl:

```
    ImageParam in(UInt(16), 1);
    Func f, g;
    Var x;

    f(x) = in(x) + 3;
    g(x) = cast<uint32_t>(f(2*x)) + f(2*x+1);

    g.vectorize(x, 4);
    f.compute_at(g, x).vectorize(x, 8);

    g.compile_to_assembly("/dev/stdout", {in},
Target("arm-linux-32-no_asserts-no_bounds_query-no_runtime"));

```

I'm having a harder time getting llvm to generate vpadal though. Really
this should do it:

```

    ImageParam in(UInt(16), 2);
    Func f, g;
    Var x, y;

    f(x, y) = in(x, y) + 3;

    RDom r(0, 100);
    g(x) += cast<uint32_t>(f(2*x, r)) + f(2*x+1, r);

    Var xo, xi;
    g.update().split(x, xo, xi, 4).reorder(xi, r, xo).vectorize(xi);
    f.compute_at(g, r).vectorize(x);

    g.compile_to_assembly("/dev/stdout", {in},
Target("arm-linux-32-no_asserts-no_bounds_query-no_runtime"));
```

But instead I get an unzip and two widening adds. We could add a pattern
for when you're adding three numbers, two of which are narrow and one of
which is wide (e.g. u32 + u16 + u16). You can interleave the u16s and then
use vpadal to do it in two ops, but you could also just use two vaddw ops,
so you really only want to do it if you think the two u16s can be
interleaved for free (for example because they are the even and odds
elements of some other vector already). Or maybe it's fine to just always
use a possible zip + vpadal in that case?

**Comment by mohamedadaly** [comment]
Thanks!

So if I want to do a vector reduction, for example to compute a dot product of two long vectors, a good way would be to use split the RDom range into chunks to compute partial sums, and then reduce the vector of partial sums using vpaddl? Or is there a better way to do that?

**Comment by dsharletg** [comment]
We now generate these kinds of instructions when vectorizing reduction variables.
