### ISSUE TITLE
Define shift by a negative value as a shift in the other direction

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3325]
Some architectures support "signed shifts", where `x << -N` is equivalent to `x >> N` and vice-versa. Currently in Halide, shifting by a negative value is undefined behavior. We could define it this way, and then emulate this on targets that do not support this in hardware. This could be made zero cost by only emulating this for signed shift RHS values. 

Currently, shifts require that the LHS and RHS have the same type, including signedness. A prerequisite to this strategy would be to allow the signedness of the operands of a shift to differ. Both signed shifts of unsigned values, as well as being able to shift signed values by unsigned shift amounts would become important.

**Comment by zvookin** [comment]
To clarify, the design would allow mixing the types of operands for shift operators and do a bounds proof on the shift amount. If if the proof comes back known non-negative or non-positive the shift operator can be determined statically at compile time, otherwise a conditional structure would be used. (Some research into the conditional structure that is best is likely warranted. My reading of the LLVM IR docs is one cannot presume LLVM will generate a machine shift instruction on machines which provide the semantics we desire. Though to be honest, I'm not sure I know of such a machine.)

The situation now has this being undefined behavior so I'm happy to define it this way. (I.e. one can basically never use a negative shift amount anyway so if it occurs in any program today, it's a bug.) The only place this might be a bit of an issue is code can be optimized now on the assumption that the negative values don't happen.

**Comment by zvookin** [comment]
One more thing: ```unsafe_promise_clamped``` would get one the current behavior fairly trivially.

**Comment by steven-johnson** [comment]
The current behavior doesn't satisfy anything: the logic for simplifying both shift-left and shift-right assumes that negative shift values are possible, and should be treated as mirroring the operation (e.g. a << -b == a >> b), but we don't seem to actually enforce this at codegen time.

I'd be fine with us ensuring that negative shifts are allowed everywhere, but until/unless that happens, we should probably stick to the lowest-common-denominator of assuming that a shift amount of `0 <= shift-amount < bits-in-type` is legal, and have the simplifier follow that rule. (And also probably add logic to fail at compile time if we can prove that the shift amount is outside that range.)
