### ISSUE TITLE
Metal vectorization issues

### ISSUE THREAD

**Issue by slomp** [halide/Halide#3372]
Metal CodeGen seems to be generating invalid/unsupported vector types.

In the example below, `int16` does not mean a 16bit integer, but a 16-lane 32bit integer.
This is not supported by Metal, whose largest integer vector type is `int4`.

```
2018-10-15 11:27:27.302983-0700 [97691:4490619] [DYMTLInitPlatform] platform initialization successful
...
2018-10-15 11:27:27.846868-0700 [97691:4490531] Metal GPU Frame Capture Enabled
2018-10-15 11:27:27.847310-0700 [97691:4490531] Metal API Validation Enabled
2018-10-15 11:27:27.946166-0700 [97691:4490531] Error Domain=MTLLibraryErrorDomain Code=3 "Compilation failed:

program_source:172:8: error: unknown type name 'int16'
      int16 _13 = int16(-10);
      ^
program_source:172:20: error: use of undeclared identifier 'int16'
      int16 _13 = int16(-10);
                  ^
program_source:176:35: error: unknown type name 'packed_int16'
      *(__address_space___shared packed_int16* )((__address_space___shared int *)__shared + _16) = _13;
                                 ^
program_source:185:8: error: unknown type name 'int16'
      int16 _18 = int16(-10);
      ^
program_source:185:20: error: use of undeclared identifier 'int16'
      int16 _18 = int16(-10);
                  ^
program_source:189:35: error: unknown type name 'packed_int16'
      *(__address_space___shared packed_int16* )((__address_space___shared int *)__shared + _21) = _18;
                                 ^
program_source:198:8: error: unknown type name 'int16'
      int16 _23 = int16(-10);
      ^
program_source:198:20: erro
Error: Metal: new_library_with_source failed.
Program ended with exit code: 9
```

**Comment by slomp** [comment]
Here's where the problem might be:
https://github.com/halide/Halide/blob/master/src/CodeGen_Metal_Dev.cpp#L63-L71

In D3D12, I simply ignore them, which is also not good...
https://github.com/halide/Halide/blob/master/src/CodeGen_D3D12Compute_Dev.cpp#L81-L98

We might have to "emulate" wider types and warn the user, or disallow them completely and report an error.

**Comment by zvookin** [comment]
The code is likely inherited from OpenCL. Ignoring user requested
vectorization doesn't seem like a good idea, but Halide doesn't really have
a definitive position on what to do when a vectorize directive cannot be
satisfied by a native vector width.

-Z-

On Oct 15, 2018 3:11 PM, "Marcos Slomp" <notifications@github.com> wrote:

Here's where the problem might be:
https://github.com/halide/Halide/blob/master/src/CodeGen_Metal_Dev.cpp#L63-L71

In D3D12, I simply ignore them, which is also not good...
https://github.com/halide/Halide/blob/master/src/CodeGen_D3D12Compute_Dev.cpp#L81-L98

We might have to "emulate" wider types and warn the user, or disallow them
completely and report an error.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/halide/Halide/issues/3372#issuecomment-429977827>, or mute
the thread

**Comment by shoaibkamil** [comment]
In this case, I'd advocate for at least issuing an error at codegen time.

**Comment by zvookin** [comment]
https://github.com/halide/Halide/pull/3380 has a fix that turns it into an error and tests that it fails.

**Comment by zvookin** [comment]
Fixed by https://github.com/halide/Halide/pull/3380.
