### ISSUE TITLE
webassembly branch: generating wasm, input buffer

### ISSUE THREAD

**Issue by rajeevgUCI** [halide/Halide#3444]
I successfully used [the webassembly branch](https://github.com/halide/Halide/tree/webassembly) to compile a pipeline to wasm, and ran the pipeline on data in the browser. But I was wondering if my approach can be improved: is there a better way to convert a Halide pipeline to wasm, or a better way to generate an input buffer?

My current approach is:
1. Compile Halide pipeline to .s assembly using the webassembly branch.
2. Use [binaryen](https://github.com/WebAssembly/binaryen) to convert the .s to .wasm. I had to make a change to the webassembly branch, [see my commit here](https://github.com/rajeevgUCI/Halide/commit/c93918e31ba3d0ddfe4f729de64f061e4c74b562).
3. Write C++ code that creates a Halide input buffer.
4. Use [emscripten](https://github.com/kripken/emscripten) to compile the C++ code to .wasm.
5. Write JavaScript glue code between the Halide-generated wasm and the emscripten-generated wasm.

Thanks!

**Comment by steven-johnson** [comment]
The WASM branch is ~1 year old so I'm not surprised that it could use a little polish around the edges. (IIUC there hasn't been a lot of demand expressed for it hence the lack of work on it.) We'd definitely welcome additional work on the branch to make it easier to fit into things.

**Comment by zvookin** [comment]
I mostly decided to stop working on WebAssembly until things rationalized somewhat due to issues like this. It was not obvious how to utilize the technology and I don't really have a good use case so I can't really experiment to figure it out even if I had the time.

Glancing over the linked issue and some things hanging off it, I'm unconvinced much progress has been made in terms of what they're doing. The whole thing strikes me as pretty dubious to be honest.

That said, it seems like we want to surface both the ELF and s2wasm options. One way to do this is to have ```compile_to_object``` produce the ELF variant and ```compile_to_assembly``` produce the s2wasm variant. I'm not sure this is a good idea, but it might be. It requires adding some more plumbing to the Halide compilation path which is a bit ugly, but not too hard to do.

What is your use case? Are you seeing useful results from Halide?

**Comment by zvookin** [comment]
For now, I think I'm going to throw in a total hack and overload "NoOS" as the operating system to mean using the wasm target triple and default to ELF otherwise per the commit.

**Comment by zvookin** [comment]
@steven-johnson @rajeevgUCI IS this issue still relevant given the merged WebAssembly support? It looks like there may still be a usability issue in integrating Halide wasm output with the JavaScript. If so, it seems it may be more productive to open a new issue with that made explicit and to close this one.

**Comment by steven-johnson** [comment]
Sorry, I never saw the comment from @rajeevgUCI.

(1) Halide only supports the llvm backend; we don't support fastcomp, s2wasm, etc and likely never will, as the LLVM backend is where most dev work is happening now.

(2) we haven't investigated autogenerating JS glue code, as (literally) no one else has requested it so far, believe it or not. (we'd be very happy to have a PR contributing such a change.)

agreed that closing this issue and opening new one(s) as appropriate is the right thing at this point.
