### ISSUE TITLE
Simplifier not simplifying dead lets

### ISSUE THREAD

**Issue by dsharletg** [halide/Halide#3631]
I have an expression that is not getting simplified as I expect:

expr:

    (let t12073 = ((t11933/2) + ((gained.s0.x.x + yuv.s0.x.min_1.s)*64)) in (((t12073 + -3) + (63*1)) - ((t12073 + -3) + (0*1))))

simplify(expr):

    (let t12073 = ((t11933/2) + ((gained.s0.x.x + yuv.s0.x.min_1.s)*64)) in 63)

I think the issue is that here, var_info.old_uses is greater than 0, but the var is not actually used anymore. If I make this change, I get the simplification that I expect (the expression is simply 63):

    @@ -200,7 +201,7 @@ Body Simplify::simplify_let(const LetOrLetStmt *op, ExprInfo *bounds) {
             result = LetOrLetStmt::make(it->new_name, it->new_value, result);
         }
 
    -    if (info.old_uses > 0 || !remove_dead_lets) {
    +    if ((info.old_uses > 0 && stmt_or_expr_uses_var(result, it->op->name)) || !remove_dead_lets) {
             // The old name is still in use. We'd better keep it as well.
             result = LetOrLetStmt::make(it->op->name, it->value, result);
         }

(Keeping the old check seems to avoid serious compile time issues).

However, I can't seem to find a failing expression to put in test/correctness/simplify.cpp! Reimplementing the expression I gave is simplifying correctly in the context of that test.

**Comment by abadams** [comment]
The issue is that a var can be counted as used, and then removed by a later simplification that cancels it out, so you might be able to create a test case that way: `let x = sqrt(y) in (x - x + 3)`

stmt_or_expr_uses_var is a big hammer to use in the middle of the simplifier though. It implies a full recursive walk over the inside of the letstmt, which could have n^2 complexity for chains of not-dead letstmts. It could be safer to do a single remove-dead-lets pass after a simplifier run. It's worth benchmarking the compile time of large pipelines with this change (e.g. performance_lots_of_inputs has very long chains of of letstmts).
