### ISSUE TITLE
warning_parallel_size_one and warning_vectorize_size_one are broken

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#3762]
git bisect suggests that https://github.com/halide/Halide/pull/3720 is the culprit here

**Comment by shoaibkamil** [comment]
Broken how— in that you get false positives (the warning even when it isn’t by 1) or because it’s not triggering the warning when it should?

I ask because if it’s the former, I’m almost certain it’s a preexisting problem that is showing up on more pipelines because of the new rules.  I’ve been trying to create a small test case.


________________________________

**Comment by steven-johnson** [comment]
Neither are producing a warning any more.

**Comment by abadams** [comment]
I think it's just that the simplifier now removes loops of size 1 without warning when they're vectorized or parallel.

Was this actually a useful warning? I only ever saw it fly by due to specializations, so it had that classic warning problem - I was trained to ignore it.
