### ISSUE TITLE
Tiled compute_with allocates entire outer dimension for tile case.

### ISSUE THREAD

**Issue by zvookin** [halide/Halide#3767]
The correctness_compute_with Yuv 420 test case is massively over-allocating and computing an intermediate buffer scheduled on tiles. In the test case, the `u_part` and `v_part` `Funcs` are recomputed at each tile but the height (`y` dimension) is computed for the size of the entire input, not the size of the tile.

https://github.com/halide/Halide/tree/compute_with_excessive_bounds has the `correctness_compute_with` test modified to fail due to this issue via counting the total number of loads and stores and comparing it to the `compute_root` reference version.

I spent a little time trying to see if this was happening when `compute_with` was first merged, but ran into issues getting a compatible llvm for compiling Halide at various times. (Thus git bisect is a bit trickier.) Wanted to get the issue filed quickly in case the cause is obvious or easily finable for others.

**Comment by alexreinking** [comment]
I'm working through some compute_with bugs right now. I'll see if this happens to get fixed along with the others.

**Comment by vksnk** [comment]
(Background: I've been looking into this issue lately and I think I understand what's happening, but would really appreciate an input from someone with more experience)

Context:

[Note: I simplified the test case from Zalman a bit to make it more tractable for now, but I believe it's still representative]. It might be easier to look at the [test itself](https://github.com/halide/Halide/commit/7eddb00823b4315e3734ae7e0927dbac837455e4#diff-dc08b4fbd878cc0dcb2a9552b0142673L492), but here is the key elements:

- there are three functions y_part, u_part, v_part
- u_part, v_part are scheduled to compute_with(y)
- there is an intermediate rgb_x function, which is compute_at(y)
- (this is important bit) rgb_x is only used at u_part and v_part

The problem is that currently it will allocate entire image for rgb_x and recompute it on every iteration of outer loop (y_part.y). As far as I can tell, the cause of this is that during bounds inference, when producing bounds for rgb_x, it will consider only y_part, but not u_part or v_part and given that  y_part doesn't depend on rgb_x, bounds for rgb_x loops won't be tightened.

I have no prior experience with bounds inference code, so I would really appreciate if someone can take a look at [commit](https://github.com/halide/Halide/commit/7eddb00823b4315e3734ae7e0927dbac837455e4#diff-a65c253e795b129c8f05b3ed52c5c577R1025) and see if it makes sense. It does fixes the issue with over-allocation and over-compute and rest of the tests are still passing. The general idea idea is to estimate bounds for fused functions in addition to the "main" function whenever we are defining production bounds (sorry, code is pretty rough right now, just wanted to see if this makes sense at all).

Thanks!

**Comment by dsharletg** [comment]
@abadams could you take a look at the above possible fix? I think the proposed fix makes sense but I am not sure if it is the best option.

**Comment by abadams** [comment]
This is how I understand things:

When you're producing some of a Func A, at every loop belonging to A you potentially need to define symbols for what box is being computed of A (A.x.min, A.x.max ...), because that any other producer Func P nested there is going to define its loop bounds in terms of these symbols, to ensure it computes enough of itself to satisfy the consumer.

Now say we compute B with A, and say B consumes P, not A. Bounds inference will see the shared loop, and think it belongs to A only. Maybe it defines A.x.min and friends, maybe not, but either way that's not useful, because P's loops are in terms of B.x.min, B.x.max, etc. So without a local definition of those symbols, P will use the one in the outer scope, and compute way too much of itself. It'll still be correct, but it's massive over-compute.

If I'm understanding correctly, your fix is to realize that in this loop belonging to A, we also potentially need to define a box for B, because B belongs to the same fused group as A, so really this loop belongs to A *and* B. We'll get the box using boxes_touched and only filtering for A and B after the fact (This is potentially quite expensive - might be a good idea to only call boxes_touched if A is known to belong to a fused group, or to make a variant of boxes_touched that filters on a set of funcs instead of just one). Note that even though the loops are fused, the boxes touched of A and B might be totally different, because e.g. B could be double-resolution (as happens when fusing yuv computations), so this is not just a matter of giving A's box B's name as an alias. If we're inside one of A's non-fused loops, then there will be no accesses to B, so we need to take a little care to only define a box for B if there is indeed a region touched.

Yes, I think this approach makes sense, but it took me a long time to figure out what was happening, so good comments will be key.

**Comment by vksnk** [comment]
Thank you, Andrew!

> This is how I understand things:
> 
> When you're producing some of a Func A, at every loop belonging to A you potentially need to define symbols for what box is being computed of A (A.x.min, A.x.max ...), because that any other producer Func P nested there is going to define its loop bounds in terms of these symbols, to ensure it computes enough of itself to satisfy the consumer.
> 
> Now say we compute B with A, and say B consumes P, not A. Bounds inference will see the shared loop, and think it belongs to A only. Maybe it defines A.x.min and friends, maybe not, but either way that's not useful, because P's loops are in terms of B.x.min, B.x.max, etc. So without a local definition of those symbols, P will use the one in the outer scope, and compute way too much of itself. It'll still be correct, but it's massive over-compute.

Yes, this is exactly the problem/inefficiency.

> If I'm understanding correctly, your fix is to realize that in this loop belonging to A, we also potentially need to define a box for B, because B belongs to the same fused group as A, so really this loop belongs to A _and_ B. We'll get the box using boxes_touched and only filtering for A and B after the fact (This is potentially quite expensive - might be a good idea to only call boxes_touched if A is known to belong to a fused group, or to make a variant of boxes_touched that filters on a set of funcs instead of just one). Note that even though the loops are fused, the boxes touched of A and B might be totally different, because e.g. B could be double-resolution (as happens when fusing yuv computations), so this is not just a matter of giving A's box B's name as an alias. If we're inside one of A's non-fused loops, then there will be no accesses to B, so we need to take a little care to only define a box for B if there is indeed a region touched.

Yes, that's correct. I'll add checks, so boxes_touched is only called when necessary (i.e, only for fused functions and only at fused loop dimensions).

> Yes, I think this approach makes sense, but it took me a long time to figure out what was happening, so good comments will be key.

Sorry, I should've explained better. I'll add comments for sure.

**Comment by vksnk** [comment]
Should be resolved now.
