### ISSUE TITLE
Code generation is very slow

### ISSUE THREAD

**Issue by mirsadm** [halide/Halide#3830]
I have a generator that is quite complicated with many inputs and functions. Generating a static library can take up to 30 minutes on my MBP. This makes testing different schedules very difficult. I have thought about splitting the pipeline into multiple generators but that limits the available scheduling options. Is there anything I can do to reduce the generation time?

**Comment by dsharletg** [comment]
One thing to do is check to see if you are generating a reasonable amount of code for the algorithm. It's quite possible to easily generate very large amounts of code. I find that when optimizing large pipelines, I need to keep code size in mind. Some things that help:

- When using boundary conditions, only use BoundaryConditions helpers on dimensions that will be vectorized, or are otherwise expensive to have clamps in the coordinate computations of. These helpers split up the loops affected by boundary conditions, which can be a large increase in code size. In the typical case of just using repeat_edge on an image processed in the usual loop ordering, it's not slow to just use a `clamp(y, y_min, y_max)` instead of `BoundaryConditions::repeat_edge`.

- Use `TailStrategy::RoundUp` when splitting internal pipeline stages.

- Be careful with `unroll`. Of course it can be helpful, but it comes at a code size cost of course.

I've found that being aware of these 3 things leads to reasonable code size/compile time well beyond the point at which there is value from fusing pipeline stages, and so it is reasonable to split a pipeline up into separate pipelines at that point (as there would just be a compute_root() there in an end-to-end pipeline anyways). But of course this will depend on the algorithm. The other option is if you are able to provide some example bitcode (via compile_to_bitcode), we can take a look and see if this is triggering some pathological case in LLVM (cc @alinas).

**Comment by mirsadm** [comment]
Thanks for the advice. I'll look into providing some example bitcode as soon as I can.
Basically part of the algorithm is to perform a wavelet transform on a few images. Increasing the number of levels for the forward transform increases the code generation time significantly.

Eg:

```
for(int i = 0; i < inputs.size(); i++) {
    for(int level=0; level < levels; ++level) {
        forwardTransform(inputFromPreviousLevel, output);
    }
}

```

forwardTransform() performs a wavelet transform over rows/cols of the input. My guess is that is the cause of the slow code generation. I ran the generator through Instruments to see if there was anything obvious and it seems to be spending a lot of time in ```make_producer_consumer()``` in ```src/AsyncProducers.cpp.```.

**Comment by dsharletg** [comment]
It is also quite possible that there is also an issue in Halide lowering that needs investigation.

For algorithms like this, assuming that there is downsampling/decimation between the pyramid levels, I find that it is only necessary to fuse a few pyramid levels to get the performance advantages of fusion. 3 levels of a decimate-by-2 pyramid contains ~98% of the work.

Even if not decimating, I still would think that fusing just a few pyramid levels together would give most of the benefit.

An added advantage of this approach is that you can dynamically determine the number of pyramid levels to use.

**Comment by abadams** [comment]
30 minutes is a little ridiculous - maybe you have found something pathological in either llvm or Halide. Our general rule is to try to keep the time spent inside Halide under the time spent inside llvm. If that's not the case, and you're not generating exponentially large amounts or IR, we'd love a repro so we can fix it.

**Comment by mirsadm** [comment]
I've hacked together a quick generator here:
```https://github.com/mirsadm/cwt_test/blob/master/cwt_generator.cpp```

Running it with
``` ./cwt_generator -g cwt_generator -f cwt_generator -e static_library,h,schedule -o . target=host-profile levels=6 inputs.size=4```

Takes a long time on my Mac. I'm new to Halide so I apologize in advance if there is something obvious in there which is causing this.

**Comment by abadams** [comment]
This is large, but not ridiculously large. For me on my macbook it got through the Halide portion of compilation in 80s, and is now stuck inside LLVM. I guess I'll see how long it takes there. If it's a modest amount of bitcode we should punt it to an llvm dev to look at. One change to the code that will speed things up is to make i a Var instead of a c++ for loop, and make all your Func arrays that are index by i single 4d Funcs instead of an array of 3d Funcs. This also gives you the option of doing things like parallelizing across i.

**Comment by mirsadm** [comment]
Mine has finished and it has taken about 17 mins.

```time DYLD_LIBRARY_PATH=/Users/mirsadm/Workspace/halide/bin ./cwt_test -g cwt_generator -f cwt_generator -e static_library,h,schedule -o . target=host-profile levels=6 inputs.size=4

real	17m53.719s
user	17m42.054s
sys	0m3.815s
```

**Comment by abadams** [comment]
14.6 minutes for me, so you're definitely not holding it wrong. It generates 4MB of llvm bitcode though (and 3MB of compiled binary), so I think the problem is just that you're generating too much code for llvm to handle gracefully in a single compilation unit. Making i a Var should cut it down by a factor of four. Beyond that I think you'd have to break it into more generators.

**Comment by mirsadm** [comment]
Makes sense. Thanks for the help.

**Comment by mirsadm** [comment]
For anyone else having this issue I've been able to reduce the code generation time signifiantly by replacing uses of Func with Expr at a slight cost to code readability.

**Comment by steven-johnson** [comment]
Is this still open/actionable?
