### ISSUE TITLE
Regarding fft in halide

### ISSUE THREAD

**Issue by yvn96** [halide/Halide#3856]
I want to compute fft on a 128x128 or 256x256 buffer. Since halide only supports 16x16, 32x32, 48x48 and 64x64, how will I be able to do that with the help of halide? Any leads will be appreciated.

**Comment by dsharletg** [comment]
The sizes you listed are just the ones benchmarked by the Makefile. The app and algorithm itself support any size (https://github.com/halide/Halide/blob/master/apps/fft/main.cpp#L38-L43). 

However, the Halide FFT is only really efficient for <64x64, maybe only <48x48 FFTs. Larger FFTs would require a different scheduling strategy.  The benefits of a Halide FFT are bigger when the FFT is small and you are doing many of them, because you can fuse and optimize the FFT and the surrounding pipeline together. With larger FFTs, the improvements offered by these kinds of optimizations are smaller, and so there's less reason to not just use fftw or another library. This is one of the use cases of 'extern stages'.

**Comment by yvn96** [comment]
thanks for the information @dsharletg

**Comment by steven-johnson** [comment]
Sounds like this is resolved. Closing.
