### ISSUE TITLE
TSAN reports data race in runtime/can_use_target.cpp

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4140]
With the caveat that there are no harmless data races, this is a harmless one; that said, we should fix this so that downstream users who test with TSAN aren't alarmed. It should be possible to fix this via adding `can_use_target_tsan` variants, in the same way we have done for (e.g.) posix_threads vs posix_threads_tsan.

**Comment by abadams** [comment]
Is it safe though? What happens if initialized=true gets moved before the memcpy

**Comment by steven-johnson** [comment]
Looks to me like the race can be that `cpu_features_storage` can be written to multiple times -- but it should just be wasted effort (writing the same data to it), thus 'benign' in that sense. Is there a path by which it couldn't be written at all?

**Comment by steven-johnson** [comment]
(Obligatory..)

![unnamed](https://user-images.githubusercontent.com/328955/63118081-009ca480-bf52-11e9-89dd-bc8199734385.gif)

**Comment by abadams** [comment]
One thread could set initialized before it does the memcpy due to devious compiler or CPU shenanigans, then another thread could read that, assume cpu_features_storage has already been initialized and use the uninitialized static array. It will be zero, so I guess the consequence might be the wrong version of the code being run (mostly benign)? Or might it cause an assertion failure (all implementations of this require these CPU features)?

**Comment by steven-johnson** [comment]
Fair. Will fix.
