### ISSUE TITLE
Autoscheduler fails on auto_schedule_mat_mul because the old version is run

### ISSUE THREAD

**Issue by kpassarella** [halide/Halide#4152]
The old autoscheduler result in auto_schedule_mat_mul is much worse than the manual result (25ms vs 7ms). This test should either be fixed or disabled.

**Comment by steven-johnson** [comment]
@abadams -- Not sure whether we are just neglecting to verify that the performance tests for the old autoscheduler are run sequentially (and thus subject to bogus slowdowns), or if there is a genuine slowdown here. Should we bother trying to investigate, or just disable the performance tests to avoid false failures?

**Comment by abadams** [comment]
On my machine it barely passes:
Manual time: 9.37877ms
Auto time: 25.4584ms

Honestly though, the manual schedule for mat mul could be better. I can get it down to 7.6ms by just changing the tile size to 16x6. Looks like 7.2ms is where it would start failing for me with the current threshold.

I guess the purpose for these autoscheduler tests is that we want to make sure the autoscheduler doesn't have a massive performance loss or stop working entirely due to an apparently unrelated change, not to claim that autoscheduler is good at mat mul. Let's just change the threshold from 3.5x to 5x.

**Comment by steven-johnson** [comment]
fixed
