### ISSUE TITLE
Should autoscheduler benchmarks use CPU time instead of wall time?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4170]
The halide_benchmark() utility (and thus RunGen, and thus all of the autoscheduler benchmarking) measures performance using wall-clock time rather than CPU time; this means that we are always optimizing for latency, but not necessarily efficiency of CPU utilization -- the latter might well be preferable for certain tasks (e.g. non-interactive server processing of images)

Would it make sense to revise the autoscheduler benchmark criteria to include minimization of CPU time as a factor (in combination with and/or instead of wall-time)?

**Comment by abadams** [comment]
The way people who care about throughput usually benchmark is to run something on an otherwise unloaded machine and measure total CPU time. This almost always favors just running the whole thing single-threaded, as anything else would imply a super-linear speedup from parallelism, which is very rare. So you can probably satisfy these people by just setting params.parallelism to 1.

**Comment by steven-johnson** [comment]
@abadams Feel free to close if you think this is not actionable

**Comment by abadams** [comment]
I think params.parallelism = 1 is adequate for this use-case.
