### ISSUE TITLE
When should we consider moving Halide to C++17?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#4216]
Currently, Halide assumes/requires C++11. When should we consider moving our baseline to C++17? 

(FYI: Google recently moved to allow use of C++17 internally, so we'd be fine with this; I don't know how many other downstream users might be impacted by such a change. Would be nice to start a discussion.)

**Comment by abadams** [comment]
constexpr if and parameter pack folds would be very nice. However it would raise our required gcc version to 7, MSVC version to 2017, and clang version to 8. That seems fairly aggressive to me. Then again, we already require that you have clang 7 or greater just to compile the runtime.

**Comment by steven-johnson** [comment]
Since the current version of MSVC is 2019, requiring MSVC 2017 seems pretty reasonable to me. (Are we still running 2015 on the builtbots?) Ditto for gcc 7. But we should get widespread input to see if how this would impact existing users.

**Comment by benoitsteiner** [comment]
Debian stable only ships with llvm/clang 7, so it would make it harder to use Halide for folks. In my company we're using what looks like clang7 with some modification, so that would mean goodbye to Halide. It would be best to delay the upgrade for some time until the mainstream environments have caught up.

**Comment by slomp** [comment]
I'm OK with upgrading the compiler for the "internals", but at for the public interface, I think it's wise to hold and be a bit conservative with C++11 for now.

**Comment by alexreinking** [comment]
@benoitsteiner  - is `clang-8` not [available on sid](https://packages.debian.org/sid/clang-8)?

**Comment by steven-johnson** [comment]
@benoitsteiner I don't think anyone is in a rush (at least, I'm not); I mainly want to start thinking about timetables. Would you have a guesstimate as to when your folk would be able to use C++17 without causing any hardship?

**Comment by alexreinking** [comment]
> Debian stable only ships with llvm/clang 7, so it would make it harder to use Halide for folks. [...]

We require LLVM/Clang 9+ to build Halide. I guess you're using binary releases?

**Comment by abadams** [comment]
Installing llvm 9 as a system toolchain is a bigger deal that just requiring that someone build llvm 9 as a library as part of building Halide.

**Comment by alexreinking** [comment]
This matrix might be helpful

| C++ standard | Compiler | Supported since | Release date | Notes |
|--|--|--|--|--|
| C++11 | GCC | 4.8.1 | May 31, 2013 |
|  | Clang | 3.3 | June 17, 2013 |
|  | MSVC | 2015 | July 20, 2015 | 
| C++14 | GCC | 5.1 | April 22, 2015 | default since v6.0 |
|  | Clang | 3.4 | Jan 2, 2014 |
|  | MSVC | 2017 15.0 | March 7, 2017 |
| C++17 | GCC | 7.1 | May 2, 2017 | default since v11.0 |
|  | Clang | 5 | September 7, 2017 |
|  | MSVC | 2017 15.7 | May 07, 2018 | DRs missing until 2019 16.4 |

References:

https://gcc.gnu.org/projects/cxx-status.html
https://gcc.gnu.org/releases.html
https://clang.llvm.org/cxx_status.html
https://releases.llvm.org/
https://docs.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2015-version-history
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.0

**Comment by alexreinking** [comment]
> Installing llvm 9 as a system toolchain is a bigger deal that just requiring that someone build llvm 9 as a library as part of building Halide.

Moot point since Clang supports C++17 since version 5, and @benoitsteiner is on version 7.

**Comment by abadams** [comment]
I claimed 8 because I was taking the max along the clang version column in https://clang.llvm.org/cxx_status.html, but actually there's a 9. I'm not sure how seriously to take the DRs.

**Comment by abadams** [comment]
Maybe the solution is to just make sure one of the buildbots is using our minimum supported clang/gcc version, and permit anything that it will accept?

**Comment by alexreinking** [comment]
> I'm not sure how seriously to take the DRs. [...] Maybe the solution is to just make sure one of the buildbots is using our minimum supported clang/gcc version, and permit anything that it will accept?

I'm not either, but this is the correct solution no matter what minimum C++ version we take.

**Comment by steven-johnson** [comment]
> AFAIK, our minimum supported compiler versions all permit C++14, though we would need to bump the version for GCC if we wanted to require C++17.

Do we actually explicitly specify minimum versions of gcc/clang anywhere? I'm not aware of that. I thought we just claimed "C++11 support".

**Comment by steven-johnson** [comment]
> This matrix might be helpful

[snip]

IIRC, MSVC2015 "mostly" supported C++11 but had a few odd bugs and warts we had to work around. We absolutely should drop overt support for it as soon as no one complains.

**Comment by alexreinking** [comment]
> Do we actually explicitly specify minimum versions of gcc/clang anywhere? I'm not aware of that. I thought we just claimed "C++11 support".

The versions on our buildbots are de facto minimums. I raised the issue of making things explicit in #5154
