### ISSUE TITLE
Lesson 02 does not run on Windows

### ISSUE THREAD

**Issue by jonno85uk** [halide/Halide#4300]
After following the instructions to build halide (4a89a8f2500d934278acf54ec208ea5efd12a60e) &  llvm (v9.0) on windows it is not possible to run Lesson 02 (input image).

The returned error from the console is:

> unsupported file extension "png", supported are: mat pgm ppm tiff tmp

When changing the source image to a tiff:

> Reading TIFF is not yet supported

For pgm:

> Error:
Dimensionality mismatch accessing Buffer b0. There were 3 arguments, but the Buffer has 2 dimensions:
  (uint8)b0(v0, v1, v2)

Only PPM files work. I do not know what a mat or tmp file format is and neither does GIMP.

**Comment by alexreinking** [comment]
> Only PPM files work. I do not know what a mat or tmp file format is and neither does GIMP.

A `.mat` file is a serialized Matlab matrix. Numpy can export its arrays in that format, too. And `.tmp` is a file format used by [ImageStack](https://github.com/abadams/ImageStack), a tool written by Halide's own @abadams.

And you will need to make sure you're linking with libpng, which you should build yourself since the major sources of binary releases (Nuget, GnuWin32) have an unpatched use-after-free vulnerability.

**Comment by jonno85uk** [comment]
@alexreinking What is the variable required for cmake to include a built png into Halide?

**Comment by alexreinking** [comment]
The new tooling with #4644 and vcpkg makes this easy to do. Please open a new issue if you can't make it work from `master`.
