### ISSUE TITLE
Internal code reuse in apps and autoschedulers

### ISSUE THREAD

**Issue by BachiLi** [halide/Halide#4341]
Currently there is no easy way to reuse some internal code, which is causing code duplication for some autoschedulers. For example, the error/assertion macro (e.g. `user_error`) needs to be replicated by apps/autoscheduler.

**Comment by shoaibkamil** [comment]
Isn’t the fundamental problem here that these should not be apps, but should be something in the Halide namespace?

I don’t think we should use internal code like this in apps. That said, I don’t know if the situation for plugins is better.

**Comment by BachiLi** [comment]
Yeah this is mostly for autoscheduler plugins. So far it seems that the outstanding issue is the error macros. Not sure if there is other.

**Comment by steven-johnson** [comment]
See also https://github.com/halide/Halide/issues/4349

**Comment by alexreinking** [comment]
**Position:** `apps/` should not have access to _any_ internal code, include paths, etc. They should be self-contained, and built as an end-user would build them. Thus, since autoschedulers are not apps, but plugins, they should be relocated and treated differently as discussed in #4349 #4053 .

Similarly, the code in `tests/` straddles that boundary. Since they're fundamentally integration tests, not unit tests, and reference Halide.h, they should also be built separately and take the fully built libHalide as a dependency - again, in the same way a user would, just with somewhat more automation.

**Comment by steven-johnson** [comment]
> **Position:** `apps/` should not have access to _any_ internal code, include paths, etc. 

I regret I can give only a single +1

**Comment by abadams** [comment]
I also concur.

**Comment by alexreinking** [comment]
I will make violating this principle impossible in the CMake build, in that case.

**Comment by alexreinking** [comment]
Apps in #4644 are now built fully standalone.
