### ISSUE TITLE
Faster halide backend on qualcomm SOC

### ISSUE THREAD

**Issue by cjluo-nuro** [halide/Halide#4587]
Hi, Halide team,

I had a general question about running halide on qualcomm SOC. Since qualcomm SOC has both HVX and GPU, which one would give me better performance on a general camera post processing pipeline? (Say if power is not a concern here)

**Comment by dsharletg** [comment]
This is a hard question to answer in general, it's really going to depend on what you are doing, and the relative strength of HVX and GPU varies significantly across different Qualcomm SOCs.

Even with the same nominal performance, the GPU and HVX have very different strengths. If your workload can leverage the texture sampler to good effect, the GPU is going to be hard to beat. But if your pipeline is a large chain of stencils, HVX is probably going to be better.

There will be other differences too, e.g. the GPU might be able to execute a large chain of stencils well, but it will probably use a lot more memory to do it.

**Comment by cjluo-nuro** [comment]
Thanks Dillon. Right now we are just doing simple image processing algorithms like gamma correction, sharpening, blurring etc on 1080p or 4k images on qualcomm 845 SOC. I tried camera_pipe example on the device and it seems HVX is just 2X fast compared with arm CPU. I also tried opencl on the device, which for some reason is much slower than HVX, even CPU. Not sure if this behavior is expected.

**Comment by dsharletg** [comment]
FWIW, I think we've only really optimized the camera_pipe on the Hexagon simulator, rather than a real device, so it's possible there's still more improvement possible. It's also been a *long* time since anyone optimized it on ARM CPUs too, so there might be room for improvement there too :)

My guess is that OpenCL was slow due to overhead, memory transfers rather than the actual compute being slow (but this might be a problem in a real workload too, depending on the context).

Also, if this was done by just throwing an OpenCL schedule on the camera pipe app, it might take some work to get it running well. You're probably going to want to schedule the pointwise stuff (gamma, CCM, etc.) before the stencils somehow (local memory?).

**Comment by abadams** [comment]
The GPU schedule for camera pipe was recently reoptimized to be good on desktop GPUs via CUDA, so it should be solid (e.g. it clocks in at 1.4ms on my fairly old geforce 980). That assumes inputs/outputs are all in GPU memory already. So if it's quite slow, I'd assume there's something going wrong outside of the Halide code (e.g. memory copies to and from GPU memory).

**Comment by cjluo-nuro** [comment]
Thanks for the info. I will double check if we can optimize the scheduling on our platform to get a better performance.
