### ISSUE TITLE
Consider dropping MinGW support

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#4593]
It's unclear whether anyone uses Halide via MinGW anymore.  We should drop support if nobody is actively using it, given the fact that we have to employ specific workarounds for that environment.

**Comment by steven-johnson** [comment]
So far haven't heard about a lot of use. Might be worth also explicitly pinging the halide-dev mailing list. Since this is "working" now we don't need to be in a hurry to remove it, but it always has been an odd special case. (I wonder, have people who previously used it switched to using the Linux-on-Windows environment instead?)

**Comment by alexreinking** [comment]
Speaking for myself, I haven't used MinGW since real GCC became available on Windows via WSL. Instead, I prefer clang-cl or Intel's compiler on Windows if I don't want to use MSVC.
