### ISSUE TITLE
How to use parallel for a 1D input

### ISSUE THREAD

**Issue by jsksra1** [halide/Halide#4604]
Hi ,

I am trying Halide example for 1D buffer processing, all the examples shows "parallel"  only when the input is of 2d like f(x,y). 

In my case 

       f(x) = i1(x) + i2(x); 

	f.split(x, x_o, x_i, 16);
	f.vectorize(x_i);

My motivation for this is, if at all there is an option to use parallel then wanted to try splitting f(x) to two buffers and perform addition parallelly. 

Thanks

**Comment by ashishUthama** [comment]
You can parallelize the outer loop:

`f(x) = i1(x) + i2(x); 
f.split(x, x_o, x_i, 16);
f.vectorize(x_i);
f.parallel(x_o);
`

I would play with different split factors, since overall throughput might vary with the core count/threading over head and length of x. The idea is the same, you can recursively split x into different ranges - parallelize the outer most and vectorize the inner most.

**Comment by jsksra1** [comment]
It worked thanks, all the time I was trying to parallelize the inner loop.
But the performance is poor with any split factor if I introduce parallel, can we use tiling too when the input is 1D?

Hoping that tiling with parallel may improve the performance.

**Comment by ashishUthama** [comment]
Have a look at this section of the [tutorial] (https://halide-lang.org/tutorials/tutorial_lesson_05_scheduling_1.html). Tiling is the same as splitting and reordering loop traversals. 

I cant say more about the performance - maybe there isnt enough work that threading only adds overhead? If you can post a full repro, maybe I or someone else might be able to give you better pointers.

**Comment by jsksra1** [comment]
okay, thanks!

Probably this isn't so complex one and as you said threading just increasing overhead in this case.
