### ISSUE TITLE
Support for multi-dim vectorization

### ISSUE THREAD

**Issue by KnowingNothing** [halide/Halide#4616]
I want to port Halide to a new hardware backend. As far as I know, Halide only supports 1-D vectorization for now. Is there any support for multi-dim vectorization or is there any plan to support this? It is a valuable feature as there are more and more special accelerators that use tensorization to gain high performance. I'd be grateful if anyone can provide some useful information.

**Comment by abadams** [comment]
This is a very interesting question. We can currently vectorize multiple loops, but only using the Func::fuse directive to turn them into a single loop first. This gives you vector values that encode multi-dimensional ramps in awkward ways, e.g:

Broadcast of a ramp: Ramp(0, 1, 32) % 4 
Ramp of a broadcast: Ramp(0, 1, 32) / 4

A 2D ramp (e.g. the index when loading a dense 2D tile of a matrix) would be the sum of two things that look like that. That's the sort of IR you get if you vectorize multiple dimensions by first fusing them. Backends that support things like 2D loads could just peephole recognize those patterns. Operations that do meaningfully 2D things (e.g. take a 2D crop or transpose of a 2D vector) can use ShuffleVector to get the lanes it needs. Partial reductions across the vector (e.g. a horizontal add) are coming in my atomic_vectorization branch. With that partial reduction node, an entire matrix multiply of two vectors that are actually 4x4 matrices would look something like:
```
let a_idx = ramp(0, 1, 64) % 4 + ramp(0, 1, 64) / 16
let b_idx = ramp(0, 1, 64) % 16
let c = horizontal_add(a[a_idx] * b[b_idx], 4);
```

Now I think we could make things a little cleaner if we allowed ramps and broadcasts to take vector args, instead of requiring that they be scalar, with the semantics that you produce a multi-dimensional vector and then linearize it with the args to the broadcast or ramp innermost. So a broadcast of a vector repeats that entire vector some number of times. Then my example would be:

```
let a_idx = ramp(broadcast(ramp(0, 1, 4), 4), broadcast(1, 4), 4)
let b_idx = broadcast(ramp(ramp(0, 1, 4), broadcast(4, 4), 4), 4)
let c = horizontal_add(a[a_idx] * b[b_idx], 4);
```
which is maybe easier on the backends? The multi-dimensional structure is more clearly expressed in the index as ramp of broadcast of ramp, or broadcast of ramp of ramp. A backend that wants to peephole optimize a dense 2D load could look for a load of a ramp that has ramp base and broadcast stride.

Separately we could have the vectorize loops pass handle nested vectorization to remove the requirement to call Func::fuse. This would be simpler to implement if we had nested ramps/broadcasts.

Note that none of this requires the Type system to change. Any new intrinsics that do 2D operations to a vector value would have to encode the shape in the operation, not the types of the args (e.g. the way LLVM encodes signedness of integer ops in the operation, not the type).

The reason I don't want to change the type is that I think 99.9% of the time you don't care about the shape of a multi-dimensional vector, just maybe the total number of lanes. Type is a simple 32-bit struct right now, and making it variable-sized would be a huge pain.

Tagging @dsharletg , with whom I've been chatting about this.

**Comment by KnowingNothing** [comment]
Thank you for your comments. I think the two solutions give me a lot of inspirations. But I still have some questions:
1. The code below is a matrix multiply of 4x4, but it seems `a[a_idx]` represents a matrix of shape 16x4, while `b[b_idx]` represents a vector of length 16. So I am confused about this code.
```c
let a_idx = ramp(0, 1, 64) % 4 + ramp(0, 1, 64) / 16
let b_idx = ramp(0, 1, 64) % 16
let c = horizontal_add(a[a_idx] * b[b_idx], 4);
```
2. I think ramp of ramp can express a matrix, but why ramp of broadcast of ramp or broadcast of ramp of ramp?
3. Another person with whom I talked about this suggested me to modify `struct Type` by adding a pointer `Type*` to represent the tensor type, which would bring a constant overhead of `sizeof(pointer)` bypes. I think it is acceptable anyway. Will this cause other problems if we don't care about the extra memory overhead?
Thanks a lot!

**Comment by vksnk** [comment]
This sounds like a very useful feature to have, is anyone actively working on it? If not I would like to take on it. More specifically (exactly as Andrew suggested, just reiterating) starting with extending Ramp/Broadcast to allow vector arguments and then going to nested vectorization.

Just to confirm my own understanding of the above, if we want to represent 4x4 matrix multiplication then we need to have a 4x4x4 indices in total (with extra 4x multiplier for reduction) and range for each should be from 0 to 15 (because matrices are 4x4), and they represent the way we iterate over corresponding matrices, which, I think, would explain the following code from above:

```
let a_idx = ramp(0, 1, 64) % 4 + ramp(0, 1, 64) / 16
let b_idx = ramp(0, 1, 64) % 16
let c = horizontal_add(a[a_idx] * b[b_idx], 4);
```

However, I think there might be a missing 'stride' in the computation of a's indices and it should be something like:

```
let a_idx = ramp(0, 1, 64) % 4 + 4 * int(ramp(0, 1, 64) / 16)
```

is that right?

**Comment by abadams** [comment]
Nobody's actively working on it, so feel free. And I think you're right about the indexing. As I wrote it, a_idx <= 6.

**Comment by vksnk** [comment]
After some experimentation, I have another question:

let's say nested ramps/broadcasts are allowed, as well as nested vectorization. Also, let's suppose we have following program:

```
    f(x, y) = x + y;

    f.compute_root()
        .tile(x, y, x, y, xi, yi, 4, 2, TailStrategy::RoundUp)
        .vectorize(xi, 4)
        .vectorize(yi, 2);

```

right before vectorization pass IR would look like:

```
 produce f {
  for (f.s0.y.y, 0, 9) {
   for (f.s0.x.x, 0, 6) {
    vectorized (f.s0.y.yi.v1, 0, 2) {
     vectorized (f.s0.x.xi.v0, 0, 4) {
      f[(((((f.s0.y.y*2) + f.s0.y.yi.v1)*f.stride.1) + ((f.s0.x.x*4) + f.s0.x.xi.v0)) - ((f.min.1*f.stride.1) + f.min.0))] = (((f.s0.x.x*4) + f.s0.x.xi.v0) + ((f.s0.y.y*2) + f.s0.y.yi.v1))
     }
    }
   }
  }
```

now focusing only on the value of the Store node to narrow things a bit:
```
(((f.s0.x.x*4) + f.s0.x.xi.v0) + ((f.s0.y.y*2) + f.s0.y.yi.v1))
```
after going through a pass of VectorSubs to replace one of the vectorized loop vars with ramp, as well as to widen surrounding pieces of expression, we will end up with something like:
```
((x4((f.s0.x.x*4)) + ramp(0, 1, 4)) + x4(((f.s0.y.y*2) + f.s0.y.yi.v1)))
```

My question is if we go for the second pass (to replace the second loop var), should we consider nested ramps while computing the number of lines to widen? To be more concrete:
```
// without considering nested ramps
((x4((f.s0.x.x*4)) + ramp(0, 1, 4)) + x4((x2((f.s0.y.y*2)) + ramp(0, 1, 2))))
```
 or 
```
//  considering nested ramps
(x2(x4((f.s0.x.x*4)) + ramp(0, 1, 4)) + x4((x2((f.s0.y.y*2)) + ramp(0, 1, 2))))
```

As a more localized example, which way is correct to widen an expression with nested ramps/broadcast: `ramp(x2(0), x2(1), 4) + x4(1)` or `ramp(x2(0), x2(1), 4) + x8(1)`?

**Comment by vksnk** [comment]
Thank you, that makes sense. 

I came to this question when I started to extend VectorizeLoops to support nested ramps/broadcasts and realized that they need to be accounted when we compute how much widening needs to happen (which I think I understand how to do). However, then I got concerned that it may break somewhere down the line whenever we call lanes() on ramp, so maybe I actually need to make lanes() of ramp return total number of lanes including nested ramps  (basically, for something like this `ramp(x2(0), x2(1), 4)`, should lanes() method return 4 or 8?) Or maybe update all the code down the line to account for that? I am not even sure if this is a valid concern, though.

**Comment by abadams** [comment]
The type of ramp(x2(0), x2(1), 4) should be Int(32, 8), otherwise things don't make sense to me. So ramp->type.lanes() should return 8, but ramp->lanes is 4. Currently they're equal, so it might be tricky to adjust existing code.

**Comment by vksnk** [comment]
Ugh, I somehow combined ramp->type.lanes() and ramp->lanes into one entity in my brain, so that was the source of confusion, sorry about that. That definitely clears things up, thanks a lot!

**Comment by vksnk** [comment]
I have another question and would really appreciate any help.

progress so far is:
* updated Ramp and Broadcast to support vector base and stride;
* VectorizeLoops can handle basic case of nested vectorized loops;
* updated (some of) simplification rules for ramp/broadcast to make sure that they are only applied to the expressions with the same number of lanes;
* there is an extra pass in the end which goes over the IR tree and flattens nested ramps/broadcasts using concat. This helps to keep existing codegens unchanged, which, I think, is nice for now, because it helps to keep the change smaller and more localized.

Putting it all together it's possible to run a simple end-to-end [test](https://github.com/halide/Halide/compare/vksnk/vector-ramp#diff-15a1cb4a23aa316b8d5e02b8507953f0R12) with nested vectorization. I am going to work on more test cases and fixing things as they come (I am sure there will be many).

Question:
After enabling nested ramps/broadcast, it is now possible to have expressions like `x2(ramp(0, 1, 4)) + x4(ramp(0, 1, 2))`, which are (understandably) problematic for the current simplification rules, because they assume that number of lanes in the corresponding ramps/broadcasts are matching. 

IRMatcher code is quite complex and I've been struggling quite a bit with a proper way to resolve it. There is a lane field in ramp/broadcast, however it's not a wildcard, but rather plain int. Initially, I've added a loop over it and generated a separate rule for each:

```
for (int ix = 2; ix < 64; ix++) {
    // clang-format off
    if (EVAL_IN_LAMBDA
        (rewrite(x + x, x * 2) ||
         rewrite(ramp(x, y, ix) + ramp(z, w, ix), ramp(x + z, y + w, ix)) ||
         rewrite(ramp(x, y, ix) + broadcast(z, ix), ramp(x + z, y, ix)) ||
         rewrite(broadcast(x, ix) + broadcast(y, ix), broadcast(x + y, ix)) ||
         rewrite((x + broadcast(y, ix)) + broadcast(z, ix), x + broadcast(y + z, ix)) ||
         rewrite((x - broadcast(y, ix)) + broadcast(z, ix), x + broadcast(z - y, ix))
        )) {
        return mutate(rewrite.result, bounds);
    }
    // clang-format on
}
```

This worked, but is obviously horrible. 

Then I realized that it's possible to pass a predicate, so ended up writing one to check that passed wildcards have the same number of lanes. It seems to be working, but given the complexity of the code, I feel like I might be missing something and it's not fully correct. Could you please take a look at the [predicate itself](https://github.com/halide/Halide/compare/vksnk/vector-ramp#diff-a1f33a6ba27b9f04670c4fcaa9d50ec8R1881) and the [way it's used](https://github.com/halide/Halide/compare/vksnk/vector-ramp#diff-83519e65b7d06e1a4c722d5aa94a9237R52)?  

Another option is to try to turn lanes argument into wildcard, which I think would be really nice, but I couldn't make it work on my first attempt. I wanted to check if this is a good idea at all, before spending more time on it. What do you think?

**Comment by abadams** [comment]
I think making lanes into a wildcard could be a good idea, but your existing solution seems simpler and reasonable. It you want to turn lanes into a wildcard I could help. I'd generalize the predicate  to same_type instead of just checking if it's the same number of lanes. That could be useful in other contexts.

**Comment by vksnk** [comment]
Thank you, Andrew! This is really helpful!

I was worrying that it just appears to be working, so it can be a source of subtle and difficult to figure out bugs, but now I am more confident (it still can be, if implementation is wrong in some way, but at least know I know that it's sound in theory :) ). Given that, I probably leave the predicate (great point about generalizing it to compare full type, should be easy to change) as is for now and focus on other things, like more tests and corresponding fixes (there are quite a few missing pieces!). After everything else, I would like to give another try in turning lanes into wildcard, but if it doesn't work out, I would definitely ask for help. Thanks again!
