### ISSUE TITLE
How to avoid Simplify to the same Call?

### ISSUE THREAD

**Issue by KnowingNothing** [halide/Halide#4698]
Hi, I am modifying Halide for my own project. I want to construct a series of customized Call nodes which load vector-typed data using Shuffle. That is, `Shuffle::make_concat({Call::my_load, Call::my_load....})`. My Call::my_load actually loads data from a FIFO so all the `Call` nodes in `Shuffle`  have the same structure and parameters.  I want to reserve them but Simplify pass, unfortunately, eliminates all of them and transforms Shuffle to Ramp. I don't know much about the Simplify, could anyone kindly tell me how to avoid such a problem? 

Thank you!

**Comment by abadams** [comment]
If the calls are the same IR, but mean different things, e.g. because of side-effects, then one trick is just to give each a unique argument that gets ignored. This won't prevent the simplifier from reordering them though if they occur in the same expression. You might want each call to be in its own LetStmt. Also, make sure the Call nodes use one of the impure call types (e.g. CallType::Extern)

**Comment by KnowingNothing** [comment]
Thanks! I tried your solution. My problem is solved now.
