### ISSUE TITLE
Using Halide for HVX and Hexagon DSP together

### ISSUE THREAD

**Issue by ImageHandler** [halide/Halide#4917]
Hi,
I have been working on Hexagon DSP provided by qualcomm. My questions are
1. Apparently, the divisions are not fast enough to be performed on Hexagon DSP, is there any way in which halide can make it faster? Or any other way I can make it faster manually using q_format etc?
2. Some functions might work better using HVX intrinsics than using Halide on the Qualcomm DSP. So once I enter the DSP I don't want to go back to the CPU, so how do I make  it work for Halide Offload mode? E.g I have 3 functions for which I have the generators also, but 2nd function works better in Intrinsics, after processing fn 1 I want to perform fn 2 but wihtout going back to CPU(since the IPC overhead is high ~0.6 ms). Is there any way by which I can call function directly from generator of 1st function (something to that sort of)?

Thanks!

**Comment by dsharletg** [comment]
Regarding 1: You'll need to find ways to avoid division in your algorithm. There are lots of ways to approach this, all with different precision/constraints. Most are going to involve using fixed point reciprocals instead of division, i.e. instead of `x / y`, you compute `(x * inv_y) >> N`. If inv_y varies in a small range, you can use a small lookup table (which can map to `vlut` on Hexagon, which is pretty fast).

Regarding 2: I think you should just not use the offload model, and target Hexagon directly instead. Halide can generate header/object files for Hexagon, e.g. with a target `hexagon-32-qurt-hvx_128`. Then you can just call these functions from Hexagon code as you would any other function.
