### ISSUE TITLE
cmake should halt if HL_TARGET does not contain platform/host

### ISSUE THREAD

**Issue by slomp** [halide/Halide#5009]
For context:
- Windows
- MSVC build
- `HL_TARGET=d3d12compute` (note: no `host`, or platform/os)

The build process was going its merry way, and all looked fine, until it reached this point:
```
LINK : fatal error LNK1181: cannot open input file 'cost_model.a' [apps\autoscheduler\Halide_Adams2019.vcxproj]
```
(note the '.a' suffix where it should have been '.lib')

We should probably emit some warning during cmake setup if `HL_TARGET` does not have enough context.

**Comment by steven-johnson** [comment]
I would have thought that would parse as `host-d3d12compute`, which should be legal -- any idea what it ends up being parsed as?

**Comment by steven-johnson** [comment]
(but yeah, targets should probably have unambiguous arch-bits-os, either explicitly or via `host`)

**Comment by slomp** [comment]
The _really_ scary thing is that it happens to "just work" if you're on Linux/macOS/*nix platform.

**Comment by slomp** [comment]
> I would have thought that would parse as `host-d3d12compute`, which should be legal -- any idea what it ends up being parsed as?

I don't know what it ends up being parsed, but this is what @alexreinking suggested, that eventually led to the realization that it was missing the platform/os in the target:

- open `cmake/HalideGeneratorHelpers.cmake`
- find L140 (`_Halide_get_library_suffix(...)`)
- and add this on the line right after it:
`message("Getting lib suffix for ${TARGET}, ${GEN_TARGETS} -> ${HL_STATIC_LIBRARY_SUFFIX}")`

which then started to print the following during cmake generate:
```
Getting lib suffix for acquire_release, d3d12compute-no_runtime -> .a
Getting lib suffix for alias, d3d12compute-no_runtime -> .a
Getting lib suffix for argvcall, d3d12compute-no_runtime -> .a
Getting lib suffix for async_parallel, d3d12compute-no_runtime -> .a
...
```

**Comment by alexreinking** [comment]
> I would have thought that would parse as `host-d3d12compute`, which should be legal -- any idea what it ends up being parsed as?

So CMake didn't like it because it assumed that targets would always have either host or arch-bits-os present. It determines the static library suffix the generator will use by first checking if "host" is in the string (in which case it uses CMAKE_STATIC_LIBRARY_SUFFIX), then it looks for "windows" (uses .lib), else it defaults to ".a".

This is easier to maintain than outright duplicating generator logic in CMake.

Speaking of which, it just occurred to me that adding a "cmake" output option to the generator to emit an importable script next to the other outputs might be something worth evaluating if this sort of thing becomes a persistent cause of pain.

**Comment by steven-johnson** [comment]
Oh, wait -- so this is something CMake-specific? I hadn't realized that. Yeah, if CMake is parsing the target strings itself then yeah, we need some more smarts.

**Comment by alexreinking** [comment]
The issue is here:

function(_Halide_get_library_suffix OUTVAR)
    if ("${ARGN}" MATCHES "host")
        # Since all OSes must match across target triples, if "host" appears at all, then it must match CMake
        set(${OUTVAR} "${CMAKE_STATIC_LIBRARY_SUFFIX}" PARENT_SCOPE)
    elseif ("${ARGN}" MATCHES "windows")
        # Otherwise, all targets are windows, so Halide emits a .lib
        set(${OUTVAR} ".lib" PARENT_SCOPE)
    else ()
        # All other targets use .a
        set(${OUTVAR} ".a" PARENT_SCOPE)
    endif ()
endfunction()

This function assumes that the target is well formed (ie. contains an arch-bits-os specifier). I'm mildly opposed to duplicating target parsing/validation code in the CMake rules.

slomp's issue would have been caught just as quickly if the generator executable had failed with an error message indicating that arch-bits-os or host was missing.

**Comment by steven-johnson** [comment]
> the generator executable had failed with an error message indicating that arch-bits-os or host was missing

SGTM
