### ISSUE TITLE
Poor Performance of GPU Auto-Scheduler

### ISSUE THREAD

**Issue by ArmageddonKnight** [halide/Halide#5079]
Hi,

I have been benchmarking the `apps/cuda_mat_mul` example in the `standalone_autoscheduler_gpu` branch. However, given below is the performance numbers that I got when I ran the `make test` command in the application folder:

| | Runtime (ms) |
|---|:---:|
| cuBLAS | 0.224 |
| Manual | 0.786 |
| Auto-Scheduler | 4.86 |
| Gradient Auto-Scheduler | 3.33 |

May I know whether I missed anything important in order for the GPU auto-scheduler to work, or is the GPU auto-scheduler still work-in-progress? Thank you for your help.

**Comment by abadams** [comment]
In short: That's essentially a randomly-generated schedule. There's no point in benchmarking that branch for any purpose right now.

The autoscheduler in that branch is a work in progress, and there are no checked-in general-purpose weights, so the schedule you get from "make test" is some arbitrary point in the space of all schedules currently being considered. Only the autotuning mode is functional right now, and it has been restricted to a subspace of all possible schedules while we get the cost model more accurate (and that subspace is actually a particularly bad one for mat_mul, because we're working on refining the modelling of shared memory so it's not allowed to put the accumulators in registers, which is essential for a good mat mul). So the autotuning mode isn't particularly meaningful for mat mul right now either.

**Comment by ArmageddonKnight** [comment]
@abadams Thank you for your reply. Could you please kindly tell me whether there is any existing GPU auto-scheduling example that we could use for benchmarking purposes?

**Comment by abadams** [comment]
Not really. The gradient autoscheduler is a strawman basic GPU autoscheduler but it's not very competitive. It's like a -O1 please run this on the GPU. I heard there's a good one coming out in TACO 2020 but it's not available online yet. If you're trying to do a comparison for a paper I'd focus on comparing to the manual schedules and Li's autoscheduler (the gradient autoscheduler).

**Comment by ArmageddonKnight** [comment]
@abadams Thanks again for your help.
