### ISSUE TITLE
[Hexagon DSP] How to fill static buffers created inside Halide

### ISSUE THREAD

**Issue by ImageHandler** [halide/Halide#5166]
Hi,
I want to use LUT (8x8) inside the generator. So I passed the ION buffer from DSP wrapper. Turns out I get 1.3 ms latency for the calculations using the LUT.
Now, I created a static halide buffer inside the Halide generator and used a static valued LUT. Something like :

```
static short LUT[8*8] = {1,2,3....,64 values}; //(the values are similar to those in the LUT buffer, but only they are now constant and assigned manually)
static Halide::Buffer<short> lut_halide(LUT);
```

I used lut_halide() instead of previous input buffer coming form input. Now the latency is reduced to 0.6 ms with bit matching.

The algorithm runs on many frames.
Now, what I want to do is, allocated 64 size buffer inside the Halide generator, and fill this memory with the input(LUT buffer) coming from the dsp wrapper on the first frame only (It is known that the LUT values are constant for every frame run). 

Benefit : now the latency might come 1.3 ms for the first frame calculations but will get reduced to 0.6 ms for the rest of the frames since I will be using the same stack memory.

However I am not able to achieve this. Please Help!

**Comment by abadams** [comment]
Are you sure it's because it's allocated differently and not due to some other reason (e.g. the LUT size is known at compile-time and so vlut instructions are getting used in one case but not the other)? I thought memory was memory once it was in the L2 on the dsp. 

Func::memoize lets you stash a compute_root Func over several runs of a pipeline, so you could try that. Start with the 1.3ms version that takes the lut as an input, then schedule the input like so:

```
lut_input.in().compute_root().memoize();
```

Not sure if the memoization cache is supported on hexagon, but if it is this should work.

**Comment by ImageHandler** [comment]
thanks @abadams , ran into some problem while compiling the generators : "computations which depend on buffer parameters cannot be scheduled compute_cached. Use memoize_tag to provide cache key information for buffer."
Also, there are not enough examples given to understand the halide keywords or halide APIs. Any place where I could get some help to utilize halide to a great extent?
