### ISSUE TITLE
CMake should forward variables to apps testing suite

### ISSUE THREAD

**Issue by shoaibkamil** [halide/Halide#5300]
This is on Windows.  If I use cmake to configure the build:

```
> cmake -DCMAKE_BUILD_TYPE=Release -G Ninja -DLLVM_DIR=d:/halide/llvm-install/lib/cmake/llvm -DHalide_TARGET=host-d3d12compute -DPNG_LIBRARY=<blah> -DPNG_PNG_INCLUDE_DIR=<blah>  ..\halide
```

And then I run `ctest --config Release -R bgu -VV`, the output shows:
```
...
563: Environment variables:
563:  HL_TARGET=host-d3d12compute
563: Test timeout computed to be: 10000000
563: Internal cmake changing into directory: D:/halide/halide-build-d3d12compute-issues/apps/bgu
563: ======== CMake output     ======
563: Halide detected active CMake target `x86-64-windows`
563: Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
563: Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
563: Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
563: Configuring done
563: Generating done
563: Build files have been written to: D:/halide/halide-build-d3d12compute-issues/apps/bgu
```

**Comment by abadams** [comment]
I was thrown for a bit by this. Clearly if the app is built separately, it shouldn't use Halide_TARGET from a build of libHalide. Would be weird if a cross-compiler had a preferred target it imposed on users. Building the apps as part of building libHalide is a bit weird IMO, and is what has lead to this. I guess we should probably plumb Halide_TARGET through to the sub-build. @alexreinking is the one who knows how.

**Comment by alexreinking** [comment]
@shoaibkamil -- is something actually _failing_ or is the output just misleading? The line:

```
563: Halide detected active CMake target `x86-64-windows`
```

is not connected to the `Halide_TARGET` environment variable. It's just reporting the base triple that corresponds to CMake's own target configuration (based on `CMAKE_SYSTEM_NAME`, `CMAKE_SIZEOF_VOID_P`, etc.). If it differs from the base triple of `Halide_TARGET`, then it will use some cross-compiling hacks, but otherwise plays nice.

That line is printed here:

https://github.com/halide/Halide/blob/f6c607b1e782680410c71abc5f2621ac7a32b420/cmake/HalideTargetHelpers.cmake#L45

And `Halide_TARGET` is forwarded to the apps here:

https://github.com/halide/Halide/blob/f6c607b1e782680410c71abc5f2621ac7a32b420/apps/CMakeLists.txt#L45-L49

**Comment by shoaibkamil** [comment]
Sorry, I should have been more explicit.  Something _is_ failing, in that I eventually get an error about PNG format not being supported.  I would've expected the apps to also get `PNG_LIBRARY` et al.

**Comment by alexreinking** [comment]
Ah, I use vcpkg for the image library dependencies and the vcpkg configuration _is_ forwarded to the apps. Do we have a full list of variables that need to be forwarded?

**Comment by shoaibkamil** [comment]
I think it would be the PNG, JPEG, and ZLIB dependencies, but those are the ones I was trying to forward, so I'm not sure it's comprehensive.  I ended up temporarily re-enabling vcpkg to work around this locally.

**Comment by alexreinking** [comment]
Actually, the right move might be to write your own toolchain file that sets those variables and load that via `-DCMAKE_TOOLCHAIN_FILE=...`. That would get forwarded to the apps.

**Comment by alexreinking** [comment]
This is invalidated by #5507
