### ISSUE TITLE
LLVM_LINK_LLVM_DYLIB and WebAssembly don't mix

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5471]
LLVM's build [has an option](https://releases.llvm.org/11.0.0/docs/CMake.html), `LLVM_LINK_LLVM_DYLIB`, which links "tools" to the _shared_ LLVM library. This is ludicrous and no one should use it because it will also link the _static_ lldWasm library to the _shared_ LLVM library. Yet, the Linux version of Homebrew _does_ use this.

Fortunately, the installed CMake files for LLVM tell you if this is the case: they will set `LLVM_LINK_LLVM_DYLIB` to something true-y (`ON` on my system). So the following three things cannot be true at the same time:

1. `TARGET_WEBASSEMBLY` is enabled
2. `LLVM_LINK_LLVM_DYLIB` is enabled
3. `Halide_SHARED_LLVM` is _disabled_

We should check for this and error out if it happens.

**Comment by alexreinking** [comment]
This is LLVM's fault even more than it is Homebrew's. They should set `LLVM` shared library and the `LLVM<Component>` static libraries to be _incompatible_ using CMake's built-in features for that.

https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#compatible-interface-properties

**Comment by steven-johnson** [comment]
The check we added turns out to prevent the prebuilts from apt.llvm.org from being used; they have LLVM_LINK_LLVM_DYLIB set, but if I remove the check, we seem to be able to build and run tests just fine. Do you recall the failure mode you were seeing?

...does anyone actually use the Linux version of Homebrew? (I thought it was Mac-only).
