### ISSUE TITLE
Conda-forge packages are stale

### ISSUE THREAD

**Issue by alexreinking** [halide/Halide#5609]
User @dfgreeve on Gitter reported a failure to use the autoschedulers from Halide. They had installed the `halide-python` package from Conda Forge. The listed maintainers are: @jrk, @minrk, and @steven-johnson.

Unfortunately, these packages are using the dated release prior to version 10. With version 11 around the corner, we ought to clean this up ASAP (even removing it is better at this point) so our prospective users don't get a bad first impression!

These are the conda-forge "feedstocks" (their word for "package") in question:

https://github.com/conda-forge/halide-python-feedstock
https://github.com/conda-forge/halide-feedstock

Related to #5360

**Comment by jrk** [comment]
I believe the halide-python package is reasonable, and the main trouble
with the halide package is that their CI infrastructure would always time
out while building LLVM as part of building that (and the conda default
LLVM package had no targets but host-native, which is not what you want for
Halide). But this is all from 2018 — it looks like these packages may have
been updated since then, so maybe there’s a way they can work well enough
with our standard binary releases?

Otherwise, we should indeed probably kill them. I’m not sure of the
process. Our own pip package, built atop the binary releases, is presumably
is the right place to focus efforts for now.

>

**Comment by steven-johnson** [comment]
I reviewed/approved this back then but did not write it originally; I will of course take a look if the original author isn't available but it will probably be slower as I'll have to get some background info retrieved from the back of my brain. 

I am not a regular Pythonista so I'm not sure about the use case of this vs a Pip package; if we can focus on the latter and drop this, I'd be in favor of it.

**Comment by jrk** [comment]
I was the original author, but @minrk was central to actually pulling this off. (But he shouldn't be penalized for his generosity. :)

The motivation here was that conda supports non-Python binary packages quite well, too, so this was a plausible environment for distributing Halide releases — not just Python packages. But I don't think it's the right place to focus for either at this point. (It's a maybe-nice-to-have but probably like 8th or 10th on our list of packaging targets, as long as we can deliver a good experience for most users with apt, Homebrew, pip, etc.)

The only thing I don't know is the conda-forge standards or processes for killing a package. Can we just do that unilaterally, no questions asked?

**Comment by alexreinking** [comment]
>  The only thing I don't know is the conda-forge standards or processes for killing a package. Can we just do that unilaterally, no questions asked?

I opened an issue on the feedstock. conda-forge/halide-feedstock#7

Hopefully someone will get back to us with further instructions.

**Comment by isuruf** [comment]
We have v19 packaged now. Hopefully we'll be able to keep up with the releases.

**Comment by alexreinking** [comment]
> We have v19 packaged now. Hopefully we'll be able to keep up with the releases.

Indeed! Closing this issue now
