### ISSUE TITLE
CMake Xcode generator appears broken

### ISSUE THREAD

**Issue by popizdeh** [halide/Halide#6167]
```
cmake_minimum_required (VERSION 3.16.0)

project (HalideExample)

set (CMAKE_CXX_STANDARD 17)
set (CMAKE_CXX_STANDARD_REQUIRED YES)
set (CMAKE_CXX_EXTENSIONS NO)

find_package(Halide REQUIRED)

add_executable (my_generators my_generators.cpp)
target_link_libraries (my_generators PRIVATE Halide::Generator)

add_halide_library (my_first_generator FROM my_generators)

add_executable (app main.cpp)
target_link_libraries (app Halide::Halide my_first_generator)
```

This seems to work just fine when using Ninja generator. It will produce `my_first_generator.o` and `my_first_generator.h` as well as `libmy_first_generator.a`. When using Xcode generator all I get are the first two files. Inspecting the generated project tells me that `app` executable depends on `libmy_first_generator.a` as well but this file is not present. I also see that `my_generators` executable is missing in this case...

So it feels like `my_generators` hasn't been built and run.

Any ideas?

**Comment by alexreinking** [comment]
I'm not sure anyone on the team uses Xcode, so this has likely never been tested before! If you find a fix, I would welcome a PR. Unfortunately, I don't have access to a mac desktop on which to test this.

**Comment by popizdeh** [comment]
From https://cmake.org/cmake/help/v3.21/command/add_library.html?highlight=add_library

"Some native build systems (such as Xcode) may not like targets that have only object files, so consider adding at least one real source file to any target that references $<TARGET_OBJECTS:objlib>."

The problem seems to be in `add_library("${TARGET}" STATIC ${generator_sources})` from `add_halide_library` as this only contains the object file produced by the `.update` target.

I'm not sure what the right way to fix this is as I don't get why there need to be 3 targets for each filter.

**Comment by alexreinking** [comment]
> I'm not sure what the right way to fix this is as I don't get why there need to be 3 targets for each filter. My guess is you're trying to leverage build system to get the native naming convention rather than producing the static library directly from the generator executable?

The runtime target exists for at least the first target, but can be reused with the `USE_RUNTIME` option. So there's only really two targets:

1. The custom target `${TARGET}.update` (an analogous one exists for the runtime, too). This exists as a convenience to run the generator from the command line if you just want to get the extra outputs and not bother with the linking step. It also protects against edge cases where the custom command (i.e. generator) might be run twice. It's generally safer to drive custom commands with a custom target and make dependent targets (like (2) below) depend on the custom target via `add_dependencies`.
2. The actual static library formed from the generated objects. We can't just spit out a static library from the generator because CMake needs to feel as though it did something useful (_ugh_) in order to make the generated library target first-class (i.e. installable, not `IMPORTED`).

---

I think a better solution would be something like the following:

```
if (CMAKE_GENERATOR STREQUAL "Xcode")
    # Xcode generator requires at least one source file to work correctly
    set(empty_file "${CMAKE_CURRENT_BINARY_DIR}/Halide_${TARGET}_empty.cpp")
    if (NOT EXISTS "${empty_file}")
        # Touching unconditionally would cause the archiver to re-run every time
        # CMake re-runs, even if nothing has actually changed.
        file(TOUCH "${empty_file}")
    endif ()
else ()
    set(empty_file "")
endif()
add_library("${TARGET}" STATIC ${generator_sources} ${empty_file})
```

**Comment by popizdeh** [comment]
Yeah, I realised quickly that file needs to go to binary directory. Making it Xcode specific also makes sense. Note that this needs to be done both for .update and .runtime target.

How do we get this in? I'm happy to test this for you if you want to open a PR and submit a patch?

**Comment by alexreinking** [comment]
> How do we get this in? I'm happy to test this for you if you want to open a PR and submit a patch?

Sounds good to me.

**Comment by alexreinking** [comment]
> Note that this needs to be done both for .update and .runtime target.

The `.update` target is a custom target and so doesn't have sources. What needs to be done here, exactly?

**Comment by popizdeh** [comment]
Sorry, I meant the static library target instead of .update.

**Comment by alexreinking** [comment]
@popizdeh - please see #6175 and confirm whether the patch works.

**Comment by popizdeh** [comment]
Legend!
