### ISSUE TITLE
Missing AVX2_znver3 target

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#6515]
It seems like the `-march=<>` is mimicked via target features,
in which case there's a large number of cpu's/features missing.
At the very least, i'd like to have one for znver3.

**Comment by LebedevRI** [comment]
Ok, so. Trying to think of the generalization here, and i have a general philosophy/design question.

As everyone knows, clang/gcc have three ways to control the target CPU:
* `-mattr=` - specify which features (ISA sets) to enable/disable
* `-mtune=` - without changing the enabled ISA sets, target this CPU
* `-march=` - both of the above

Now, there is only a single configuration method in halide, the features string, and features can only be enabled,
so there isn't much room to model all that flexibility, so i guess if the particular cpu is specified in the features,
it should mean both "target this cpu" and "tune for this cpu"? Or is there desire to be able to separate the two?

**Comment by LebedevRI** [comment]
Correction: in string form, we could have `target_cpu=ABC,tune_cpu=DEF`, that would be transparently stored as strings
in `Halide::Target`, IFF we are okay with not being able to configure them via `Target::set_feature()`/`Target::has_feature()`.

**Comment by abadams** [comment]
I'd rather just add lots more flags, honestly. The current flags are equivalent(ish) to mattrs. I have no objection to adding flags like Target::Zen3, or Target::IceLake. These flags would be used primarily by CodeGen_LLVM::mcpu() and would act like mtune.

If we want something like march instead, we could extend complete_x86_target in CodeGen_X86.cpp and do similar in other backends. That's where implied features get turned on (e.g. avx512 implies avx2). Should the target flag "SkylakeX" imply "avx512"? Quite possibly no, because it's a clock speed hit, so I guess that suggests the flags would have to be equivalent to mtune. But perhaps that's surprising... thoughts?

**Comment by LebedevRI** [comment]
Would be considered too disruptive to add `Target::{set,get}_{target,tune}_cpu(string)`?
I think my main worry is the fact that fixing #6514 will result in the CPU always being present in `Target`,
and going the full-flexibility route from the start might be less issue-prone.

**Comment by abadams** [comment]
It would be less disruptive to add more target flags, and we generally prefer enums to strings. I don't think the cpu always being present in a resolved "host" target is a bad thing. If anything it makes it clearer what's going on. We'd have to get a bit more clever with cpuid though.

**Comment by LebedevRI** [comment]
IF we can only add features, and presumably we don't want add two features per CPU,
then it would certainly have to be `-march=`, much like the existing ones (e.g. `AVX512_KNL`) already are.

**Comment by LebedevRI** [comment]
(i'm looking at x86 only.)
Ok, next question: do we want to do it right and have a feature for every single CPU that LLVM's X86 backend knows about,
or pretend that the CPU's without SSE2 support don't exist?

**Comment by abadams** [comment]
SSE2 is our baseline, so yeah, we should pretend microarchitectures without it don't exist.
