### ISSUE TITLE
Simplification of impure function

### ISSUE THREAD

**Issue by white-pony** [halide/Halide#655]
I've been looking into profiler for a little bit, in particular, I am trying different ways of measuring timer's overhead, so at some point I come up with the following code:
```c++
ticker_block = Block::make(
    Store::make(kIgnoreBuf,
        Add::make(
            Call::make(UInt(64), Internal::Call::profiling_timer, vector<Expr>(), Call::Intrinsic),
            Call::make(UInt(64), Internal::Call::profiling_timer, vector<Expr>(), Call::Intrinsic))
        , 0),
    ticker_block
);
```
which is intended to generate something like (and it does generate):
```c++
for (j, 0, 1000000) {
  $ignore_buf$[0] = (profiling_timer() + profiling_timer())
}
```
However, after all simplifications, it turns into:
```
for (j, 0, 1000000) {
  $ignore_buf$[0] = (let t1 = profiling_timer() in (t1 + t1))
}
```
which does not seem right to me, because of profiling_timer impurity. What do you think?

P.S. Just in case complete Profiling.cpp file to reproduce: https://gist.github.com/white-pony/3b260762be08ce230176

**Comment by abadams** [comment]
We assume all function calls are pure to simplify our analysis, because we
almost never have to handle ones that aren't. It's even worse that you
write, because we if tell llvm that the call is pure, then it'll lift the
call out of the loop entirely. I think we have a special-case for the
profiling timer to avoid this.

One way around these sorts of difficulties is to add a dummy argument that
uniquely identifies each call.

for j:
  ignore_buf[0] = profiling_timer(2*j) + profiling_timer(2*j+1)

On Tue, Feb 10, 2015 at 8:37 PM, Volodymyr Kysenko <notifications@github.com

**Comment by white-pony** [comment]
That's what I thought. This totally makes sense.

Sorry, but I did not get about special-case for profiler timer: I use one, is it something different?

Trick with dummy argument does work: do you think patch will be useful?

**Comment by abadams** [comment]
CodeGen.cpp lines 2204 - 2217 has some logic to at least tell LLVM that
certain functions are impure. It doesn't apply to our own common
subexpression elimination, but it stops llvm from lifting calls outside of
loops. The profiling timer is handled specially in CodeGen.cpp line 1931,
where it is also not marked as pure.

A patch that makes these calls have unique ids to prevent common
subexpression elimination would be welcome.

- Andrew

**Comment by white-pony** [comment]
Thanks for the explanation, it is clear now.

I'll send PR with this change.
