### ISSUE TITLE
We don't assert that all users of a Func are inside its compute_at

### ISSUE THREAD

**Issue by dvicini** [halide/Halide#679]
Hi,

I am quite new to Halide and currently just experimenting a bit before I start to work on my actual project. I tried implementing and optimizing a simple 1D gaussian blur. The code is fairy straightforward and should be correct, or at least the result I get looks alright. But when I tried to do some meaningful scheduling on it, suddenly the result does not look the same anymore. I've pasted the complete code at the end of this issue, but here is a short explanation what I tried to do: Without any scheduling, the code does recompute the gaussian weights for every pixel, which is quite slow. Therefore I tried to compute the weights in advance, before iterating over the pixel. The weights are calculated as follows (could this maybe be simplified?):
`RDom r(-sGaussianW, filter_size, "Filter Range");`
  `Func gWeights("Gaussian Weights");`
   `gWeights(x) = exp(-0.5f * x * x / (sigma * sigma));`
  `Func normalizationFactor("Norm factor");`
  `normalizationFactor() = 0.0f;`
   `normalizationFactor() += gWeights(r);`
   `Func normalizedWeights("Norm Weights");`
  `normalizedWeights(x) = gWeights(x) / normalizationFactor();`

I tried scheduling these calculations:
    `normalizedWeights.store_root().compute_root();`
  `normalizationFactor.store_root().compute_root();`
   `gWeights.store_root().compute_at(normalizationFactor, r);`

This should compute the non-normalized weights ("gWeights") and sum them up in one loop and then create the normalized weights in a second loop. The generated code however is not correct and gives the wrong output. Here is the relevant section as shown in the debug output:

```
allocate Gaussian Weights[float32 * 1]
allocate Norm factor[float32]
produce Norm factor {
    Norm factor[0] = 0.000000f
} update Norm factor {
    for (Norm factor.s1.Filter Range.x$r, -8, 17) {
        produce Gaussian Weights {
            Gaussian Weights[0] = exp_f32((((float32(Norm factor.s1.Filter Range.x$r)*-0.500000f)*float32(Norm factor.s1.Filter Range.x$r))*0.040000f))
        }
        Norm factor[0] = (Norm factor[0] + Gaussian Weights[0])
    }
}
allocate Norm Weights[float32 * 17]
produce Norm Weights {
    for (Norm Weights.s0.x, -8, 17) {
        Norm Weights[(Norm Weights.s0.x + 8)] = (Gaussian Weights[0]/Norm factor[0])
    }
    free Gaussian Weights
    free Norm factor
}
```

Instead of creating an array of unnormalized weights, the compiler does only store one weight in the "Gaussian Weights" array and does not allocate enough memory for 17 different weights. The resulting image filter then is just filtering all pixel with the same weight (the last which was stored in Gaussian Weight [0]). The Problem can be fixed by removing the last line from my scheduling, even though this adds complexity to this simple precomputation step. I am compiling using the latest Halide version for Windows x64. I did not get any other problems so far using Halide. I am really surprised that the scheduling in this case does change the output, I thought that should be impossible. Please let me know if I am doing anything wrong or if this is the right way to schedule this kind of operation and this is just a bug.

Complete code (image_io.h from the tutorials, same for the image file):

```
#define _CRT_SECURE_NO_WARNINGS
#include <Halide.h>
#include <stdio.h>
#include <algorithm>

using namespace Halide;

// Support code for loading pngs.
#include "image_io.h"

int main(int argc, char **argv)
{
    const float sigma = 5.0f;
    const int sGaussianW = (int) ceil(1.5 * sigma);
    const int filter_size = 2 * sGaussianW + 1;

    Image<uint8_t> input = load<uint8_t>("images/rgb.png");

    Var x("x"), y("y"), c("c");
    // clamp and normalize to [0, 1]
    Func clamped("Clamped");
    clamped(x, y, c) = input(clamp(x, 0, input.width() - 1), clamp(y, 0, input.height() - 1), c) / 255.0f;

    // reduction domain for filter
    RDom r(-sGaussianW, filter_size, "Filter Range");

    // 1D gaussian weights function
    Func gWeights("Gaussian Weights");
    gWeights(x) = exp(-0.5f * x * x / (sigma * sigma));
    Func normalizationFactor("Norm factor"); 
    normalizationFactor() = 0.0f;
    normalizationFactor() += gWeights(r);
    Func normalizedWeights("Norm Weights"); 
    normalizedWeights(x) = gWeights(x) / normalizationFactor();

    Func accumulate("accumulate");
    accumulate(x, y, c) = 0.0f;
    accumulate(x, y, c) += normalizedWeights(r) * clamped(x + r, y, c);

    Func gaussian("Gaussian");
    gaussian(x, y, c) = cast<uint8_t>(255 * accumulate(x, y, c));

    // Scheduling
    normalizedWeights.store_root().compute_root();
    normalizationFactor.store_root().compute_root();
    gWeights.store_root().compute_at(normalizationFactor, r); // <-- problematic line

    //gaussian.compile_to_c("test.cpp", std::vector<Argument>(), "gaussian");

    Image<uint8_t> output = gaussian.realize(input.width(), input.height(), input.channels());
    save(output, "gaussian_blurred.png");
    printf("Success!\n");
    std::getchar();
    return 0;
}
```

**Comment by abadams** [comment]
This is an interesting bug, but unfortunately the bug is a missing error
message. Your schedule describes something that a person might very
reasonably want to do, but it's not actually expressible in Halide. We
require that all users of a Func be inside of that Func's compute_at level.
This is not the case with your schedule. It looks like this slipped through
our checks and caused mistakes later in lowering (*). It looks like we're
erroneously only checking that all the users of a Func are inside its
store_at level.

I think gWeights.compute_root() is the closest legal thing to what you want.

Here's the longer explanation of why we require all users of a Func to be
inside its compute-at level, instead of just the store_at level. Consider
the following pseudocode:

allocate f {
 for g.x {
  compute f
  g(g.x) = f(...)
 }
 for h.x {
  h(h.x) = f(...)
 }
}

g and h both use f. f is scheduled as f.store_root().compute_at(g, x)

This schedule will only work if by the time we get to computing h, enough
of f has been computed to satisfy h's use of it. Did we do this? We
computed enough of f to satisfy g's use of f. In case that wasn't enough,
we could inject another computation of f inside h.x, but a Func only has
one compute_at location, and even if it could have multiple this might do a
bunch of redundant work.

Perhaps we can just assert that enough of it has already been computed in
the loop over g.x (as would be the case in your example). To do that we'd
have to prove that the region of f used in h's loop over x is within the
region of f computed in g's loop over x. We only have one tool to determine
the bounds read or computed of something - interval arithmetic - and it's
conservative in the wrong direction. We can prove that the region computed
is at *most* some box, but we can't prove that it's at *least* some box.
Even if we have a tight bound, we can't easily prove it covered absolutely
every point in the region. This is not impossible to do (for simple cases
at least), but it's not a tool we have.

Thanks for the bug report.

**Comment by dvicini** [comment]
Thanks for the quick reply!

I understand. I guess gWeights.compute_root is indeed the closest to what I need. (if it were performance critical I could still write an external C function).

**Comment by abadams** [comment]
This schedule may actually be better, because it allows for vectorization
of the weight computation (our exp is an approximate vectorizable thing).

**Comment by dsharletg** [comment]
I'm guessing this was fixed at some point.
