### ISSUE TITLE
CMake should have an `add_halide_runtime()` rule

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#6981]
Currently we don't have a clean way to add a Halide Runtime library without a Generator attached; we should really consider adding one, because:
- Advanced users could use it to reduce redundant build time (since Generators default to produce their own bespoke runtimes, even when identical)
- `add_halide_python_extension_library()` requires all participating targets to have *identical* runtimes, which is unpleasantly hackish at present

**Comment by steven-johnson** [comment]
@alexreinking Is this as simple as making `_Halide_add_halide_runtime` a public, documented rule, or is there more tweaking that would be needed?

**Comment by alexreinking** [comment]
There is more tweaking because `_Halide_add_halide_runtime` needs an existing generator to work. To make this a good, public-facing feature, we need to bundle an empty gengen binary tool like `halide-gengen[.exe]` to make it possible to, say, call `add_halide_runtime` before creating any other generators.
