### ISSUE TITLE
When/If should we deprecate support for x86-32?

### ISSUE THREAD

**Issue by abadams** [halide/Halide#7047]
llvm 16 no longer tests building on x86-32 (on linux at least), which means JIT isn't guaranteed to work, and neither will our tests. 

I can't imagine any remaining Halide use for x86-32, so I propose that we mark x86-32 as deprecated in Halide 15, and drop support for it in Halide 16. 

I'm opening this as an issue to see if there are uses for Halide on x86-32 that I'm not thinking of. E.g. is anyone using the JIT from inside a win-32 process? Or running emulated x86-32 Halide-generated code on Windows ARM machines?

**Comment by steven-johnson** [comment]
> llvm 16 no longer tests building on x86-32 

To be clear: I don't have *confirmation* of this from anyone at LLVM. I do know that recently code that won't even compile on x86-32-bit builds was checked in successfully, and (AFAICT) Halide was the only group to notice or complain. (I've open an inquiry to clarify whether this was intentional or oops-we-messed-up)

**Comment by zvookin** [comment]
We should get clarification from LLVM on the status of x86_32/arm32. Both are fairly widely used in embedded work. In as much as Halide supports embedded use cases and things like firmware development, the timeframes for deprecating such support are pretty long. More like a decade than a year. LLVM deprecating 32-bit would probably push us to support longer backward compatibility for LLVM versions.

32-bit is capable enough that many use cases will never need more. And low power is important enough that it is likely worth the savings. RISC V is doing 32-bit support fully due to this, despite that it would obviously be easier to standardize on 64-bit only.

**Comment by steven-johnson** [comment]
To be clear, there's no evidence at all that LLVM is considering dropping the *generation* of x86-32; there is some question as to whether LLVM is being tested *running* on x86-32. 

We could continue to support x86-32 and arm32 codegen as long as LLVM does, with the (giant) caveat that our test suite need to be rewritten to avoid relying on JIT, for obvious reasons.

**Comment by zvookin** [comment]
Removing the JIT requirement for tests is desirable for other reasons. But to move the question forward, JIT and 32-bit might not be required. Halide could likely be AOT only for embedded.

**Comment by abadams** [comment]
I know arm-32 is still important in embedded, but is x86-32 really used? Intel's Atom chips have been 64-bit since ~2010.

**Comment by steven-johnson** [comment]
It's a good question. For new projects/code, probably not. (IIRC, Windows-on-ARM will emulate x86-32 but not x86-64, in which case demand for maintaining existing stuff will definitely continue even longer than expected.)

**Comment by abadams** [comment]
llvm fixed their build and Ryan Stout on gitter states that they're actively using Halide for x86-32, so let's put a pin in this.
