### ISSUE TITLE
Vague assertion failure in FuseGPUThreadLoops

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7076]
Take the following (contrived, apparently-illegal) schedule example:

```
    ImageParam im(Float(32), 2);

    Func a, b;
    Var x, y;

    a(x, y) = im(x, y);
    b(x, y) = a(x, y);

    Var xi, yi;
    b.gpu_tile(x, y, xi, yi, 4, 4);
    a.compute_at(b, y).gpu_tile(x, xi, 4);

    b.realize({32, 32}, Target("host-metal"));
```

This will fail with something like

```
Internal Error at FuseGPUThreadLoops.cpp:60 triggered by user code at :
Condition failed: !block_count[dim].defined():
```

It's not clear to me whether this schedule is illegal (and the issue is that the assertion needs to be more helpful about why), or whether it should be legal (but the code in `ExtractBlockSize` isn't correct).

**Comment by abadams** [comment]
The bug is a missing error message. gpu_tile makes an outer (potentially multi-dimensional) blocks loop and an inner (potentially multi-dimensional) threads loop. If you're compute_at another Func's GPU blocks loop, you must be compute_at the innermost such loop, and you can't have your own GPU blocks loop. This corresponds to computing the Func in the same cuda/metal kernel and transmitting results via shared memory. So the legal schedules for `a` are:

```
// Compute in a separate kernel
a.compute_root().gpu_tile(...);
// Compute within b's kernel but with it's own threads loop, transmit results via shared memory
a.compute_at(b, x).gpu_threads(x, y);
// Compute as needed per thread within b's kernel. Roughly equivalent to inlining it.
a.compute_at(b, xi);
```
