### ISSUE TITLE
Python Generators rearrange input and output arguments silently

### ISSUE THREAD

**Issue by Copper280z** [halide/Halide#7669]
It appears that python generators will rearrange inputs and outputs so that in the generated function call all input arguments come first, then output arguments, even if this is not the order defined in the generator class.

This may be intended behavior, but I can't find it called out anywhere in the examples or documentation, and it seems to me like an unintuitive result. It seems like either an addition to the documentation or a more descriptive error message would be a helpful addition. I think this would be caught more readily in a C++ setting because of static typing, Python tools can't easily catch this problem because it's dynamically typed. It's also not immediately obvious to me how to inspect the code generated by a generator, but I've only spent a few minutes looking.

Minimal example:
```
import numpy as np
import halide as hl

x = hl.Var("x")
y = hl.Var("y")

@hl.generator(name="testgen")
class testgen(hl.Generator):
    output = hl.OutputBuffer(hl.UInt(8), 2)  # output defined first
    offset = hl.InputScalar(hl.UInt(8))  # input defined second
    
    def generate(self):
        self.output[x,y] = self.offset


if __name__ == "__main__":
    inp = 3
    out = np.empty((256,256), dtype=np.uint8)
    t = hl.Target("host")
    with hl.GeneratorContext(t):
        gen = testgen()
        
        test_filter = gen.compile_to_callable()
        
        test_filter(inp, out)  # <- this works
        
        test_filter(out, inp)  # <- this fails

```

result:
```
  File ...example.py:26
    test_filter(out, 3)  # <- this fails

HalideError: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

**Comment by abadams** [comment]
@alexreinking @steven-johnson is there some way to make this an error? I'm not sure if you can introspect on member ordering.

**Comment by steven-johnson** [comment]
To clarify: does this only happen with `compile_to_callable()`? (i.e., when using the JIT, rather than AOT compilation?)

**Comment by steven-johnson** [comment]
OK, for now I am assuming that the issue here is specifically with `compile_to_callable()`, rather than AOT compilation.

The behavior you are seeing is (currently) working as intended, but is definitely not documented properly. The rules for argument ordering for a Callable (in both C++ and Python) are:

- First, the inputs you specified directly in source, in the order you specified
- Then, any additional inputs added via the `configure()` method
- Then, the outputs you specified directly in source, in the order you specified
- Then, any additional outputs added via the `configure()` method

This decision was informed by the encouraged-but-not-required coding guideline that all Inputs in a Generator should come before any Outputs, but, as you noticed, was not properly documented.

So there are several issues here:
- This choice of ordering is fairly arbitrary; we could change it, but we'd need to decide what ordering to use (and in particular, how to order things added by `configure()`). Of course, changing this order would break existing code, so we'd need to find a way to migrate to it.
- Obviously the documentation for both C++ and Python code needs to be revised to make the ordering choices much more explicit, but before I update that, we need consensus on what the right ordering is. 

If we decide to change the ordering, then presumably the most likely ordering would be (order listed in source) followed by (order added by `configure()` method), regardless of whether argument is input or output. I could live with this style (though IMHO it doesn't fit well with most existing Halide usage), but again, we would need to work out a way to transition existing code to avoid breakage.

>  I think this would be caught more readily in a C++ setting because of static typing

FWIW, this "error" isn't actually going to be much more obvious in C++, because the techniques we use in C++ effectively subvert the type system in favor of quick runtime checks (unless you use `Callable::make_std_function`, which makes this cleaner).

**Comment by abadams** [comment]
I was thinking we'd just make it an error to have Output members before Input members in the generator class. I.e. enforce the existing convention.

**Comment by steven-johnson** [comment]
> I was thinking we'd just make it an error to have Output members before Input members in the generator class. I.e. enforce the existing convention.

We could do that too, but (again) that will probably break someone's existing usage -- we need to decide whether to just make it a breaking change or not.

**Comment by abadams** [comment]
We could add a warning for Halide 17 that notifies the user than the argument order to the aot entrypoint isn't going to match the declaration order in the generator class, and that this behavior will be an error in Halide 18. That would have solved the silently-did-the-wrong-thing behavior in the issue.

**Comment by steven-johnson** [comment]
@Copper280z would appreciate your feedback here :-)

**Comment by Copper280z** [comment]
Whoops, sorry!

My view is that most every behavior is acceptable, so long as it's documented and expected. Ideally if you use something wrong, the error points you towards why it was wrong. :)

I think enforcing the current condition with a warning on generator instantiation for the next version, then an error should be totally acceptable. (At least for the python interface, I have very little experience with C++ conventions for things like that.) That would have caught it for me. A copy and paste of your explanation on ordering, or link to this issue in the python readme might also be appropriate?

I didn't try this with an AOT compilation, but I can give it a shot and see. Being unfamiliar with the behind the scenes differences, I would assume the behavior would be identical between the two?

**Comment by steven-johnson** [comment]
> I think enforcing the current condition with a warning on generator instantiation for the next version, then an error should be totally acceptable.

Cool, that's what I'll do.

> I would assume the behavior would be identical between the two?

That's what I would hope, but at the moment I can't swear to it :-)

**Comment by steven-johnson** [comment]
I have confirmed that what I reported earlier regarding the expected ordering of all arguments is in fact consistent across both AOT and JIT, and also across Python and C++. So I propose the following to address this:

- Add more explicit documentation about this ordering.
- Add checks that all predeclared Inputs in a Generator come before any predeclared outputs
  - For Halide 17, violating this will produce a warning that the argument order won't match, and that this behavior will be forbidden in the future
  - For Halide 18, violating this will be a compilation error

I don't think it's worth trying to add any sort of checking for inputs/outputs added by `configure()`, because (1) it's an unusual corner case, and (2) I'm not sure what of useful checking is even possible here.

Sound ok?
