### ISSUE TITLE
bounds-query can quietly return wrong answer when specialize_fail() is used

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7756]
The scenario: we have code that does a bilinear resize, with specialize() for various channel counts, planar/chunky options, etc.

While tweaking the schedule, `specialize_fail()` was added at the end, to avoid codegen for unsupported specialize options; after this was done, bounds-query mode starting failing when this function was used for `define_extern()`: it doesn't return an error code, but it just quietly gives bogus results (generally, all-zero bounds). I'm assuming this is because the `define_extern()` case passes in bounds that have `stride=0` for all dimensions (which is an unsupported case after this change).

If I remove the specialize_fail(), or call bounds-query with supported stride values, things work correctly.

**Comment by abadams** [comment]
I think it's because bounds query needs a second pass in this instance, and define_extern doesn't support that. In the first bounds query call, it doesn't see any explicit constraints on the stride (i.e it just sees .dim(0).set_stride(Expr())), so it thinks it can be anything and sets it to one by default. In the same pass it learns nothing about the extent, because the extent required depends on what the actual stride ends up being, and at the time of the call the actual stride is zero. Given a stride of zero, the input isn't touched at all, so an extent of zero is fine.

So in general bounds queries can require multiple passes, and pipelines that require multiple passes aren't supported by define_extern, but it's hard to detect that so it's hard to give an error message that says that.

I think there's a fix in this case though. To get the region required of the input, we use boxes_touched. boxes_touched already implicitly assumes that all asserts pass. If it sees:
```
assert(f.dim(0).stride() == 2);
f[17];
```
Then it returns that f is unconditionally touched at position 17, ignoring the fact that if the assert fails, we're not going to access f at all. This is fine, because boxes_touched is conservative. It's allowed to claim accesses that don't actually happen.

However given the following code: 
```
if (f.dim(0).stride() == 2) {
  assert(false);
} else {
  f[17];
}
```
It respects the if statement and returns that f is accessed at 17 provided that f.dim(0).stride() != 2. 

This is also a correct reply, but this is clearly weird, because the two pieces of code are actually equivalent, and we're no longer assuming that asserts pass (under that assumption, we can assume the assert(false) is unreachable). I think we *want* boxes_touched to conservatively assume asserts pass, because we get more useful bounds that way without requiring multi-pass shenanigans.

I can't make it do this perfectly, because that 'false' could always be something not statically detectable as false like 'there is a counter example to FLT'. I can't even make it assume that any branch with an assert(false) in it isn't taken, because we might have code like this:
```
if (f.dim(0).stride() == 2) {
  f[9999];
  assert(false);
} else {
  f[17];
}
```
and for that code we want the assert to fail rather than getting a segfault on f[9999].

What I *can* do however is conservatively take a union, and assume the else branch is unconditionally taken if the then branch contains an assert(false) (and vice-versa). So the region touched would be [17, select(f.dim(0).stride() == 2, 9999, 17). That should work out cleanly in the specialize_fail case, because the conditionally-taken branch doesn't access any buffers anyway.
