### ISSUE TITLE
Missing potential optimizations when input/output buffers are constant extents

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#7761]
If you explicitly constrain a Generators input buffer extents to specific values (eg we know that `input_k` is always 128x16, so we do `input_k_.dim(0).set_extent(128).dim(1).set_extent(16);` 

- we *do* inject the correct assertions to verify that, but... 

- we don't seem to propagate those constants elsewhere, e.g. when calculating extents of intermediate Func that are based on that, e.g. `let O_block.s1.y.max = let t283 = min(input_k.extent.1, 16) in max(-1 - t283, max(t283, 1) + -1)` [hey, we know that input_k.extent.1 is a constant!]
 
- we still get (redundant) assertion  checks that `input_k.min.1` is in range (in addition to the must-be-exact-value check),

**Comment by abadams** [comment]
This is explicitly handled here: https://github.com/halide/Halide/blob/main/src/AddImageChecks.cpp#L242

I suspect there's something unique about your specific case.

**Comment by steven-johnson** [comment]
Try generating stmt from this example:

```
class Foo : public Halide::Generator<Foo> {
 public:
  Input<Buffer<float, 2>> input_1_{"input_1"};
  Input<Buffer<float, 2>> input_2_{"input_2"};

  Output<Buffer<float, 2>> output_{"output"};

  void generate() {
    // Note that due to the constraints below,
    // we should always know W=128, H=16
    Expr W = input_1_.dim(0).extent();
    Expr H = input_1_.dim(1).extent();

    Expr BlockWidth = 16;
    Expr BlockHeight = min(BlockWidth, H);

    Expr BlockCols = cast<int>(round(W / BlockWidth));
    Expr BlockRows = cast<int>(round(H / BlockHeight));

    Var x{"x"}, y{"y"}, i{"i"}, j{"j"};

    RDom ij(1, BlockRows, 1, BlockCols, "ij");

    Func b1{"b1"};
    b1(x, y, i) = input_1_((i-1) * BlockHeight + x, y);

    Func b2{"b2"};
    b2(x, y, j) = input_2_((j-1) * BlockWidth + x, y);

    Func b3{"b3"};
    b3(x, y, i, j) = b1(x, y, i) + b2(x, y, j);

    output_(x, y) = b3(x % BlockWidth, y % BlockHeight, x / BlockWidth, y / BlockHeight);

    // Schedule
    b1.compute_root();
    b2.compute_root();
    b3.compute_root();
    output_.compute_root();

    // Constraints: all buffers are 128x16
    input_1_.dim(0).set_min(0).dim(1).set_min(0);
    input_2_.dim(0).set_min(0).dim(1).set_min(0);
    output_.dim(0).set_min(0).dim(1).set_min(0);

    input_1_.dim(0).set_extent(128).dim(1).set_extent(16);
    input_2_.dim(0).set_extent(128).dim(1).set_extent(16);
    output_.dim(0).set_extent(128).dim(1).set_extent(16);

    output_.bound(x, 0, 128).bound(y, 0, 16);
  }
};
```

The dimensions of b1, b2, and b3 should be inferrable as constants at compile time, but instead, we get (eg)

```
let b3$0.s0.j.min = select(0 < input_1.extent.1, 0, 15/min(input_1.extent.1, 16))
let b3$0.s0.y.max = let t98 = min(input_1.extent.1, 16) in max(-1 - t98, max(t98, 1) + -1)
```

**Comment by steven-johnson** [comment]
> This is explicitly handled here: https://github.com/halide/Halide/blob/main/src/AddImageChecks.cpp#L242

It injects constraints for the input and output buffers, but doesn't seem to use those constraints to simplify the bounds (etc) of intermediate funcs.

**Comment by abadams** [comment]
It does use those bounds to simplify the entire rest of the pipeline after the assert. Our lowered code goes like this:

1) Compute the bounds required of all compute_root Funcs as a function of the output shape. Any constraints on the output buffer shape are respected (Normally, bounds on intermediate Funcs only depend on the output shape).
2) Use the inferred bounds of Funcs to compute what actual regions of the input buffers get read.
3) Compare those against the actual shape of the input buffers, and compare those shapes against any constraints. Any constraints are then exploited in the rest of the pipeline to simplify and constant fold.

The issue in this case is that the shape of one of the inputs is leaking into a bounds inference expression in step 1, due to the use of the input size in a bounds-affecting way, and this is before any asserts are checked, so it's before it's safe to make any assumptions about what those values are. We might need to move the constraint-checking asserts earlier, or convince ourselves that it's safe to exploit the constrained value before we actually check the constraint (this sort of anti-causal assert exploitation can potentially cause asserts to incorrectly pass if the value that exploits the constraint is one that feeds into the checking of the constraint itself).
