### ISSUE TITLE
vectorize loops triggers name not in scope error

### ISSUE THREAD

**Issue by TH3CHARLie** [halide/Halide#7779]
A simple repro:
```cpp
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Var x("x"), y("y"), yo("yo"), yi("yi"), yoi("yoi"), yoio("yoio"), yoii("yoii");
    Func f("f");
    f(x, y) = x + y;
    f.split(y, yo, yi, 8, TailStrategy::Auto).split(yo, yo, yoi, 4, TailStrategy::RoundUp).vectorize(yoi).vectorize(yi).split(yoi, yoio, yoii, 2, TailStrategy::Auto);
    Pipeline p({f});
    std::cout << "before realize\n";
    Buffer<int> buf = p.realize({128, 128});
    std::cout << "realize done\n";
    return 0;
}
```

This code will trigger the following internal error under `HL_DEBUG_CODEGEN=2`
```
Vectorizing...
Subcontext threw exception. Rethrowing...
Internal Error at /home/xuanda/dev/Serializer/Halide-clean/src/Scope.h:134 triggered by user code at : Name not in Scope: f.s0.y.yo.widened.f.s0.y.yi
{
  f.s0.y.yi.base.widened.f.s0.y.yo.yoi.yoii
  f.s0.y.yo.widened.f.s0.y.yo.yoi.yoii
}
```

**Comment by abadams** [comment]
Something is going wrong in VectorizeLoops.cpp. The IR before vectorization is this:

```
  for (f.s0.y.yo.yoo, 0, (f.extent.1 + 31)/32) {
   vectorized (f.s0.y.yo.yoi.yoio, 0, 2) {
    vectorized (f.s0.y.yo.yoi.yoii, 0, 2) {
     let f.s0.y.yo = (f.s0.y.yo.yoo*4) + ((f.s0.y.yo.yoi.yoio*2) + f.s0.y.yo.yoi.yoii)
     let f.s0.y.yi.base = min(likely_if_innermost((f.s0.y.yo*8) + f.min.1), (f.extent.1 + f.min.1) + -8)
     vectorized (f.s0.y.yi, 0, 8) {
      for (f.s0.x, f.min.0, f.extent.0) {
       f[(((f.s0.y.yi + f.s0.y.yi.base)*f.stride.1) + f.s0.x) - ((f.min.1*f.stride.1) + f.min.0)] = (f.s0.y.yi + f.s0.y.yi.base) + f.s0.x
      }
     }
    }
   }
  
```

Note the let of f.s0.y.yo. The RHS depends on some vectorized vars, so it's a vector, but it's defined outside the innermost vectorized loop. vectorized lets are added to a vector_scope with a name determined by the original name + ".widened." + the name of the enclosing vectorized loop var. Lookup under this name fails inside the loop over f.so.y.yi, because the enclosing vectorized loop var is different.

The problem is that I don't understand *why* the name is tagged with the enclosing vectorized loop var. I think it must be related to the multiple vectorization work done by @vksnk, so maybe he can take a look?

**Comment by vksnk** [comment]
Yes, looks like a bug with the nested vectorization, I'll take a look.
