### ISSUE TITLE
Massive unroll leads to block visitor stack overflow

### ISSUE THREAD

**Issue by TH3CHARLie** [halide/Halide#7824]
Discovered by an unintended exploration in the fuzzer, usually don't expect anyone actually write schedules like this. The schedule below starts with unrolling the y dimension and follows by splitting it multiple times, causing all the child vars unrolled. It will create a massive Block node and the recursive visit will stack overflow. 
```
    Func input("input");
    Func local_sum("local_sum");
    Func blurry("blurry");
    Var x("x"), y("y");
    input(x, y) = 2 * x + 5 * y;
    RDom r(-2, 5, -2, 5);
    local_sum(x, y) = 0;
    local_sum(x, y) += input(x + r.x, y + r.y);
    blurry(x, y) = cast<int32_t>(local_sum(x, y) / 25);
    Var xo("xo"), xi("xi");
    Var x_outer("x_outer"), x_inner("x_inner"), yo("yo"), yi("yi");
    Var yoo("yoo"), yoi("yoi"), yooo("yooo"), yooi("yooi");
    Var yoooo("yoooo"), yoooi("yoooi"), yooooo("yooooo"), yooooi("yooooi"), yooio("yooio"), yooii("yooii");
    local_sum.unroll(y).split(y, yo, yi, 8, TailStrategy::PredicateStores).unroll(x).split(yo, yoo, yoi, 8, TailStrategy::Auto).split(yoo, yooo, yooi, 2, TailStrategy::Auto).split(yooi, yooio, yooii, 8, TailStrategy::Auto).split(yooo, yoooo, yoooi, 8, TailStrategy::Auto).split(yoooo, yooooo, yooooi, 8, TailStrategy::PredicateStores);
    local_sum.update(0).unscheduled();
    Pipeline p({blurry});
    Buffer<int> buf = p.realize({32, 32})
```

**Comment by TH3CHARLie** [comment]
Given previous experience in https://github.com/halide/Halide/issues/7759, we suspect this schedule would eventually crash LLVM as well

**Comment by abadams** [comment]
As a workaround, you can set HL_COMPILER_STACK_SIZE to something larger than the default. After all, it's just address space. This test passes for me with a 32MB stack (turns out llvm can handle this case).

A potential improvement for this sort of case is to change the Block IR node to have a vector of Stmts instead of just a first and a rest, to force all Block visitors and mutators to be non-recursive. It's possible to be non-recursive with the current Block node with a while loop, but the base class IRMutator has to be recursive to support potentially recursive child class mutators, and sometimes even the base class mutator can overflow the stack. The hard part of this task would be rewriting the simplifier block visitor, which is where this specific case overflows.

There are always going to be valid schedules that we can't compile in practice, because you can unroll arbitrarily large loops and we'll run out of memory, whether it's the stack or the heap.
