### ISSUE TITLE
Cross-Platform compiling of Halide (Linux->Windows)

### ISSUE THREAD

**Issue by tz-reinberger** [halide/Halide#7835]
I am currently trying to get a halide program compiled for a Windows target on a linux host.
However, this is proving to be rather difficult.
For reference, I have already successfully built Halide programs:
- for Windows x86_64, on Windows x86_64: using MSVC (release mode) and the pre-built binaries (from the releases tab)
- for Linux x86_64 on Linux x86_64: using G++ or CMAKE and the pre-built binaries
- for Linux ARM64v8 on Linux ARM64v8 : using G++ or CMAKE and the pre-built binaries

I have already tried (on Linux x86_64):
- building with minGW and linking to the pre-built binaries -> does not work because the pre-built binaries are probably built with MSVC and thus incompatible
- building Halide with VCPKG -> does not work because 'Use of Visual Studio's Developer Prompt is unsupported on non-Windows hosts.' (It would probably not produce minGW compatible binaries anyway)

What are my options?
I have read that minGW support was dropped for Windows (https://github.com/halide/Halide/issues/7503#issuecomment-1507289832), so is it currently possible to build for Windows on Linux?
I could compile LLVM for Windows on Linux using a modified MXE (https://github.com/mxe/mxe) makefile, same for the other dependencies.
But I wonder if it is possible to build Halide itself with minGW, even with all the dependencies in place.

**Comment by abadams** [comment]
I'm going to assume you're using Halide as an AOT compiler, because JIT compiling code for windows on a linux host doesn't really make sense.

When using Halide as an AOT compiler, the static libraries generated by libHalide when compiling for windows on windows should be identical to the static libraries generated when compiling for windows on linux. There's no dependence on the host system in the output. So you should be able to compile a static library out of any functioning build of Halide on linux and link that in to an msvc project and perform the rest of the build of your program on windows. There's no reason I can think of to try to use a windows or mingw build of libHalide on a linux system. For the stuff where we're in control of compilation, Halide is a full cross compiler.

It seems like the core problem is that there's no way to build the non-Halide-generated parts of your windows program on a linux host without using mingw, and Halide doesn't support mingw as a compilation target, so you can't link the Halide-generated static libraries to the rest of your program. Not supporting mingw as a compilation target mostly means that our runtime doesn't use mingw-appropriate syscalls for things like threading primitives. The only path of can think of is compiling your Halide-generated static libraries with the -no_runtime target flag and then providing your own mingw-compatible implementations of things like halide_do_par_for.

I hope that's somewhat helpful - I don't entirely understand what you're trying to do.

**Comment by tz-reinberger** [comment]
Reading through my initial post again, it seems I missed explaining what exactly I am trying to build.

I want to compile lesson_01.cpp (https://halide-lang.org/tutorials/tutorial_lesson_01_basics.html) for Windows on Linux.
So the program would run the JIT compiler for actual Halide language code/computation on Windows, but I want to build the Windows executable (.exe) on Linux.
I cannot compile lesson_01.cpp with MinGW and link against the pre-built binaries from the releases (Halide.lib), since that one is incompatible to MinGW as far as I know, because the Halide.lib from the releases tab was built with MSVC.

My question is, what do I have to do in order to be able to compile lesson_01.cpp on my Linux box for a Windows target, producing an executable file that i can put in a folder with Halide.dll and run on Windows.
Just running on Windows would be my first priority, running with GPU support my second priority.
I reckon I have to compile the Halide library from source using MinGW, to create a Halide.lib and Halide.dll as well as headers that I can use to compile lesson_01.cpp with MinGW.
Is that possible?
Has it been done before?

**Comment by AngryLoki** [comment]
> since that one is incompatible to MinGW as far as I know, because the Halide.lib from the releases tab was built with MSVC.

I think you are right. Not only released Halide.lib works only with MSVC, it works there _only in release mode_ (#6180).

What you suggested sounds possible, you should start with building static LLVM libraries as described at https://llvm.org/docs/HowToCrossCompileLLVM.html. But I'm not sure the effort is worth the time spent. It looks easier to just run MSVC in VM.

**Comment by abadams** [comment]
I agree with running MSVC in some sort of VM. I don't think using Halide as a JIT compiler is going to work well if it's compiled under MinGW, because presumably that means you're getting things like MinGW's math library, which Halide's JIT runtime doesn't understand (e.g. see the runtime code that was removed from Halide in #4601)

**Comment by tz-reinberger** [comment]
> I don't think using Halide as a JIT compiler is going to work well if it's compiled under MinGW, because presumably that means you're getting things like MinGW's math library, which Halide's JIT runtime doesn't understand (e.g. see the runtime code that was removed from Halide in #4601)

I see. Building it with MSVC seems like the only reasonable option then. It would also mean I could link against pre-built binaries, which is excellent.

**Comment by tz-reinberger** [comment]
I have now successfully built lesson_01.cpp in Linux x86_64 for Windows x86_64 with MSVC.
Just in case more people are interested in making the Windows build on Linux, here is how to do it:
- use [msvc-wine ](https://github.com/mstorsjo/msvc-wine )@9c6af53 (the Docker approach) for the build environment and follow the guide for CMake (I used the [CMake 3.27.3 binaries](https://github.com/Kitware/CMake/releases/tag/v3.27.3))
- In short, set these enviroment variables as such: 
```
CC="cl"
CXX="cl"
PATH="/opt/msvc/bin/x64/:$PATH"
```
and call cmake with the flags 
```
-G Ninja
-DCMAKE_MSVC_DEBUG_INFORMATION_FORMAT=Embedded
-DCMAKE_BUILD_TYPE=Release
-DCMAKE_SYSTEM_NAME=Windows 
```
- get the Halide binary zip from the releases. I have used Version [15.0.0](https://github.com/halide/Halide/releases/tag/v15.0.0).
- set the `Halide_DIR` environment variable to the folder `<halide unzipped root>/lib/cmake/Halide` on your system
- build with cmake as usual. My CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.25)

project(HalideDemo)

find_package(Halide REQUIRED)

set(SOURCES
    lesson_01.cpp
)

add_executable(halide-demo ${SOURCES})

target_link_libraries(halide-demo PRIVATE Halide::Halide)
set_target_properties(halide-demo PROPERTIES CXX_STANDARD 17)
```

Note that this does not include the ZLIB, PNG or JPEG libraries. These can be obtained/built using [MXE](https://github.com/mxe/mxe).
