### ISSUE TITLE
GLSL backend doesn't round consistently vs. CPU backends

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#802]
Given a simple generator like:

```
ImageParam input{ UInt(8), 3, "input" };
Func build() override {
    Func output("output");
    output(x, y, c) = cast<uint8_t>(0.5f * cast<float>(input(x, y, c)));
    return output;
}
```

you may receive different results for the output on CPU vs GLSL backends, especially on mobile/ES2 backends. More investigation needed, but it appears that our GLSL backend needs some round-to-nearest for float->int conversion in order to match CPU backend output in a predictable manner.

**Comment by abestephensg** [comment]
I did an experiment earlier this spring with interpolation and conversion and observed different behavior between desktop driver implementations as well.  In those instances, it was also possible to change the rounding mode of the CPU code to match the behavior of a particular device running Halide generated code.  Right now, none of this behavior is specified by Halide- which is ok for many use cases, but others may have specific requirements that would limit the devices and Halide backends that they could be deployed on.

**Comment by zvookin** [comment]
Generally speaking it is going to be impossible to get consistent rounding
across backends. E.g. there is no efficient way to do round to nearest in
JavaScript so far as I can tell and even in C/C++ it is not an easy thing
to guarantee.

This said, code that is strictly integer should produce consistent results
across backends.

**Comment by steven-johnson** [comment]
I don't expect consistent rounding for FP across backends, but I do expect 8 * 0.5 to reliably round to 4 everywhere.

**Comment by zvookin** [comment]
I think the translation for this case to GLSL is (8 / 255.0f) * .5f *
255.0f. Is this the actual test case? What platform is it failing on? We
should see if adding high precision qualification helps. I'm a bit
surprised if such a simple case is going wrong unless the backend is
inserting something more complex or has a bug.

-Z-

**Comment by abestephensg** [comment]
This is an interesting case since the value cannot be represented exactly, i.e. 8/255 is 0x1.010101010101...p-5 and there are several steps that normalize and unnormalize it on both the CPU and GPU.

Here are the steps including texturing and conversion for this expression:
output(x, y, c) = cast<uint8_t>(0.5f * cast<float>(input(x, y, c)));

1.) the data in the input uint8 buffer_t is converted to a normalized texture
2.) x and y are interpolated across the drawn quad
3.) the texture is sampled at the interpolated coordinates and produces a normalized float value
4.) Halide inserts code that scales by 255.0 to unnormalize the value
5.) Perform the multiplication by 0.5
6.) Cast the float value to Halide uint8, Halide inserts a floor 
7.) Normalize the value and copy to the output color.
8.) The normalized output buffer is converted to uint8 by GL

The texture data conversion steps 1 and 8 are defined by the ES specification, but the precision and rounding of the coordinate interpolation that is used to read the input, and the arithmetic for the expression is not. I'm not sure if the input has a single value of 8/255 or if that is the value of a single texel, but any difference due to interpolation and texturing could be removed by replacing steps 1-4 and passing the input value as a uniform parameter, in a Halide Param.
