### ISSUE TITLE
Local Laplacian schedule

### ISSUE THREAD

**Issue by Joel911** [halide/Halide#810]
Hello, I'm still new to Halide, and I am looking into the local_laplacian in Halide/apps.
I found some of the Funcs like gPyramid and inGPyramid are scheduled as compute_root() while some others like lPyramid, floating and outLPyramid are not . (inlining) 

I am curious that if this schedule is the best one for local laplacian. 
So I tried so many other combinations (to decide every single Func being compute_root or not), but none of the schedules is better. They only get slower.

Here my question is how do you find this great schedule for local_laplacian? 
And how do I make my own schedule for a new application?
Is there some principle to make the decisions?
Because there are so many combinations and I got no clue.

I'm not sure if this is a proper question here.
Thank you very much.

**Comment by abadams** [comment]
If I recall correctly, it went like this:

I started with everything compute_root, parallelized over the outer loop
(y, or k), and vectorized over the inner loop. I didn't bother optimizing
the top pyramid levels - they're tiny compared to the inputs, so they take
approximately 0% of the runtime (I discovered this with HL_PROFILE=1).

I then tried inlining all the gaussian pyramid levels. That was slower. I
tried inlining the lapalacian pyramids. That was faster. I tried inlining
the bottom few levels of the Gaussian pyramid too. Turns out it was best to
inline the bottom ones only for gPyramid[0] and ingPyramid[0]. I then tried
a few compute_at options for the pyramids, but didn't get anywhere with
that, so everything's compute_root or inlined. I then messed with the size
of the parallel jobs. I changed that recently because my current machine
has two sockets, so memory access is non-uniform in weird ways so slightly
coarser-grained parallelism is better. Another thing I changed recently is
that gPyramid used to be parallel over k, but there are only 8 values of k
and my current machine has 32 hardware threads, so I moved the loop over k
inside the loop over y and parallelized y instead.

So the strategy is: Make everything compute_root, vectorized over innermost
and parallel over outermost, and then profile to identify which stages
matter, and then for each of those stages try all combinations of inlining,
compute_at, or compute_root and see what happens in the profile. Standard
profilers like oprofile work too if you've parallelized a stage, because
the parallel loop body gets emitted into a separate function.

Sometimes when a stage is really slow I also read the assembly to see if
there's anything nasty going on. I often also read the .stmt output to
check for anything dumb (e.g. accidentally inlined an expensive look-up
table, or vectorized an operation that doesn't really vectorize on this
archecture, like integer division on arm).
