### ISSUE TITLE
Win32 compiler errors: Halide.h redefines functions marked dll_import

### ISSUE THREAD

**Issue by ericbarnhill** [halide/Halide#830]
Halide.h contains the code:
# if defined(_WIN32) && defined(Halide_SHARED)
# ifdef Halide_EXPORTS
# define EXPORT __declspec(dllexport)
# else
# define EXPORT __declspec(dllimport)
# endif
# else
# define EXPORT
# endif

This doesn't work because:
-- Halide_EXPORTS is not defined anywhere
-- consequently EXPORT is always defined as __declspec(dllimport)
-- many functions possessing the EXPORT attribute have inline definitions later in Halide.h
-- ergo the Win32 compiler throws an error because the definition is marked dllimport

recommend changing to:
# if defined(_WIN32) && defined(Halide_SHARED)
# define EXPORT __declspec(dllexport)
# else
# define EXPORT
# endif

**Comment by delcypher** [comment]
@ericbarnhill What compiler are you using? When I build my [branch](https://github.com/delcypher/halide/tree/fix_llvm_cmake_build) under Windows with Visual Studio 2013 I don't run into compiler issues. The tutorials use this header file and they work fine.

According to [this](http://www.cmake.org/Wiki/BuildingWinDLL) ``Halide_SHARED`` will be automatically defined when building a DLL under a MSVC platform.

I also believe your fix is incorrect. If you have ``dllexport`` on a function when building a dll I think you need for the proto type to have ``dllimport`` when it is included by a user of the library.

**Comment by ericbarnhill** [comment]
I am on Ubuntu 14.04 trying to cross-compile my glnx64 app to a win32 target, against the Halide Win32 trunk. My makefile call is

%_win32.exe: ../%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: MinGW G++ Compiler'
	i686-w64-mingw32-g++ $(INCLUDES_WIN32) -shared -g3 -Wall -c -std=c++11 -o "$@" "$<"
	@echo 'Finished building: $<'

The app compiles for glnx64 but not win32.

Sorry if I proposed a wrong fix. That fix at least gets me through to the linker, but then the linker is having problems, perhaps for the reasons you mention.

**Comment by delcypher** [comment]
Ah I see. AFAICT the  ``Makefile`` was never designed with cross compilation in mind. The ``#ifdef Halide_EXPORTS`` is implicitly assuming you're using Windows and you're using CMake rather than the plain ``Makefile``.

So I guess your options are either teach the ``Makefile`` to define ``Halide_EXPORTS`` when building Halide as a shared library or to use CMake.

**Comment by abadams** [comment]
This is correct. The Makefile is entirely untested for windows builds.

**Comment by kgnk** [comment]
FYI, dllimport is a hint and is not strictly required.

**Comment by zvookin** [comment]
@abadams is there anything we can or need to do here?

**Comment by abadams** [comment]
It seems like the cmake build defines Halide_EXPORTS, and that's why things work on Windows, but I can't figure out how it does it. grepping is getting me nowhere. Maybe this is a builtin cmake thing?

The mingw build works with the Makefile, probably because it compiles with a different default symbol visibility. I guess it wouldn't hurt to add -DHalide_EXPORTS to the makefile.

**Comment by delcypher** [comment]
@abadams CMake implicitly adds `<target_name>_EXPORTS` define when building a shared library on windows. See http://stackoverflow.com/questions/27429732/cmake-adds-dlibname-exports-compile-definition.

For CMake you might want to use the [GenerateExportHeader](https://cmake.org/cmake/help/v3.8/module/GenerateExportHeader.html) function to generate a header file with the necessary macros and only include it when doing CMake builds so that the Makefile based build system doesn't need to care about the `dllexport` stuff.

**Comment by alexreinking** [comment]
We should probably re-evaluate our symbol export policy for the main Halide library. I would support using GenerateExportHeader. But this is a discussion to be had in a new issue. Closing...
