### ISSUE TITLE
saxpy performance only 70% of cBlas/OpenBlas

### ISSUE THREAD

**Issue by rodrigob** [halide/Halide#835]
According to
https://docs.google.com/spreadsheets/d/15pJP-oS4l_PZNvf63wcdxUNuaKwMOiQj-IMEAaUI-gw/edit#gid=0

Halide is reaching only 70% of "what is should" on simple operations like [saxpy](http://www.netlib.org/lapack/explore-html/d8/daf/saxpy_8f.html).

This is somewhat a performance bug. Any idea on how to push up the performance ? (I guess by changing the schedule function in the generator).

Also not clear if current benchmark is considering single or multithreaded options, @kree-colemcalughlin ?

**Comment by kree-colemcalughlin** [comment]
I believe the L1 operations did not use any parallelization in halide, as I
was not able to get any benefits and in fact saw some slow downs. However,
there have been some changes in halide since running these benchmarks that
may have fixed the issues with mutlithreading. So parallelism may be a
place to explore some performance improvements there.

In general, we spent more effort trying to optimize the higher order
operations, particularly gemm, so the scheduling of the L1 ops may just be
non-optimal. I am currently on another project and have not had time to
work on this recently. But I am hoping to take another pass at it sometime
in the relatively near future.

Cheers,
Kree

**Comment by rodrigob** [comment]
So (for saxpy at least) cBlas and OpenBlas are using the 12 cores, while Halide is not ?

**Comment by kree-colemcalughlin** [comment]
Very likely so.

**Comment by rodrigob** [comment]
Tried to compile `apps/linear_algebra` to benchmark on my machine but Halide apps compilation is broken, waiting for #825 to try again.

**Comment by delcypher** [comment]
@rodrigob #825 doesn't fix app compilation, it just disables building them because I haven't had time to look into fixing these.

**Comment by rodrigob** [comment]
:crying_cat_face:
