### ISSUE TITLE
undefined reference to `pthread_mutex_lock` and `halide_malloc`

### ISSUE THREAD

**Issue by janakiramreddy3** [halide/Halide#8472]
I am trying to run a simple halide program on riscv-64 baremetal target. I am able to compile the kernel using target string `riscv-64-noos-rvv-vector_bits_128`. but got below errors while linking with my `main.cpp`

undefined reference to `pthread_mutex_lock`
undefined reference to `pthread_mutex_init`
undefined reference to `pthread_cond_init`
undefined reference to `pthread_cond_wait`
undefined reference to `pthread_mutex_unlock`
undefined reference to `pthread_cond_signal`
undefined reference to `pthread_create`
undefined reference to `dlopen`
undefined reference to `dlsym`

undefined reference to `halide_malloc`
undefined reference to `halide_free`
undefined reference to `halide_print`

**Comment by mcourteaux** [comment]
This is desired behaviour. When you specify `noos` (i.e., _no operating system_), halide won't assume any os-specific runtime functions. This means it's your responsibility to provide them. On Linux, you could link with pthreads and dl. Afterwards you'd still need to specify the `halide_*` functions yourself.

Have a look at the runtime modules that get compiled into your pipeline when you specify `noos`:

https://github.com/halide/Halide/blob/a397712d3e6786f593a1e0f8ea8170d6363e97be/src/LLVM_Runtime_Linker.cpp#L1029-L1045

Pay attention to that comment:
https://github.com/halide/Halide/blob/a397712d3e6786f593a1e0f8ea8170d6363e97be/src/LLVM_Runtime_Linker.cpp#L1030-L1034


Alternatively, specify an OS. Either way, Halide will need these functions, because you have features in your pipeline that require them. Perhaps, you could try to reduce the surface of functions you need to provide. For example, specify `-no_asserts` to get rid of asserts (very much NOT recommended) (and their implied printing) and get rid of all multithreading (`async()`/`parallel()`).

Note that it's also possible to use `-no_runtime` for all your pipelines, and generate one runtime separately (with the AOT generator flag `-r`), which you link to your application, to avoid having all the runtime functions be included in every pipeline you compile. This is how I recommend working in serious projects with many pipelines.

**Comment by janakiramreddy3** [comment]
I am trying to use `vectorize(x, 8)` for computing `float` buffer, but it throws an error `illegal hardware instruction` for the same target `riscv-64-noos-rvv-vector_bits_256-no_asserts`. do I need to specify any other flags while applying these scheduling primitives? Thanks.

**Comment by janakiramreddy3** [comment]
sorry, I opened the issue again.

I defined `halide_malloc`, `halide_free`, `halide_print`, and `halide_error` functions and able to link it to my application. But when I run my program, the defined functions are not get called by the runtime. my main program is able to continue its execution irrespective of the `halide_malloc` implementation (even it if has semantic errors), it works fine for smaller buffers and getting failed for larger buffers.

could you help me, if any thing I missed here to able to make the defined functions used by halide runtime?

**Comment by mcourteaux** [comment]
Probably your particular pipeline does not require those functions? Although here, I'm not sure on what's going on. I would have expected the linker to not complain when there is no need for that function. Although perhaps more runtime functions exist that call out to `halide_malloc()`, but again you happen to not ever need one for your pipeline.

**Comment by janakiramreddy3** [comment]
@mcourteaux Thank you for your prompt response.

Here, I am trying to run the halide kernel on baremetal `riscv64` target. I assume the halide runtime must call the memory allocation functions I provided during the compilation (because it throws error `undefined reference to halide_malloc`, so provided) but It just ignores and able to execute the kernel for smaller inputs.

**Comment by mcourteaux** [comment]
If you want more detail, you'll have to share your generator code, and your compilation options (target triple with the selected target features). Note that Halide tries to allocate small temporary buffers from your schedule (Funcs scheduled with `.compute_at()`) on the stack. Those things are visible in the (conceptual) stmt files.

**Comment by janakiramreddy3** [comment]
@mcourteaux  Thank you very much for your assistance.

I tested a different schedule and noticed that the Halide runtime calls the defined `halide_malloc` function whenever the schedule includes a `.compute_at()` primitive that requires a temporary buffer. I now understand the issue I was facing earlier.

**Comment by janakiramreddy3** [comment]
@mcourteaux Thank you.
