### ISSUE TITLE
`performance_fast_pow`/`performance_fast_sine_cosine` fails on i386

### ISSUE THREAD

**Issue by LebedevRI** [halide/Halide#8536]
```
      Start 569: performance_fast_pow
 8/32 Test #569: performance_fast_pow ....................***Failed  Required regular expression not found. Regex=[Success!
]  2.86 sec
host is:          x86-32-linux-tune_znver3-avx-f16c-fma-sse41
HL_TARGET is:     x86-32-linux
HL_JIT_TARGET is: x86-32-linux-jit
powf: 35.943204 ns per pixel
Halide's pow: 375.072758 ns per pixel (rms error = 0.0000001623)
Halide's fast_pow: 316.049953 ns per pixel (rms error = 0.0000019084)
powf is faster than Halide's pow
```
```
      Start 570: performance_fast_sine_cosine
 9/32 Test #570: performance_fast_sine_cosine ............***Failed  Required regular expression not found. Regex=[Success!
]  1.36 sec
sin: 7.238321 ns per pixel
fast_sine: 171.935907 ns per pixel
cosine: 7.260333 ns per pixel
fast_cosine: 171.872918 ns per pixel
fast_sin is not faster than sin
```

**Comment by abadams** [comment]
Wow, that's more than a little slower. I'll investigate.

**Comment by abadams** [comment]
It's because the approximations use floor, but without sse4.1 we don't have a floor instruction, so we scalarize and defer to llvm.floor, which calls floorf as a library function a bunch. This is made even worse by passing arguments from xmm registers to floorf using the x87 fp stack.

We could try to emulate it more efficiently, but I'm not sure we should spend much effort on x86-32 prior to sse4.1. The last processor to ship that falls into that category was an Atom processor from 2008. I'll skip the test if we're on x86 without sse4.1.

We may want to discuss just requiring sse4.1 as our baseline for x86, rather than sse2 as we do currently.

**Comment by alexreinking** [comment]
> We may want to discuss just requiring sse4.1 as our baseline for x86, rather than sse2 as we do currently.

Added `dev_meeting` label to discuss this at the next dev meeting.

---

Relevant history:

* SSE4.1 was first added by Intel to Penryn (Core tick) in November 2007
* AMD added full support in Bulldozer in October 2011 (c.f. Intel's Sandy Bridge)
* Windows 10 and newer require at least a Broadwell Intel CPU
