### ISSUE TITLE
Should Halide::Internal::GeneratorBase::target should be private?

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#865]
fsticken@google.com suggests it should be private (and accessed via get_target()). However, there are existing uses that rely on being able to mutate this (e.g. to add a Feature to the Target; see Matlab code).

**Comment by abadams** [comment]
It is certainly convenient to be able to mutate it to turn on feature
flags, and the current syntax for mutating it is pretty gross. I'd say
leave it protected so that you can just say target instead of
.get_target(), but the fact that target is a GeneratorParam instead of an
actual Target is what makes the syntax weird. Maybe we should expose an
actual mutable Target object somehow.

**Comment by steven-johnson** [comment]
(It's actually public now, not protected.)

**Comment by zvookin** [comment]
@steven-johnson Can this be closed?

**Comment by steven-johnson** [comment]
Yep.
