### ISSUE TITLE
Let's rename "build" output dirs

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#873]
I'm experimenting with the Bazel build system, and running into an annoying problem: its build files are always named "BUILD" (all caps); on systems that have case-insensitive filesystems this makes maintaining both Make-based and Bazel-based builds impossible (and the .gitignore situation is uglier).

Strawman suggestion: Makefile -> "build-make", CMake -> "build-cmake"

(I'm happy to make this change but want buy-in on the general issue and specific replacement names before doing so)

**Comment by delcypher** [comment]
I've just had a chat with @steven-johnson about this as I wasn't exactly sure what he was proposing. This issue seems to stem from the fact we allow in-source builds (if we only did out of source builds this problem would not happen).

There is also a distinction that I feel is worth noting here. The ``build`` directory that @steven-johnson mentions only really exists in the Makefile build system, not in the CMake build. Although we do use ``build`` as the suggested name for the root build directory for CMake they function differently from each other

* The ``build`` directory for Makefile build system contains temporary object files but not the libraries and binaries, it must be located inside the source tree.
* The root build directory for CMake as the same suggests is the root of the build and **all** build files go here (not just the object files). This directory can be created anywhere and it is good practice to have this completely outside the source tree.

I felt that the strawman conflated these two as being the same which they are not.

I'm happy with the suggested rename for the Makefile build system but for the CMake build we should just tell people to build completely out of source (completely avoids a naming conflict). Here's an example of building completely out of source

```
% mkdir halide
% cd halide
% git clone https://github.com/halide/Halide.git halide_src
% mkdir build
% cd build
% LLVM_ROOT=/path/to/llvm3.5
% cmake -DLLVM_BIN=${LLVM_ROOT}/build/bin \
    -DLLVM_INCLUDE="${LLVM_ROOT}/include;${LLVM_ROOT}/build/include" \
    -DLLVM_LIB=${LLVM_ROOT}/build/lib -DLLVM_VERSION=35 \
    ../halide_source
% make -j8
```

**Comment by abadams** [comment]
In-source builds are bad. This is why all our build artifacts are in
folders outside of 'src' ;) You need a top-level directory to do your stuff
in. The question is, is this top-level directory the root dir of the repo,
or do you make a new local Halide directory for yourself and then check out
the repo within that into a subdirectory? Most open source projects seem to
do the former and have a 'src' directory within them. I think forbidding
this would confuse people used to the traditional "./configure && make &&
make install" incantation.

Anyway, the build artifacts folders are set by the Makefile variables
"BUILD_DIR" "BIN_DIR" and "DISTRIB_DIR". We could change the defaults to
avoid a bazel conflict. Does bazel have rules on where its BUILD file must
go? Can it go in src like the CMakeFile?

**Comment by steven-johnson** [comment]
Bazel defaults to using a complex symlinked directory structure, but everything is named "bazel-bin", "bazel-genfiles", etc, so avoiding "bazel-*" will do the trick.

It does require files named BUILD and WORKSPACE in a few places, though.

**Comment by delcypher** [comment]
> In-source builds are bad. This is why all our build artifacts are in
folders outside of 'src' ;) You need a top-level directory to do your stuff
in.

I'd still call that in-source ;) There isn't a single directory I can delete that deletes all the build files and leaves the source tree untouched and the files are still inside the directory containing the git repository.

> The question is, is this top-level directory the root dir of the repo,
or do you make a new local Halide directory for yourself and then check out
the repo within that into a subdirectory?

I much prefer the later, it allows for multiple build configurations from a single source tree. For example I can use the same source tree for a build of Halide against LLVM 3.5, 3.6 and trunk.

> I think forbidding
this would confuse people used to the traditional "./configure && make &&
make install" incantation.

We don't really follow that convention anyway do we? There is no configure script and no working ``install`` target AFAIK.

**Comment by steven-johnson** [comment]
Sounds like changing the README and the defaults for BUILD_DIR (etc) are the low-hanging fruit here (along with any possible buildbot issues). I'll prep a PR for that.

**Comment by steven-johnson** [comment]
Bikeshed possibilities for renaming "build"

(1) move to a subdir under "bin" (i.e. bin/build), leaving only bin and distrib at toplevel
(2) s/build/built/ (z's suggestion)
(3) s/build/genfiles/ (blaze/bazel naming convention)
(4) prefix all of them, e.g. "make-build", "make-bin", "make-distrib"

I tend to lean towards (1), unless packaging conventions / expectations of what the "bin" directory contains precludes this.

**Comment by steven-johnson** [comment]
Re: delcypher's suggestion about building "completely out of source", while this is possible with CMake, it isn't possible (or at least practical) with all build systems, AFAIK; if settling for a well-defined set of toplevel-only build-artifact directories is the best we do, I think it's better to promote this for CMake as well, to reduce complexity.
