### ISSUE TITLE
Feature Request: generate glue code for runtime CPU feature detection

### ISSUE THREAD

**Issue by steven-johnson** [halide/Halide#879]
For AOT Generators, it's common to want to take advantage of certain CPU features but fallback when not present; e.g., on x86-64, you probably want to build AVX, SSE4.1, and 'baseline' .o files, then choose the best to use at runtime.

It would be nice if the Generator infrastructure in Halide had a standard way of specifying this, and of generating the appropriate wrapper code, rather than having Halide users reinvent this particular wheel.

**Comment by abadams** [comment]
The easiest thing might be to express the switcher as a Halide::Module that
dispatches to the correct thing and includes a baseline runtime. Then the
variants would be compiled with NoRuntime. We'd need some new runtime
functions to do the feature detection.

Could also probably emit a jumbo header.

**Comment by zvookin** [comment]
+1 on the Halide::Module idea. I was also thinking of this re: the
discussion on including all the runtime declarations in the generated .h
file. That would multiply against the multiple version compile if it is not
somehow encapsulated inside Halide. (Or done with noruntime.)

**Comment by aTinker** [comment]
This would be very useful.

I am trying to understand the Halide::Module solution discussed above. 
How would this module know the entry points for each of the SIMD specializations? Would those be autogenerated and internal, in which case there is just one external entry point - if so, then the comment about a jumbo header is confusing me. 

I am trying to explore something along these lines, sharing some of my approach/needs:
- Using the approach shown in Generators tutorial (15), using a predefined function naming scheme (e.g. myalgo, myalgo_sse4, myalgo_avx etc). 
- Combining the .o's into one shared library per pipeline (i.e there might be myalgo.so, myanotheralgo.so etc)
- Plan to write a common dispatch library which sits on top of this
  -Takes in a string ('myalgo' or 'myanotheralgo')
  -Dynamically dispatches (dlopen/dlsym/dlclose) to the correct .so, and function based on highest available SIMD version using function pointers
  -Cross x86 OS platform (Windows/Mac/Linux)
  -For testing: have a switch to turn off auto dispatch and force a particular SIMD version

Andrew's comment makes me think I ought to move the runtime to the dispatch layer, so I just have one copy instead of one each in myalgo.so/myanotheralso.so.


Any other/better way to do this currently? 


Ashish
Image Processing, Mathworks

**Comment by steven-johnson** [comment]
The approach I had in mind would have the specializations internally generated and hidden, so there is (still) only one external entry point.

Specifically, the design I've been thinking of would allow you to combine arbitrary specializations via a new runtime function (let's call it "halide_can_use_specialization" for argument) for choosing between them. in handwavy pseudocode, you'd compile a Generator with arbitrary targets in a specific order:

     my_generator.compile("x86_64_avx", "x86_64_sse41", "x86_64")

this would generate a single entry point that would have code like:

    int my_generator_function(...) {
      // Try each specialization in the order listed; choose the first that
      // halide_can_use_specialization() says is acceptable.
      if (halide_can_use_specialization("x86_64_avx") {
        return my_generator_function_x86_64_avx(...);
      }
      if (halide_can_use_specialization("x86_64_sse41") {
        return my_generator_function_x86_64_sse41(...);
      }
      if (halide_can_use_specialization("x86_64") {
        return my_generator_function_x86_64(...);
      }
      return kErrorNoSpecialization;
    }

Note 1: you'd probably want to restrict this to targets with matching cpu, os, and bit size.
Note 2: you'd definitely want to cache the result of this test, so you only pay for the calls to halide_can_use_specialization() on the first call.

[The "jumbo header" refers to the idea of emitting multiple entry points (one for each specialization) and then adding much more complex code in the Halide-generated header (e.g. inline functions that dispatch to the right specialization). An approach like this is used inside Google and while it works, it has drawbacks (e.g. inline functions don't mix well with code that needs function pointers, like define_extern()).]

**Comment by steven-johnson** [comment]
Right now, the Target::Feature flags are a compile-time only set of flags (not visible to runtime). I'd like to consider moving them to HalideRuntime.h so that they can be used as the argument to the new runtime callback needed, e.g.

    // return true iff every Feature in feature_mask can be used in the current runtime environment.
    // result may be cached.
    bool halide_can_use_features(uint64_t feature_mask);

Gotchas:
-- Conceptually, do we want Features exposed to the Runtime?
-- Features have to remain (relatively) stable (shouldn't be an issue)
-- we're already up to ~30 Features; if/when we pass 64, we'll have to rethink the structure here, which will be a minor breaking change

**Comment by zvookin** [comment]
We now have fully featured multi-target support that addresses this issue.
