### ISSUE TITLE
``le64-unknown-unknown-unknown`` target used for runtime has wrong calling convention under x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by delcypher** [halide/Halide#924]
#919 is currently blocked because of incorrectly generated runtime code.

In that PR I've added a "pure runtime" test that tries to call into a function in Halide's generated standalone runtime. This test current fails because there is a mismatch between the calling convention used to build the test and the calling convention used in the generated standalone run time on Linux x86_64.

My test tries to do

```
halide_float16_t_to_float(in);
```

At the call site the generated assembly puts the argument into `%edi`

```
0x409080 <main()+775>   movzwl -0x130(%rbp),%eax                                                                                                                                                               
0x409087 <main()+782>   mov    %eax,%edi
0x409089 <main()+784>   callq  0x408c50 <halide_float16_t_to_float(halide_float16_t)> 
```

In the callee  it tries to read the argument from the stack and put it into `%esi`.

```
0x408c50 <halide_float16_t_to_float(halide_float16_t)>          push   %rbp                                                                                                                                    
0x408c51 <halide_float16_t_to_float(halide_float16_t)+1>        mov    %rsp,%rbp                                                                                                                               
0x408c54 <halide_float16_t_to_float(halide_float16_t)+4>        movzwl 0x10(%rbp),%esi                                                                                                                         
0x408c58 <halide_float16_t_to_float(halide_float16_t)+8>        mov    %esi,%edx                                                                                                                               
0x408c5a <halide_float16_t_to_float(halide_float16_t)+10>       shl    $0x10,%edx 
```

and so the function reads the incorrect value for the argument.

I've found if I change the target used by clang to generate the 64-bit runtime from `le64-unknown-unknown-unknown` to  `x86_64-unknown-linux-gnu` then the problem is fixed.

I glanced at the LLVM IR generated using the different target triples. The halide runtime function I call appears to get a different signature...

**le64-unknown-unknown-unknown**

```
target datalayout = "e-m:e-v128:32-v16:16-v32:32-v96:32-n8:16:32:64-S128"
target triple = "le64-unknown-unknown-unknown"

%struct.halide_float16_t = type { i16 }
%union.anon = type { float }

; Function Attrs: nounwind
define weak float @halide_float16_t_to_float(%struct.halide_float16_t* byval %value) #0 {
entry:
  tail call void @llvm.dbg.declare(metadata %struct.halide_float16_t* %value, metadata !18, metadata !54), !dbg !55
  %data = getelementptr inbounds %struct.halide_float16_t, %struct.halide_float16_t* %value, i64 0, i32 0, !dbg !56
  %0 = load i16, i16* %data, align 2, !dbg !56, !tbaa !57
  tail call void @llvm.dbg.value(metadata i16 %0, i64 0, metadata !19, metadata !54), !dbg !62
  %conv = zext i16 %0 to i32, !dbg !63
  %and = shl nuw i32 %conv, 16, !dbg !64
  %shl = and i32 %and, -2147483648, !dbg !64
  tail call void @llvm.dbg.value(metadata i32 %shl, i64 0, metadata !20, metadata !54), !dbg !65
  tail call void @llvm.dbg.declare(metadata %union.anon* undef, metadata !23, metadata !54), !dbg !66
  %and2 = and i32 %conv, 1023, !dbg !67
  tail call void @llvm.dbg.value(metadata i32 %and2, i64 0, metadata !28, metadata !54), !dbg !68
  %and4 = lshr i32 %conv, 10, !dbg !69
  %shr.55 = and i32 %and4, 31, !dbg !69
  tail call void @llvm.dbg.value(metadata i32 %shr.55, i64 0, metadata !29, metadata !54), !dbg !70
  %cmp = icmp eq i32 %shr.55, 0, !dbg !71
  %cmp5 = icmp ne i32 %and2, 0, !dbg !72
  %or.cond = and i1 %cmp5, %cmp, !dbg !73
  br i1 %or.cond, label %if.then, label %if.else, !dbg !73
...
```

**x86_64-unknown-linux-gnu**

```
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.halide_float16_t = type { i16 }
%union.anon = type { float }

; Function Attrs: nounwind
define weak float @halide_float16_t_to_float(i16 %value.coerce) #0 {
entry:
  tail call void @llvm.dbg.value(metadata i16 %value.coerce, i64 0, metadata !18, metadata !54), !dbg !55
  tail call void @llvm.dbg.declare(metadata %struct.halide_float16_t* undef, metadata !18, metadata !54), !dbg !55
  tail call void @llvm.dbg.value(metadata i16 %value.coerce, i64 0, metadata !19, metadata !54), !dbg !56
  %conv = zext i16 %value.coerce to i32, !dbg !57
  %and = shl nuw i32 %conv, 16, !dbg !58
  %shl = and i32 %and, -2147483648, !dbg !58
  tail call void @llvm.dbg.value(metadata i32 %shl, i64 0, metadata !20, metadata !54), !dbg !59
  tail call void @llvm.dbg.declare(metadata %union.anon* undef, metadata !23, metadata !54), !dbg !60
  %and2 = and i32 %conv, 1023, !dbg !61
  tail call void @llvm.dbg.value(metadata i32 %and2, i64 0, metadata !28, metadata !54), !dbg !62
  %and4 = lshr i32 %conv, 10, !dbg !63
  %shr.55 = and i32 %and4, 31, !dbg !63
  tail call void @llvm.dbg.value(metadata i32 %shr.55, i64 0, metadata !29, metadata !54), !dbg !64
  %cmp = icmp eq i32 %shr.55, 0, !dbg !65
  %cmp5 = icmp ne i32 %and2, 0, !dbg !66
  %or.cond = and i1 %cmp5, %cmp, !dbg !67
  br i1 %or.cond, label %if.then, label %if.else, !dbg !67
...
```

**Comment by delcypher** [comment]
Side note I think this issue is caused by how the different targets handle a struct being passed by value. I may be able to avoid this issue if pass the struct by a pointer or just pass a ``uint16_t`` around.

**Comment by abadams** [comment]
Yuck. We operate under the assumption that the translation from c++ to ll
is architecture-neutral enough that we don't need to precompile the runtime
to different ll for every possible target triple - it's enough to just fix
the target triple later.

This breaks down in one or two places. E.g. the stdcall calling convention
in win32 appears in the .ll, and struct alignment is abnormally
conservative with le64-unknown-unknown-unknown. Looks like passing structs
by value is another of those places.

Sigh. Perhaps the typedef solution is worth another look?

**Comment by delcypher** [comment]
> Yuck. We operate under the assumption that the translation from c++ to ll
is architecture-neutral enough that we don't need to precompile the runtime
to different ll for every possible target triple - it's enough to just fix
the target triple later.

One slightly crazy way to fix this would be use clang as a library and embed the runtime source into halide and then compile on demand based on the target. Bundling Clang might take more space than compiling the runtime for every target of interest though...

> Sigh. Perhaps the typedef solution is worth another look?

Sure, that'll probably work. It's just less type safe. It will also cause problems if the ``Printer`` in the runtime needs a ``operator<<()`` overload for ``uint16_t``.

**Comment by abadams** [comment]
Yeah, that's why I'm not crazy about the typedef solution.

It's a long shot, but you might want to test throwing a
HALIDE_ATTRIBUTE_ALIGN(2) on the uint16_t member or a pragma packed on the
struct.

Maybe the calling convention is OK, but the generic target triple messes
with struct layout in such a way that passing the argument as an i16 is not
correct behavior.

**Comment by abadams** [comment]
Another (also icky) possibility: Make those functions accept a float16_t by
const ref instead of by value, and add a deleted copy constructor if
COMPILING_HALIDE_RUNTIME is defined to stop anyone from passing it by value
in the runtime itself.

**Comment by zvookin** [comment]
I ran into issues with passing structs by value in the Objective-C glue
code for Metal as well. I could not get a single target plus faked call
argument types to work for for all four cases in (32/64-bit) x (ARM/X86). I
decided this was specific to Objective-C, and did find some code
controlling the lowering in clang's Objective-C frontend, but I didn't
really sort out every last detail. (This is why there
are metal_objc_arm.cpp and metal_objc_x86.cpp files.)

-Z-

**Comment by delcypher** [comment]
I've ended up using a typedef to work around the passing struct by value issue.

Does Halide really benefit that much from compiling "generic-ish" LLVM IR (``le64-unknown-unknown-unknown``) instead of compiling per target triple?

The only advantage I see to current set up is making ``libHalide`` smaller but I'm not really convinced that matters because someone who wants a small binary will probably compile their Halide code AOT and not bundle ``libHalide`` is their application. There is also the minor advantage of faster compile time (of Halide itself) but building the runtime is super fast anyway (at least if you use CMake with Ninja)

Do we really have that many target triples to support?

If that number is small I think it would be better to compile the runtime per target triple and provide CMake and Makefile options to properly disable certain targets and target triples if needed (i.e. don't build the runtime for that target triple).

**Comment by zvookin** [comment]
"Do we really have that many target triples to support?" theoretically it
is every OS/environment llvm supports for every architecture we support.
Ideally we end up supporting every architecture llvm does. So yes, it is a
lot of targets. A bigger problem is it means that the entire set has to be
enumerated when we build Halide.

Another possible solution would be to enumerate all the lowering decisions
that are made in converting the runtime code to bitcode and to compile each
module with target flags sufficient to cover all the possibilities that are
actually used. This still requires a mapping table to select the right
input for each final target. What we are doing now is effectively a subset
of this where we work to write the runtime code such that there is exactly
one target needed to cover all the final outputs.

Philosophically, our goal is to make supporting output targets really easy
and scalable. Even more so than llvm does. We are willing to accept
restrictions in the code we can write in the runtime in order to achieve
this.

I expect we'll ultimately end up embedding clang, possibly with cling
support to make the JIT even more powerful. But it doesn't seem necessary
immediately.

-Z-

**Comment by abadams** [comment]
I wrote some code to enumerate them by calling get_triple_for_target on
every possible Halide::Target arch, os, and bit-width (and toggling the
feature flags mentioned in get_triple_for_target). The code ended up being
a little ad-hoc to dance around the errors you get when you ask for things
like ios on mips. There are 21 different target triples we support (see
below). That covers 32 and 64-bit, but not debug vs not debug, so this
would increase the amount of space taken by the cpp initial modules by
about a factor of 10. The cpp initial modules currently take 4.8 MB of
space in libHalide. Expanding that to 50MB seems bad. Much of that code
would be unused (e.g. cuda on ios), but figuring out which ones make sense
to include would involve a lot of logic.

I was hoping this would come out as a viable solution, because calling
convention headaches are indeed a pain in the ass (and often very difficult
to debug). Maybe the data is highly redundant and thus highly compressible?
Making a compressed database of initial modules seems like more complexity
than the hoops we jump through to keep the initial modules neutral.

Notes on the below:
- windows elf is for jitting on windows. llvm wants elf instead of coff for
that
- linux-eabi vs linux-gnueabihf is android vs ubuntu
- I forgot to include the nacl/pnacl target triples

aarch64--linux-eabi

aarch64--linux-gnueabihf

aarch64-apple-ios

arm--linux-eabi

arm--linux-gnueabihf

arm-apple-ios

armv7s--linux-eabi

armv7s--linux-gnueabihf

armv7s-apple-ios

i386--linux-android

i386--linux-gnu

i386-apple-macosx

i386-pc-windows-msvc

i386-pc-windows-msvc-elf

mips64el--linux-android

mipsel--linux-android

x86_64--linux-android

x86_64--linux-gnu

x86_64-apple-macosx

x86_64-pc-windows-msvc

x86_64-pc-windows-msvc-elf

**Comment by alexreinking** [comment]
Is this still current?
