### ISSUE TITLE
GPU scheduling causes segfault

### ISSUE THREAD

**Issue by bobobo1618** [halide/Halide#968]
I'm running the code at https://github.com/bobobo1618/halideraw (`AOT_run_test.cpp`) generated with `target=host-profile-opencl` but with the following modified GPU schedule:

``` c++
output.reorder_storage(c, x, y).reorder(c, x, y);
output.unroll(c);

output.compute_root();

input.compute_at(output, Var::outermost());
input.unroll(x, 2).unroll(y, 2);
input.vectorize(x, 16);

ig_horizontal.compute_at(output, Var::outermost());
ig_horizontal.vectorize(x, 8);

cd_gradient_plane_horizontal.compute_at(ig_horizontal, Var::outermost());
cd_gradient_plane_horizontal.vectorize(x, 16);

ig_vertical.compute_at(output, Var::outermost());
ig_vertical.vectorize(x, 8);

cd_gradient_plane_vertical.compute_at(ig_vertical, Var::outermost());
cd_gradient_plane_vertical.vectorize(x, 16);

pass2.compute_at(output, Var::outermost());
pass2.vectorize(x, 8);

green_horizontal.compute_at(pass2, Var::outermost());
green_vertical.compute_at(pass2, Var::outermost());

pmn_h.compute_at(pass2, Var::outermost()).vectorize(x, 8);
pmn_v.compute_at(pass2, Var::outermost()).vectorize(x, 8);
pmn_d.compute_at(pass2, Var::outermost()).vectorize(x, 8);


green_unenhanced.compute_at(output, Var::outermost());
green_unenhanced.vectorize(x, 8);

d_hat_top_known.compute_at(output, Var::outermost());
d_hat_top_known.vectorize(x, 8);

d_hat_top_diagonal.compute_at(output, Var::outermost());
d_hat_top_diagonal.vectorize(x, 8);

output.gpu_tile(x, y, 16, 16);
```

And I consistently get a SIGSEGV when running. Replacing all the `compute_at` with `compute_root` seems to resolve this.

**Comment by abadams** [comment]
Adding -debug to the target is helpful to see how Halide is using the
OpenCL api. The problem is that most of your stages run on the CPU,
including the ones that read from the input, but you've set the input host
pointer to NULL after calling copy_to_device. This might work if the stage
that reads the input is scheduled on the GPU.

The action item here for us it to trigger an error message inside
copy_to_host if the host pointer is null.

**Comment by abadams** [comment]
Actually no, copy_to_host is doing nothing because the dirty flag is false.
The problem is that the input host pointer is null and it's read from by
the first stage of the pipeline. I suppose we should compile in an
assertion that the input host pointer is non-null if the device pointer is
valid but the buffer is touched on the CPU.

**Comment by bobobo1618** [comment]
Ah, I see. I'd assumed that since the outermost function was scheduled on the GPU, the computations contained within it would be too.

Throwing `gpu_tile` on everything seems to have worked.

**Comment by zvookin** [comment]
"the computations contained within it" -- you have to be careful with the
thinking around "contained". If they are inline, they will be on the GPU
without having to do anything. If they are scheduled as roots, one has full
control. Often one computes some roots on the CPU either because it is
faster or because the GPU API being used is not capable enough to do the
computation. (A trivial example is a computation that requires extern
calls.) I believe compute_at inside a GPU kernel scheduled loop nest also
runs on the GPU, but it may depend on the level in the loop nest, where
outermost is on the CPU.

-Z-

**Comment by bobobo1618** [comment]
That makes sense. I was looking at the output of `print_loop_nest` and saw everything indented as 'contained by' the last unindented line. Should have thought about it a bit more.

**Comment by dsharletg** [comment]
It sounds like this is resolved.
