### ISSUE TITLE
Static compilation of tutorials

### ISSUE THREAD

**Issue by SanderVocke** [halide/Halide#972]
Hey everyone,

Sorry to bother you here, but I am having trouble compiling the Halide tutorials. Using the method suggested in the tutorial comments, using the shared object library, it all works fine. But I cannot seem to compile against the static library.

I set up a Makefile which effectively runs these two commands: 
g++  -I(...)/Halide/include -g -std=c++11  -c -o lesson_01_basics.o lesson_01_basics.cpp
g++  -I(...)/Halide/include -g -std=c++11 -L(...)/Halide/bin -g -lHalide -lpthread -ldl -lz lesson_01_basics.o -o halide_tutorial_1

This results in loads of undefined references, including ones such as Halide::Var::Var, Halide::Func::Func and many others.

Do you have any suggestions?

**Comment by SanderVocke** [comment]
FYI: this is on Ubuntu 14.04 32-bit, Halide built from source with LLVM 3.5, using gcc 4.8.4.

**Comment by delcypher** [comment]
You didn't say which build system you are using but I presume you are using the ``Makefile`` build system. I can reproduce the issue there. Which needs fixing.

If you use the CMake build system it will build the tutorials for you by default (``-DWITH_TUTORIALS=ON``) and can optionally build using a static Halide library (just pass ``-DHALIDE_SHARED_LIBRARY=OFF`` when you invoke ``cmake``). Note that linking will take a long-time when using the CMake build and building ``libHalide`` statically because the CMake build doesn't try to embed the contents of the LLVM libraries in the archive and generate an index.

**Comment by delcypher** [comment]
@SanderVocke Oh wait, there's nothing wrong with Halide here.

The problem is the order you've specified the command line arguments. You need to list the source file before you list the libraries due to the way gcc resolve dependencies (parsing left to right it builds up a list of unresolved symbols, therefore the source file needs to come first).

For example running this in the ``tutorial`` directory (when I build using the ``Makefile`` build system and delete ``bin/libHalide.so``) on my system works

```
g++ -std=c++11 -I ../include/ -L ../bin/ lesson_01_basics.cpp  -lHalide $(llvm-config --system-libs) -o test_prog
```

**Comment by SanderVocke** [comment]
@delcypher 

Thanks very much, that did the trick!
